import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { GUIDES } from '../src/mandats/content/guides.ts';
import { escape as e } from '../src/mandats/sharing.ts';
const dist = fileURLToPath(new URL('../dist/',import.meta.url));
const html = await readFile(dist+'mandats/index.html','utf8');
const styles = [...html.matchAll(/<link[^>]+rel="stylesheet"[^>]*>/g)].map(m=>m[0]).join('');
const origin = 'https://500signatures.fr';
function page(title:string,description:string,path:string,body:string,schema:unknown) { return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,follow"><title>${e(title)} · Mandats</title><meta name="description" content="${e(description)}"><link rel="canonical" href="${origin+path}"><meta property="og:type" content="article"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${origin+path}"><meta name="twitter:card" content="summary">${styles}<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body><a class="skip-link" href="#lecture">Aller au contenu</a><header class="site-header"><a href="/mandats/" class="brand"><strong>MANDATS</strong></a><a href="/mandats/comprendre/">Comprendre les arbitrages</a></header><main class="method-content" id="lecture">${body}</main><footer class="site-footer"><a href="/mandats/">Jouer</a><a href="/mandats/methode/">Règles et confidentialité</a><span>Rédaction assistée par IA · Sources consultées le 5 septembre 2026</span></footer></body></html>`; }
const indexPath='/mandats/comprendre/';
await mkdir(dist+indexPath,{recursive:true});
await writeFile(dist+indexPath+'index.html',page('Comprendre les arbitrages publics','Quatre guides sourcés pour comprendre les compromis du jeu.',indexPath,`<p class="eyebrow">LES CHOIX, EXPLIQUÉS</p><h1>Comprendre avant de décider.</h1><p>Des repères sourcés, puis un scénario pour mettre les compromis à l’épreuve. Les données du jeu restent fictives.</p><div class="guide-list">${GUIDES.map(g=>`<article><p class="eyebrow">${g.mode==='municipal'?'FINANCES LOCALES':'FINANCES NATIONALES'}</p><h2><a href="${indexPath+g.slug}/">${e(g.title)}</a></h2><p>${e(g.summary)}</p></article>`).join('')}</div>`,{'@context':'https://schema.org','@type':'CollectionPage',name:'Comprendre les arbitrages publics',url:origin+indexPath}));
for(const guide of GUIDES){
 const path=indexPath+guide.slug+'/';await mkdir(dist+path,{recursive:true});
 const body=`<nav aria-label="Fil d’Ariane"><a href="/mandats/">Mandats</a> / <a href="${indexPath}">Comprendre</a></nav><p class="eyebrow">REPÈRES SOURCÉS · ${guide.mode==='municipal'?'VILLE':'PAYS'}</p><h1>${e(guide.title)}</h1><p class="lead">${e(guide.summary)}</p>${guide.sections.map(s=>`<section><h2>${e(s.title)}</h2>${s.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}</section>`).join('')}<h2>Sources et périmètre</h2><ul>${guide.sources.map(s=>`<li><a href="${e(s.url)}">${e(s.title)}</a>${s.date?` · ${s.date}`:''}</li>`).join('')}</ul><p>Aucun paramètre de Mandats n’est une observation statistique. Ces repères n’ont pas valeur de conseil financier ou juridique.</p><a class="button primary" href="/mandats/?v=4&ambition=equilibre&mode=${guide.mode}&seed=42">Tester ce type d’arbitrage</a><h2>Pour poursuivre</h2><ul>${GUIDES.filter(g=>g.slug!==guide.slug).map(g=>`<li><a href="${indexPath+g.slug}/">${e(g.title)}</a></li>`).join('')}</ul>`;
 await writeFile(dist+path+'index.html',page(guide.title,guide.summary,path,body,{'@context':'https://schema.org','@type':'Article',headline:guide.title,description:guide.summary,datePublished:'2026-09-05',dateModified:'2026-09-05',mainEntityOfPage:origin+path,citation:guide.sources.map(s=>s.url)}));
}
console.log('Mandats : 4 guides sourcés et leur index, noindex pendant validation.');
