import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';

// The code and its authored kit must share a revision even while an older
// opt-in service worker is active. Public model files retain readable names.
const models = { architecture: 'glb', vegetation: 'glb', paris: 'glb', cathedrale: 'glb', daylight: 'env' } as const;
const urls: Record<string, string> = {};
for (const [name, extension] of Object.entries(models)) {
  const file = new URL(`../public/mandats/models/${name}.${extension}`, import.meta.url);
  const digest = createHash('sha256').update(await readFile(file)).digest('hex').slice(0, 16);
  urls[name] = `/mandats/models/${name}.${extension}?v=${digest}`;
}
const target = new URL('../src/mandats/map-model-revisions.ts', import.meta.url);
const source = `// Generated by scripts/mandats-model-revisions.ts from the actual asset content.\nexport const MODEL_URLS = ${JSON.stringify(urls, null, 2)} as const;\n`;
if (await readFile(target, 'utf8').catch(() => '') !== source) await writeFile(target, source);
