/** Search snippets describe the page; published verdicts stay complete in its body. */
export const SEARCH_DESCRIPTIONS: Readonly<Record<string, string>> = {
  '/analyses/age-achat-residence-principale/': 'Accès à la propriété : les parcours des générations, le poids des revenus, de l’apport et des conditions de crédit dans le premier achat.',
  '/analyses/championne-du-monde-prelevements-2024/': 'Prélèvements en 2024, cotisations imputées comprises : 45,2 % du PIB en France, 45,4 % au Danemark et 40,2 % dans l’UE. Comparaison Eurostat.',
  '/analyses/defense-credits-votes-consommes-2025/': 'Budget de la défense 2025, pensions comprises : 59,9 milliards votés et 62,1 milliards dépensés. Comprendre les crédits ouverts et leur exécution.',
  '/analyses/defense-europe-depenses-2024/': 'Dépenses de défense en Europe : 266 milliards d’euros en 2024. Suivez la hausse depuis 2020 et la répartition entre salaires, achats et investissement.',
  '/analyses/electricite-exportee-facture-francais/': 'La France exporte de l’électricité, tandis que les factures financent l’énergie, les réseaux et les taxes. Les contrats transmettent les prix dans le temps.',
  '/analyses/fournitures-scolaires-prix-1990-2025/': 'Papier, énergie, marques, listes scolaires et aides : pourquoi la rentrée reste chère après la flambée de 2023, avec des prix en euros et des sources croisées.',
  '/analyses/groenland-accord-securite-europe/': 'Accord de sécurité au Groenland signé le 22 septembre 2026 : texte publié, intérêts européens et distinction entre signature et application.',
  '/analyses/la-depense-publique-baisse-2024/': 'Dépenses, croissance annuelle et part du PIB : les comptes Insee 2025 montrent pourquoi les conclusions changent selon la mesure et les années comparées.',
  '/analyses/prix-gaz-menages-2022-2025/': 'Le prix TTC du gaz augmente d’environ 42 % entre fin 2022 et fin 2025 pour les ménages D2. Le coût hors taxes et les prélèvements contribuent à la hausse.',
  '/analyses/retraites-premier-poste-2024/': 'En 2024, 362,2 milliards d’euros de prestations de vieillesse en France, minima compris et survie exclue. Poids et financement des retraites.',
  '/analyses/satisfaction-vie-france-2010-2024/': 'La satisfaction dans la vie remonte à 7,2 sur 10 en 2024. Revenus, emploi, santé et relations sociales éclairent les écarts entre les Français.',
  '/analyses/ukraine-pret-europeen-90-milliards/': 'Prêt européen de 90 milliards d’euros à l’Ukraine : emprunt, intérêts et remboursement. Le Conseil indique 14,9 milliards versés au 24 septembre 2026.',
  '/questions/age-premier-achat-residence-principale/': 'Quel âge ont les primo-accédants ? Une réponse sourcée pour distinguer premier achat, ensemble des acheteurs et évolution historique.',
  '/questions/arenh-42-euros-etranger/': 'À qui était destiné l’ARENH à 42 €/MWh ? Comprenez la différence entre accès régulé au nucléaire et exportations d’électricité.',
  '/questions/electricite-vendue-moins-chere-etranger/': 'Pourquoi le prix de l’électricité exportée diffère-t-il de votre facture ? Réponse sur le marché de gros, le réseau et les taxes.',
  '/questions/hausse-prix-gaz/': 'Le gaz a-t-il encore augmenté en France ? Une réponse sourcée qui précise la période, le prix observé et les taxes.',
  '/questions/prix-fournitures-scolaires/': 'Comment les prix des fournitures scolaires ont évolué depuis 1990 et pourquoi les hausses récentes pèsent sur les achats de rentrée.',
  '/questions/qualite-vie-france/': 'La qualité de vie baisse-t-elle en France ? Consultez la réponse et les limites des données de satisfaction déclarée.',
};
