/** Search snippets describe the page; published verdicts stay complete in its body. */
export const SEARCH_DESCRIPTIONS: Readonly<Record<string, string>> = {
  '/analyses/age-achat-residence-principale/': 'Premier achat immobilier : ce que les données permettent de dire sur l’âge des acquéreurs, avec les limites des comparaisons historiques.',
  '/analyses/championne-du-monde-prelevements-2024/': 'Prélèvements obligatoires : comparez la France aux pays couverts par les données publiées et comprenez les limites du classement.',
  '/analyses/defense-credits-votes-consommes-2025/': 'Dépenses de défense en 2025 : comparez les crédits votés au budget initial et aux dépenses exécutées, avec les comptes publics à l’appui.',
  '/analyses/defense-europe-depenses-2024/': 'Dépenses de défense en Europe : 266 milliards d’euros en 2024. Suivez la hausse depuis 2020 et la répartition entre salaires, achats et investissement.',
  '/analyses/electricite-exportee-facture-francais/': 'Électricité exportée et facture des Français : distinguez prix de gros, contrats, réseau et taxes à partir des sources publiées.',
  '/analyses/fournitures-scolaires-prix-1990-2025/': 'Prix des fournitures scolaires : comparez leur évolution à celle des prix à la consommation, avec les sources et les limites de la série.',
  '/analyses/groenland-accord-securite-europe/': 'Accord de sécurité au Groenland : ce qui est annoncé pour l’Arctique, ce qui doit encore être ratifié et les intérêts européens en jeu.',
  '/analyses/la-depense-publique-baisse-2024/': 'Dépense publique : pourquoi une baisse en part du PIB ne signifie pas une baisse en euros. Consultez les comptes et leur périmètre.',
  '/analyses/prix-gaz-menages-2022-2025/': 'Prix du gaz pour les ménages : évolution, taxes et périmètres de comparaison expliqués à partir des données publiées.',
  '/analyses/retraites-premier-poste-2024/': 'Les retraites sont-elles le premier poste de dépense publique ? Comparez les postes, leur périmètre et les chiffres publiés.',
  '/analyses/satisfaction-vie-france-2010-2024/': 'Qualité de vie en France : ce que mesure la satisfaction déclarée, son évolution et les limites de cet indicateur.',
  '/analyses/ukraine-pret-europeen-90-milliards/': 'Prêt européen de 90 milliards d’euros à l’Ukraine : qui emprunte, à quoi servent les fonds et qui paie les intérêts ?',
  '/questions/age-premier-achat-residence-principale/': 'Quel âge ont les primo-accédants ? Une réponse sourcée pour distinguer premier achat, ensemble des acheteurs et évolution historique.',
  '/questions/arenh-42-euros-etranger/': 'À qui était destiné l’ARENH à 42 €/MWh ? Comprenez la différence entre accès régulé au nucléaire et exportations d’électricité.',
  '/questions/electricite-vendue-moins-chere-etranger/': 'Pourquoi le prix de l’électricité exportée diffère-t-il de votre facture ? Réponse sur le marché de gros, le réseau et les taxes.',
  '/questions/hausse-prix-gaz/': 'Le gaz a-t-il encore augmenté en France ? Une réponse sourcée qui précise la période, le prix observé et les taxes.',
  '/questions/prix-fournitures-scolaires/': 'Les fournitures scolaires ont-elles flambé ? Une réponse sourcée qui distingue évolution nominale et inflation générale.',
  '/questions/qualite-vie-france/': 'La qualité de vie baisse-t-elle en France ? Consultez la réponse et les limites des données de satisfaction déclarée.',
};
