/** Search snippets describe the page; published verdicts stay complete in its body. */
export const SEARCH_DESCRIPTIONS: Readonly<Record<string, string>> = {
  '/analyses/age-achat-residence-principale/': 'Accès à la propriété : les parcours des générations, le poids des revenus, de l’apport et des conditions de crédit dans le premier achat.',
  '/analyses/championne-du-monde-prelevements-2024/': 'En France, les impôts et cotisations atteignent 45,2 % du PIB en 2024 selon Eurostat. Quels services financent-ils et comment se répartit l’effort ?',
  '/analyses/defense-credits-votes-consommes-2025/': 'Défense en 2025 : 62,1 milliards d’euros dépensés, 62,6 milliards de crédits ouverts. Les livraisons progressent et les charges futures s’accumulent.',
  '/analyses/defense-europe-depenses-2024/': 'Dépenses de défense en Europe : 266 milliards d’euros en 2024. Suivez la hausse depuis 2020 et la répartition entre salaires, achats et investissement.',
  '/analyses/electricite-exportee-facture-francais/': 'La France exporte de l’électricité, tandis que les factures financent l’énergie, les réseaux et les taxes. Les contrats transmettent les prix dans le temps.',
  '/analyses/fournitures-scolaires-prix-1990-2025/': 'Les prix des fournitures augmentent moins vite que l’ensemble des prix depuis 1990. Listes scolaires, réemploi et promotions font varier le budget de rentrée.',
  '/analyses/groenland-accord-securite-europe/': 'Accord de sécurité au Groenland : ce qui est annoncé pour l’Arctique, ce qui doit encore être ratifié et les intérêts européens en jeu.',
  '/analyses/la-depense-publique-baisse-2024/': 'La dépense publique progresse en euros tandis que sa part du PIB recule. Prix, besoins collectifs et choix de financement expliquent ces évolutions.',
  '/analyses/prix-gaz-menages-2022-2025/': 'Le prix TTC du gaz augmente d’environ 42 % entre fin 2022 et fin 2025 pour les ménages D2. Le coût hors taxes et les prélèvements contribuent à la hausse.',
  '/analyses/retraites-premier-poste-2024/': '362,2 milliards d’euros de pensions de vieillesse en 2024. Leur financement dépend de l’emploi, des cotisations, du nombre de retraités et des droits.',
  '/analyses/satisfaction-vie-france-2010-2024/': 'La satisfaction dans la vie remonte à 7,2 sur 10 en 2024. Revenus, emploi, santé et relations sociales éclairent les écarts entre les Français.',
  '/analyses/ukraine-pret-europeen-90-milliards/': 'Prêt européen de 90 milliards d’euros à l’Ukraine : qui emprunte, à quoi servent les fonds et qui paie les intérêts ?',
  '/questions/age-premier-achat-residence-principale/': 'Quel âge ont les primo-accédants ? Une réponse sourcée pour distinguer premier achat, ensemble des acheteurs et évolution historique.',
  '/questions/arenh-42-euros-etranger/': 'À qui était destiné l’ARENH à 42 €/MWh ? Comprenez la différence entre accès régulé au nucléaire et exportations d’électricité.',
  '/questions/electricite-vendue-moins-chere-etranger/': 'Pourquoi le prix de l’électricité exportée diffère-t-il de votre facture ? Réponse sur le marché de gros, le réseau et les taxes.',
  '/questions/hausse-prix-gaz/': 'Le gaz a-t-il encore augmenté en France ? Une réponse sourcée qui précise la période, le prix observé et les taxes.',
  '/questions/prix-fournitures-scolaires/': 'Les fournitures scolaires ont-elles flambé ? Une réponse sourcée qui distingue évolution nominale et inflation générale.',
  '/questions/qualite-vie-france/': 'La qualité de vie baisse-t-elle en France ? Consultez la réponse et les limites des données de satisfaction déclarée.',
};
