export type Guide = { slug:string; title:string; summary:string; mode:'municipal'|'national'; sections:{title:string; paragraphs:string[]}[]; sources:{title:string;url:string;date?:string}[] };
export const GUIDES: Guide[] = [
 {slug:'fonctionnement-investissement',title:'Fonctionnement et investissement : deux budgets qui se répondent',summary:'Une école rénovée coûte aujourd’hui, puis modifie les dépenses des années suivantes. Comprendre les deux sections d’un budget communal.',mode:'municipal',sections:[
 {title:'Ce que finance le fonctionnement',paragraphs:['Les dépenses de fonctionnement permettent aux services de fonctionner au quotidien : personnel, achats, entretien courant et intérêts de la dette. Ce sont des dépenses régulières, distinctes de l’acquisition ou de la transformation durable d’un équipement.']},
 {title:'Ce que finance l’investissement',paragraphs:['La section d’investissement comprend notamment les équipements qui modifient le patrimoine communal et le remboursement du capital des emprunts. Il faut donc distinguer les intérêts, en fonctionnement, du capital remboursé, en investissement.']},
 {title:'Le choix ne s’arrête pas au prix du chantier',paragraphs:['Un équipement doit ensuite être exploité et entretenu. Dans Mandats, une maison des services peut créer des dépenses annuelles après sa livraison, tandis que la rénovation des écoles réduit une charge de fonctionnement. Ces coûts et gains sont des paramètres fictifs du jeu, pas des devis ni des rendements observés.']}
 ],sources:[{title:'Collectivités locales : dépenses de fonctionnement et d’investissement',url:'https://www.collectivites-locales.gouv.fr/gerer-les-finances-publiques-locales/execution-des-recettes-et-des-depenses-locales/depenses-locales/depenses-de-fonctionnement-et-depenses-dinvestissement'}]},
 {slug:'emprunt-et-epargne',title:'Dette communale : pourquoi l’épargne compte autant que l’emprunt',summary:'Emprunter finance un investissement, mais son remboursement mobilise les ressources futures de la commune.',mode:'municipal',sections:[
 {title:'L’emprunt n’est pas une recette ordinaire',paragraphs:['Pour une collectivité locale, le recours à l’emprunt finance des investissements. Le remboursement du capital doit être couvert par des ressources propres, et les intérêts constituent une dépense de fonctionnement.']},
 {title:'Lire les contraintes ensemble',paragraphs:['La dette, ses intérêts, l’épargne et les besoins d’investissement se lisent ensemble. Un remboursement supplémentaire réduit l’encours mais mobilise des moyens qui ne financeront pas un projet la même année.']},
 {title:'Comment le jeu le simplifie',paragraphs:['Le scénario municipal de Mandats calcule une épargne brute à partir des recettes, des dépenses courantes et des intérêts. Il empêche l’emprunt de combler un déficit de fonctionnement dans ses règles simplifiées ; ces règles ne remplacent pas l’ensemble du droit et de la comptabilité des collectivités. Le score n’est pas une notation financière réelle.']}
 ],sources:[{title:'Collectivités locales : principes du recours à l’emprunt',url:'https://www.collectivites-locales.gouv.fr/gerer-les-finances-publiques-locales/execution-des-recettes-et-des-depenses-locales/recettes-locales/emprunts-et-tresorerie/principes-du-recours-lemprunt'}]},
 {slug:'deficit-dette-perimetres',title:'Déficit, dette, État : trois notions à distinguer',summary:'Le déficit est un flux, la dette un encours. Et les finances de l’État ne couvrent pas toutes les administrations publiques.',mode:'national',sections:[
 {title:'Un besoin de financement sur une période',paragraphs:['Le déficit public correspond au besoin de financement des administrations publiques sur une période. Il tient compte de leurs ressources non financières, dépenses courantes, investissements non financiers et transferts en capital. Un montant en euros et un ratio au PIB répondent à deux lectures différentes.']},
 {title:'Un encours à une date donnée',paragraphs:['La dette au sens de Maastricht est une dette brute et consolidée. Son périmètre couvre l’État, les organismes divers d’administration centrale, les administrations publiques locales et les administrations de sécurité sociale. Les dettes détenues entre administrations publiques sont exclues de l’encours consolidé.']},
 {title:'Le périmètre du mode national',paragraphs:['Mandats utilise un scénario synthétique d’administrations publiques, et pas seulement le budget de l’État. Ses montants initiaux et les rendements des décisions sont fictifs. Le lien entre déficit et dette comporte dans la réalité des ajustements ; le jeu en publie une version volontairement bornée dans sa méthodologie.']}
 ],sources:[{title:'Insee : déficit public',url:'https://www.insee.fr/fr/metadonnees/definition/c1750',date:'2021-01-27'},{title:'Insee : dette au sens de Maastricht',url:'https://www.insee.fr/fr/metadonnees/definition/c1091',date:'2021-01-27'}]},
 {slug:'entretenir-ou-reparer',title:'Entretenir aujourd’hui, réparer demain : le coût du temps',summary:'Le suivi des ouvrages aide à anticiper les interventions. Le jeu rend ce compromis visible, sans inventer de coefficient universel.',mode:'municipal',sections:[
 {title:'L’entretien a une fonction préventive',paragraphs:['Pour les ponts et murs communaux, le Cerema souligne l’intérêt de la surveillance et de l’entretien courant pour préserver les ouvrages. Une insuffisance d’entretien peut conduire à des réparations importantes et justifie une programmation à long terme.']},
 {title:'Éviter une fausse règle universelle',paragraphs:['Le coût d’une intervention dépend de l’ouvrage, de son état et des travaux nécessaires. La source consacrée aux ouvrages routiers ne permet pas de chiffrer un surcoût identique pour toutes les écoles ou tous les bâtiments.']},
 {title:'Une conséquence visible dans Mandats',paragraphs:['Le patrimoine du jeu s’use avec le temps et certains reports créent des charges différées. Les délais et pénalités sont des hypothèses pédagogiques affichées. Comparez deux plans dans l’Atelier pour voir à quel moment leurs trajectoires divergent.']}
 ],sources:[{title:'Cerema : surveillance et entretien courant des ouvrages d’art routiers',url:'https://www.cerema.fr/fr/actualites/surveillance-entretien-courant-ouvrages-art-routiers-interet',date:'2024-02-26'}]}
];
