"""Derive shared region borders from the retained Natural Earth French subset."""
import collections
import json
import math
from pathlib import Path

folder = Path(__file__).resolve().parent
repo = folder.parents[2]
features = json.loads((folder / "france-admin1-naturalearth.geojson").read_text())["features"]
owners = collections.defaultdict(set)
for feature in features:
    geometry = feature["geometry"]
    polygons = geometry["coordinates"] if geometry["type"] == "MultiPolygon" else [geometry["coordinates"]]
    for polygon in polygons:
        for ring in polygon:
            for a, b in zip(ring, ring[1:]):
                a, b = (tuple(round(v, 5) for v in p) for p in (a, b))
                if a != b:
                    owners[tuple(sorted((a, b)))].add(feature["properties"]["region"])

groups = collections.defaultdict(list)
for edge, regions in owners.items():
    if len(regions) > 1:
        groups[tuple(sorted(regions))].append(edge)

def simplify(points, tolerance=.004):
    if len(points) < 3:
        return points
    a, b = points[0], points[-1]
    dx, dy = b[0] - a[0], b[1] - a[1]
    size = dx * dx + dy * dy
    def distance(p):
        t = max(0, min(1, ((p[0]-a[0])*dx + (p[1]-a[1])*dy) / size)) if size else 0
        return math.hypot(p[0]-a[0]-t*dx, p[1]-a[1]-t*dy)
    index = max(range(1, len(points)-1), key=lambda i: distance(points[i]))
    if distance(points[index]) <= tolerance:
        return [a, b]
    return simplify(points[:index+1], tolerance)[:-1] + simplify(points[index:], tolerance)

paths = []
for regions, edges in sorted(groups.items()):
    neighbors = collections.defaultdict(set)
    unused = set(edges)
    for a, b in edges:
        neighbors[a].add(b)
        neighbors[b].add(a)
    while unused:
        endpoints = sorted(p for p, adjacent in neighbors.items() if len(adjacent) != 2 and any(tuple(sorted((p,q))) in unused for q in adjacent))
        start = endpoints[0] if endpoints else min(unused)[0]
        path, point = [start], start
        while True:
            choices = sorted(q for q in neighbors[point] if tuple(sorted((point,q))) in unused)
            if not choices:
                break
            next_point = choices[0]
            unused.remove(tuple(sorted((point,next_point))))
            path.append(next_point)
            point = next_point
            if point == start or len(neighbors[point]) != 2:
                break
        if len(path) > 1:
            paths.append({"regions": regions, "points": simplify(path)})

header = "// Natural Earth 10m admin1, public domain. Shared metropolitan region borders.\n// Generated by tools/mandats-assets/geography/build-region-lines.py.\n"
target = repo / "site/src/mandats/map-region-geography.ts"
target.write_text(header + "export const MAP_REGION_LINES: readonly (readonly (readonly [number, number])[])[] = " + json.dumps([p["points"] for p in paths], separators=(",", ":")) + ";\n")
(folder / "region-lines.json").write_text(json.dumps(paths, ensure_ascii=False, indent=2) + "\n")
print(json.dumps({"regions":len({f["properties"]["region"] for f in features}),"shared_edges":sum(len(g) for g in groups.values()),"paths":len(paths),"vertices":sum(len(p["points"]) for p in paths)}))
