/**
 * La pile de mesures du simulateur en tunnel.
 *
 * Chaque mesure est un choix politique réel du débat français, avec son effet
 * budgétaire annuel en MILLIONS D'EUROS — un ordre de grandeur tiré du débat
 * public (annexes des lois de finances, rapports parlementaires et de la Cour
 * des comptes, études d'impact, chiffrages d'instituts), jamais un chiffre
 * publié au sens du reste du site. Le tunnel l'écrit sous chaque carte et au
 * pied de la page : ces montants situent, ils ne certifient pas. Les mesures
 * au chiffrage contesté portent leur réserve dans `precision`, affichée telle
 * quelle — la taxe Zucman et les prestations réservées se lisent avec la même
 * règle, et c'est le point : le jeu ne choisit pas, il chiffre.
 *
 * `reactions` est le modèle de jeu des quatre soutiens : des RÈGLES ÉCRITES,
 * réglables, jamais des données. `bloqueePar` porte les clés des contrats de
 * `mission.ts` qui retirent la mesure du tunnel — signer « sans toucher à
 * l'école ni à la santé » fait disparaître les cartes qu'il couvre, dans les
 * deux sens : on ne peut ni les couper, ni les augmenter.
 *
 * Ce fichier est GÉNÉRÉ depuis les catalogues validés par le propriétaire :
 * « La pile de mesures » (78 mesures) puis « Les mesures qui manquent »
 * (18 ajouts sur les retraites, l'immigration, la sécurité, le chômage et le
 * pouvoir d'achat), tous deux du 22 août 2026. L'ordre est celui de la
 * validation, chapitre par chapitre, et le tunnel le rejoue tel quel.
 */

export type Soutien = "opinion" | "entreprises" | "territoires" | "marches";

export type Mesure = {
  id: string;
  /** Le chapitre affiché dans le rail « tous les postes y passent ». */
  chapitre: string;
  titre: string;
  /** M€ par an. Positif : la mesure trouve de l'argent. Négatif : elle en
   *  coûte — et c'est aussi un choix politique, le tunnel le dit. */
  effet: number;
  /** La réserve qui accompagne le montant (« fourchette 2 000–16 000 »,
   *  « arithmétique brute », « une seule fois ») — affichée avec lui. */
  precision?: string;
  /** Ce que la mesure fait et d'où sort le chiffrage, en une ou deux phrases. */
  detail: string;
  /** Le modèle de jeu : ce que chaque tampon ADOPTÉ fait aux soutiens. */
  reactions: Partial<Record<Soutien, number>>;
  /** Ce que le REJET fait aux soutiens — le second prix, affiché sur la
   *  carte. Déclaré pour les totems seulement : rejeter la mesure préférée
   *  d'un camp le fâche, rejeter une mesure douloureuse soulage. C'est ce
   *  qui fait le dilemme : aucun tampon n'est neutre sur ces cartes. */
  rejet?: Partial<Record<Soutien, number>>;
  /** Les contrats (mission.ts) qui retirent cette mesure du tunnel. */
  bloqueePar?: string[];
  /** Les mesures incompatibles : adopter celle-ci les écarte du conseil —
   *  on ne vote pas deux barèmes de l'IR, ni 65 ans ET 62 ans. La relation
   *  est symétrisée à l'exécution : la déclarer d'un côté suffit. */
  exclut?: string[];
};

export const MESURES: Mesure[] = [
  {
    id: "flat-tax-a-20-des-le-premier",
    exclut: ["flat-tax-a-20-avec-abattement-protegeant", "tranche-a-50-au-dela-de-250", "geler-le-bareme-de-l-impot-sur", "soumettre-les-revenus-du-capital-au-bareme"],
    chapitre: "Impôts",
    titre: "Flat tax à 20 % dès le premier euro : le barème disparaît, tout le monde paie",
    effet: 150000,
    precision: "arithmétique brute",
    detail: "Arithmétique sur les revenus déclarés : 20 % de l'assiette rapportent bien plus que les ~90 000 M€ nets de l'IR actuel. Mais près de 6 foyers sur 10 ne paient rien aujourd'hui : pour eux ce n'est pas une économie, c'est 0 → 20 %. Personne ne la propose telle quelle.",
    reactions: { opinion: -20, entreprises: 4, marches: 6 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "flat-tax-a-20-avec-abattement-protegeant",
    exclut: ["tranche-a-50-au-dela-de-250", "geler-le-bareme-de-l-impot-sur", "soumettre-les-revenus-du-capital-au-bareme"],
    chapitre: "Impôts",
    titre: "Flat tax à 20 % avec abattement protégeant les revenus modestes",
    effet: -12000,
    precision: "selon abattement",
    detail: "La variante réellement proposée : les non-imposables restent à zéro, les tranches hautes paient moins, et c'est précisément pour ça qu'il manque de l'ordre de 12 000 M€. Les deux effets qu'on vous promet ensemble, « ça épargne les modestes » et « ça rapporte », ne coexistent pas.",
    reactions: { opinion: -6, entreprises: 5, marches: -3 },
  },
  {
    id: "tranche-a-50-au-dela-de-250",
    chapitre: "Impôts",
    titre: "Tranche à 50 % au-delà de 250 000 € de revenus",
    effet: 1200,
    detail: "Amendements PLF chiffrés par la commission des finances.",
    reactions: { opinion: 3, entreprises: -3 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "retablir-un-impot-sur-la-fortune-financiere",
    chapitre: "Impôts",
    titre: "Rétablir un impôt sur la fortune financière",
    effet: 4500,
    detail: "Chiffrages parlementaires, selon l'assiette retenue.",
    reactions: { opinion: 4, entreprises: -6, marches: -2 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "impot-plancher-de-2-sur-les-patrimoines",
    chapitre: "Impôts",
    titre: "Impôt plancher de 2 % sur les patrimoines au-delà de 100 M€ (« taxe Zucman »)",
    effet: 15000,
    precision: "très contesté",
    detail: "Chiffrage de l'auteur ; les contre-chiffrages descendent sous 5 000.",
    reactions: { opinion: 5, entreprises: -7, marches: -3 },
    rejet: { opinion: -3 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "soumettre-les-revenus-du-capital-au-bareme",
    chapitre: "Impôts",
    titre: "Soumettre les revenus du capital au barème (fin du PFU)",
    effet: 1000,
    detail: "Évaluations du PLF, comportements de versement compris.",
    reactions: { entreprises: -4 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "exonerer-de-droits-de-succession-jusqu-a",
    chapitre: "Impôts",
    titre: "Exonérer de droits de succession jusqu'à 300 000 € par enfant",
    effet: -2500,
    detail: "Chiffrages parlementaires des propositions déposées.",
    reactions: { opinion: 4 },
  },
  {
    id: "porter-le-taux-normal-de-tva-a",
    chapitre: "Impôts",
    titre: "Porter le taux normal de TVA à 21 %",
    effet: 9800,
    detail: "Rendement d'un point de TVA, évaluations des voies et moyens.",
    reactions: { opinion: -8, marches: 3 },
    rejet: { opinion: 3, marches: -3 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "tva-a-0-sur-un-panier-de",
    chapitre: "Impôts",
    titre: "TVA à 0 % sur un panier de produits de première nécessité",
    effet: -3000,
    detail: "Chiffrages des propositions de loi ; l'effet prix réel est débattu.",
    reactions: { opinion: 5, marches: -1 },
    rejet: { opinion: -2 },
  },
  {
    id: "geler-le-bareme-de-l-impot-sur",
    chapitre: "Impôts",
    titre: "Geler le barème de l'impôt sur le revenu (non-indexation)",
    effet: 1700,
    detail: "Évaluations des voies et moyens : la hausse d'impôt que personne ne vote : l'inflation fait monter tout le monde d'une tranche.",
    reactions: { opinion: -4, marches: 1 },
    rejet: { opinion: 2, marches: -1 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "doubler-la-taxe-sur-les-rachats-d",
    chapitre: "Impôts",
    titre: "Doubler la taxe sur les rachats d'actions",
    effet: 400,
    detail: "Rendement de la taxe votée en 2025, doublé.",
    reactions: { entreprises: -2 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "raboter-l-avantage-successoral-de-l-assurance",
    chapitre: "Impôts",
    titre: "Raboter l'avantage successoral de l'assurance-vie",
    effet: 1000,
    detail: "Dépense fiscale recensée au tome 2 des voies et moyens.",
    reactions: { opinion: -3 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "retablir-une-redevance-audiovisuelle",
    chapitre: "Impôts",
    titre: "Rétablir une redevance audiovisuelle",
    effet: 3000,
    detail: "Rendement de l'ancienne contribution, revalorisé.",
    reactions: { opinion: -4 },
    rejet: { opinion: 2 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "tva-a-5-5-sur-l-electricite",
    chapitre: "Impôts",
    titre: "TVA à 5,5 % sur l'électricité, le gaz et les carburants",
    effet: -12000,
    precision: "très contesté",
    detail: "Chiffrage de ses promoteurs autour de 12 000 ; les contre-chiffrages montent à 17 000, et le droit européen interdit le taux réduit sur les carburants en l'état. La mesure la plus populaire des sondages, avec sa fourchette et sa condition juridique.",
    reactions: { opinion: 8, marches: -4 },
    rejet: { opinion: -5 },
  },
  {
    id: "fiscaliser-les-heures-supplementaires-comme-le",
    exclut: ["flat-tax-a-20-des-le-premier", "flat-tax-a-20-avec-abattement-protegeant"],
    chapitre: "Impôts",
    titre: "Fiscaliser les heures supplémentaires comme le reste du salaire",
    effet: 1700,
    detail: "Dépense fiscale au tome des voies et moyens.",
    reactions: { opinion: -6 },
    rejet: { opinion: 2 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "elargir-la-taxe-sur-les-transactions",
    chapitre: "Impôts",
    titre: "Élargir la taxe sur les transactions financières",
    effet: 2000,
    precision: "fourchette 2 000 à 4 300",
    detail: "Rapports parlementaires sur l'extension aux opérations intrajournalières.",
    reactions: { entreprises: -2, marches: -3 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "reconduire-la-surtaxe-des-grandes-entreprises",
    chapitre: "Entreprises et niches",
    titre: "Reconduire la surtaxe des grandes entreprises",
    effet: 8000,
    detail: "Rendement voté en LFI 2025.",
    reactions: { entreprises: -8, opinion: 3 },
    rejet: { opinion: -2, entreprises: 3 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "supprimer-les-allegements-de-cotisations-entre-2",
    chapitre: "Entreprises et niches",
    titre: "Supprimer les allègements de cotisations entre 2,5 et 3,5 SMIC",
    effet: 2000,
    detail: "Rapports sur les allègements généraux (LFSS).",
    reactions: { entreprises: -5 },
    rejet: { entreprises: 2 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "raboter-de-5-les-subventions-directes-aux",
    chapitre: "Entreprises et niches",
    titre: "Raboter de 5 % les subventions directes aux entreprises",
    effet: 1500,
    detail: "Rapport sénatorial sur les aides publiques aux entreprises.",
    reactions: { entreprises: -4, territoires: -1 },
  },
  {
    id: "raboter-le-credit-d-impot-recherche-de",
    chapitre: "Entreprises et niches",
    titre: "Raboter le crédit d'impôt recherche de 10 %, PME épargnées",
    effet: 700,
    detail: "Dépense fiscale recensée au tome 2 des voies et moyens.",
    reactions: { entreprises: -4 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "supprimer-l-avantage-fiscal-du-gazole-non",
    chapitre: "Entreprises et niches",
    titre: "Supprimer l'avantage fiscal du gazole non routier",
    effet: 1500,
    detail: "Dépense fiscale recensée ; report déjà voté puis défait.",
    reactions: { entreprises: -3, territoires: -3 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "doubler-la-taxe-sur-les-services-numeriques",
    chapitre: "Entreprises et niches",
    titre: "Doubler la taxe sur les services numériques",
    effet: 700,
    detail: "Rendement constaté de la taxe actuelle.",
    reactions: { entreprises: -2, marches: -1 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "achever-la-suppression-de-la-cvae",
    chapitre: "Entreprises et niches",
    titre: "Achever la suppression de la CVAE",
    effet: -1100,
    detail: "Trajectoire inscrite puis gelée en loi de finances.",
    reactions: { entreprises: 4, territoires: -2 },
    rejet: { entreprises: -2 },
  },
  {
    id: "repousser-l-age-legal-a-65-ans",
    exclut: ["revenir-a-62-ans"],
    chapitre: "Retraites",
    titre: "Repousser l'âge légal à 65 ans",
    effet: 8500,
    precision: "en croisière",
    detail: "Ordres de grandeur du COR ; presque rien les premières années.",
    reactions: { opinion: -12, marches: 5 },
    rejet: { opinion: 3, marches: -3 },
  },
  {
    id: "revenir-a-62-ans",
    chapitre: "Retraites",
    titre: "Revenir à 62 ans",
    effet: -13000,
    precision: "à terme",
    detail: "Chiffrages COR de l'abrogation, horizon 2030.",
    reactions: { opinion: 8, marches: -6 },
    rejet: { opinion: -3, marches: 2 },
  },
  {
    id: "desindexer-les-pensions-d-un-point",
    chapitre: "Retraites",
    titre: "Désindexer les pensions d'un point",
    effet: 3600,
    detail: "Un point sur 362 178 M€ de pensions (2024, publié).",
    reactions: { opinion: -9, marches: 3 },
    rejet: { opinion: 3, marches: -2 },
    bloqueePar: ["sans-prestation"],
  },
  {
    id: "aligner-la-csg-des-retraites-aises-sur",
    chapitre: "Retraites",
    titre: "Aligner la CSG des retraités aisés sur celle des actifs",
    effet: 1800,
    detail: "Évaluations LFSS des assiettes CSG.",
    reactions: { opinion: -5 },
  },
  {
    id: "eteindre-les-derniers-regimes-speciaux-stock",
    chapitre: "Retraites",
    titre: "Éteindre les derniers régimes spéciaux (stock)",
    effet: 1000,
    precision: "montée lente",
    detail: "Rapports parlementaires ; l'extinction du stock prend vingt ans.",
    reactions: { opinion: -3 },
  },
  {
    id: "porter-le-minimum-vieillesse-a-1-200",
    chapitre: "Retraites",
    titre: "Porter le minimum vieillesse à 1 200 €",
    effet: -2000,
    detail: "Chiffrages des propositions de loi.",
    reactions: { opinion: 5 },
    rejet: { opinion: -3 },
  },
  {
    id: "suspendre-la-reforme-des-retraites-jusqu",
    exclut: ["repousser-l-age-legal-a-65-ans", "revenir-a-62-ans"],
    chapitre: "Retraites",
    titre: "Suspendre la réforme des retraites jusqu'en 2028 (l'âge gelé à 62 ans et 9 mois)",
    effet: -1400,
    precision: "monte chaque année",
    detail: "Chiffrage du PLFSS : environ 100 M€ la première année, 1 400 la deuxième, davantage ensuite. La position médiane réellement votée.",
    reactions: { opinion: 4, entreprises: -2, marches: -3 },
    rejet: { opinion: -2, marches: 2 },
  },
  {
    id: "remplacer-l-abattement-des-retraites-par",
    exclut: ["flat-tax-a-20-des-le-premier", "flat-tax-a-20-avec-abattement-protegeant"],
    chapitre: "Retraites",
    titre: "Remplacer l'abattement de 10 % des retraités par un forfait de 2 000 €",
    effet: 1200,
    detail: "Évaluation du PLF 2026. Les petites pensions y gagnent, les grosses y perdent.",
    reactions: { opinion: -3 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "ouvrir-un-etage-de-capitalisation-collective",
    chapitre: "Retraites",
    titre: "Ouvrir un étage de retraite par capitalisation collective",
    effet: -500,
    precision: "coûts de transition",
    detail: "Position patronale au conclave des retraites. Cotiser pour soi, c'est cesser de financer les pensions courantes : la transition coûte avant de rapporter.",
    reactions: { opinion: -4, entreprises: 4, marches: 4 },
  },
  {
    id: "doubler-les-franchises-medicales",
    chapitre: "Santé",
    titre: "Doubler les franchises médicales",
    effet: 800,
    detail: "Évaluations LFSS.",
    reactions: { opinion: -7 },
    rejet: { opinion: 2 },
    bloqueePar: ["ecole-sante", "sans-prestation"],
  },
  {
    id: "creer-5-000-postes-de-soignants",
    chapitre: "Santé",
    titre: "Créer 5 000 postes de soignants",
    effet: -350,
    detail: "Coût salarial moyen, année pleine.",
    reactions: { opinion: 6 },
    rejet: { opinion: -4 },
    bloqueePar: ["ecole-sante"],
  },
  {
    id: "imposer-generiques-et-biosimilaires-en-premiere-intention",
    chapitre: "Santé",
    titre: "Imposer génériques et biosimilaires en première intention",
    effet: 1000,
    detail: "Rapports de l'assurance maladie (« charges et produits »).",
    reactions: { entreprises: -2 },
    bloqueePar: ["ecole-sante"],
  },
  {
    id: "derembourser-les-cures-thermales",
    chapitre: "Santé",
    titre: "Dérembourser les cures thermales",
    effet: 250,
    detail: "Dépense remboursée publiée.",
    reactions: { opinion: -2, territoires: -3 },
    bloqueePar: ["ecole-sante", "sans-prestation"],
  },
  {
    id: "renforcer-le-controle-des-arrets-de-travail",
    chapitre: "Santé",
    titre: "Renforcer le contrôle des arrêts de travail",
    effet: 300,
    detail: "Plans d'économies LFSS successifs.",
    reactions: { opinion: -2 },
    bloqueePar: ["ecole-sante"],
  },
  {
    id: "plafonner-les-indemnites-journalieres-les-plus-longues",
    chapitre: "Santé",
    titre: "Plafonner les indemnités journalières les plus longues",
    effet: 600,
    detail: "Mesures chiffrées dans les LFSS récentes.",
    reactions: { opinion: -3 },
    bloqueePar: ["ecole-sante", "sans-prestation"],
  },
  {
    id: "fusionner-agences-sanitaires-et-echelons-des-ars",
    chapitre: "Santé",
    titre: "Fusionner agences sanitaires et échelons des ARS",
    effet: 200,
    detail: "Revues de dépenses publiées.",
    reactions: { territoires: -1 },
    bloqueePar: ["ecole-sante"],
  },
  {
    id: "loi-grand-age-50-000-recrutements",
    chapitre: "Santé",
    titre: "Loi grand âge : 50 000 recrutements en Ehpad et à domicile",
    effet: -2500,
    detail: "Rapports publics sur les besoins en personnel du grand âge.",
    reactions: { opinion: 4 },
    rejet: { opinion: -4 },
    bloqueePar: ["ecole-sante"],
  },
  {
    id: "fiscalite-nutritionnelle-au-niveau-recommande",
    chapitre: "Santé",
    titre: "Fiscalité nutritionnelle au niveau recommandé (sucre, alcool)",
    effet: 1500,
    detail: "Recommandations chiffrées de la Cour des comptes sur les taxes comportementales.",
    reactions: { opinion: -2, entreprises: -2 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "recruter-10-000-policiers-et-gendarmes",
    chapitre: "Sécurité et immigration",
    titre: "Recruter 10 000 policiers et gendarmes",
    effet: -600,
    detail: "Coût moyen chargé ; la mission Sécurités porte 25 215 M€ votés.",
    reactions: { opinion: 5 },
    rejet: { opinion: -3 },
  },
  {
    id: "construire-15-000-places-de-prison-supplementaires",
    chapitre: "Sécurité et immigration",
    titre: "Construire 15 000 places de prison supplémentaires",
    effet: -500,
    precision: "sur 10 ans",
    detail: "Coût par place des programmes immobiliers pénitentiaires.",
    reactions: { opinion: 3 },
    rejet: { opinion: -2 },
  },
  {
    id: "recruter-3-000-magistrats-et-greffiers",
    chapitre: "Sécurité et immigration",
    titre: "Recruter 3 000 magistrats et greffiers",
    effet: -300,
    detail: "Trajectoire de la loi de programmation justice.",
    reactions: { opinion: 2 },
  },
  {
    id: "supprimer-l-aide-medicale-d-etat",
    chapitre: "Sécurité et immigration",
    titre: "Supprimer l'aide médicale d'État",
    effet: 1200,
    detail: "Crédits votés de l'AME ; une partie se reporte sur les urgences.",
    reactions: { opinion: -3 },
  },
  {
    id: "reduire-les-delais-de-traitement-de-l",
    chapitre: "Sécurité et immigration",
    titre: "Réduire les délais de traitement de l'asile",
    effet: 300,
    precision: "net",
    detail: "Moyens OFPRA en plus, hébergement d'urgence en moins. Rapports budgétaires.",
    reactions: { territoires: 1 },
  },
  {
    id: "reserver-les-prestations-non-contributives-aux-nationaux",
    chapitre: "Sécurité et immigration",
    titre: "Réserver les prestations non contributives aux nationaux et aux étrangers présents depuis 5 ans",
    effet: 9000,
    precision: "fourchette 2 000–16 000",
    detail: "Fourchette du débat : ~16 000 revendiqués par ses promoteurs, 2 000 à 9 000 dans les contre-chiffrages une fois retiré ce que la Constitution et les traités interdisent en l'état. Retenu : le milieu, affiché avec sa fourchette et sa condition juridique : l'essentiel suppose une révision constitutionnelle.",
    reactions: { opinion: 3, entreprises: -2, territoires: -1 },
    rejet: { marches: -2 },
    bloqueePar: ["sans-prestation"],
  },
  {
    id: "etendre-les-centres-de-retention-administrative",
    chapitre: "Sécurité et immigration",
    titre: "Étendre les centres de rétention administrative",
    effet: -250,
    detail: "Coût par place programmé (LOPMI).",
    reactions: { opinion: 2 },
  },
  {
    id: "doubler-les-moyens-de-l-integration-francais",
    chapitre: "Sécurité et immigration",
    titre: "Doubler les moyens de l'intégration (français, emploi)",
    effet: -900,
    detail: "Mission Immigration, asile et intégration : ~2 300 M€.",
    reactions: { opinion: -2, territoires: 2 },
  },
  {
    id: "supprimer-l-allocation-pour-demandeurs-d",
    chapitre: "Sécurité et immigration",
    titre: "Supprimer l'allocation pour demandeurs d'asile",
    effet: 350,
    detail: "Budget voté de l'ADA. Petite ligne, gros totem : la carte donne l'échelle.",
    reactions: { opinion: 1, territoires: -1 },
    bloqueePar: ["sans-prestation"],
  },
  {
    id: "doubler-l-execution-des-eloignements-oqtf",
    chapitre: "Sécurité et immigration",
    titre: "Doubler l'exécution des éloignements (OQTF)",
    effet: -400,
    detail: "Coût unitaire d'un éloignement établi par la Cour des comptes, multiplié par le volume visé, rétention et laissez-passer compris. Éloigner coûte avant d'économiser.",
    reactions: { opinion: 2 },
    rejet: { opinion: -2 },
  },
  {
    id: "doubler-les-moyens-du-renseignement-interieur",
    chapitre: "Sécurité et immigration",
    titre: "Doubler les moyens du renseignement intérieur",
    effet: -300,
    detail: "Budgets votés des services.",
    reactions: { opinion: 1 },
  },
  {
    id: "legaliser-et-taxer-le-cannabis",
    chapitre: "Sécurité et immigration",
    titre: "Légaliser et taxer le cannabis",
    effet: 2800,
    precision: "fourchette 2 000 à 3 200",
    detail: "Travaux du Conseil d'analyse économique : recettes fiscales d'un marché légal, plus les économies de répression.",
    reactions: { opinion: -3, entreprises: 1 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "porter-l-effort-de-defense-vers-3",
    exclut: ["etaler-la-marche-2026-de-la-programmation"],
    chapitre: "Défense et international",
    titre: "Porter l'effort de défense vers 3 % du PIB",
    effet: -6000,
    precision: "1re marche",
    detail: "Écart entre la LPM votée (60 004 M€ en 2025) et la cible.",
    reactions: { entreprises: 3, marches: -2 },
  },
  {
    id: "etaler-la-marche-2026-de-la-programmation",
    chapitre: "Défense et international",
    titre: "Étaler la marche 2026 de la programmation militaire",
    effet: 3300,
    detail: "Marche annuelle inscrite en LPM.",
    reactions: { opinion: -3 },
  },
  {
    id: "doubler-la-reserve-operationnelle",
    chapitre: "Défense et international",
    titre: "Doubler la réserve opérationnelle",
    effet: -400,
    detail: "Cible et coût inscrits dans la LPM.",
    reactions: { opinion: 2 },
  },
  {
    id: "reduire-l-aide-publique-au-developpement-de",
    chapitre: "Défense et international",
    titre: "Réduire l'aide publique au développement de moitié",
    effet: 2900,
    detail: "Mission APD : ~5 900 M€ votés.",
    reactions: { opinion: -2 },
  },
  {
    id: "service-militaire-volontaire-de-50-000",
    exclut: ["generaliser-le-service-national-universel"],
    chapitre: "Défense et international",
    titre: "Service militaire volontaire de 50 000 jeunes",
    effet: -2000,
    precision: "en régime",
    detail: "Annonce de 2025 : environ 800 M€ la première année, 2 000 en régime de croisière. Remplace le SNU.",
    reactions: { opinion: 3 },
  },
  {
    id: "taxer-le-kerosene-des-vols-interieurs-et",
    chapitre: "Écologie et transports",
    titre: "Taxer le kérosène des vols intérieurs et intra-européens",
    effet: 1000,
    detail: "Rapports sur les exonérations du transport aérien ; dépend des traités.",
    reactions: { entreprises: -3, territoires: -2 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "retablir-une-trajectoire-carbone-recettes-redistribuees",
    chapitre: "Écologie et transports",
    titre: "Rétablir une trajectoire carbone, recettes redistribuées",
    effet: 4000,
    precision: "brut",
    detail: "Trajectoire abandonnée en 2018 ; la redistribution en rend une partie.",
    reactions: { opinion: -8, territoires: -4 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "doubler-maprimerenov",
    chapitre: "Écologie et transports",
    titre: "Doubler MaPrimeRénov'",
    effet: -2300,
    detail: "Crédits votés du programme.",
    reactions: { opinion: 3, entreprises: 2 },
  },
  {
    id: "plan-ferroviaire-3-000-m-de-plus",
    chapitre: "Écologie et transports",
    titre: "Plan ferroviaire : 3 000 M€ de plus par an",
    effet: -3000,
    detail: "Scénarios d'investissement du COI et de SNCF Réseau.",
    reactions: { territoires: 5, marches: -1 },
  },
  {
    id: "supprimer-le-bonus-automobile-electrique",
    exclut: ["relancer-le-leasing-social-de-vehicules-electriques"],
    chapitre: "Écologie et transports",
    titre: "Supprimer le bonus automobile électrique",
    effet: 1500,
    detail: "Crédits votés du bonus et du leasing social.",
    reactions: { opinion: -2, entreprises: -2 },
  },
  {
    id: "relancer-le-leasing-social-de-vehicules-electriques",
    chapitre: "Écologie et transports",
    titre: "Relancer le leasing social de véhicules électriques",
    effet: -650,
    detail: "Coût constaté de la première édition.",
    reactions: { opinion: 3 },
  },
  {
    id: "engager-six-epr2-part-annuelle-de-l",
    chapitre: "Écologie et transports",
    titre: "Engager six EPR2 (part annuelle de l'État)",
    effet: -2000,
    precision: "montée en charge",
    detail: "Coût programme publié (~52 000 M€), part publique en discussion.",
    reactions: { entreprises: 3, marches: -1 },
  },
  {
    id: "renforcer-la-taxe-sur-les-billets-d",
    chapitre: "Écologie et transports",
    titre: "Renforcer la taxe sur les billets d'avion",
    effet: 1000,
    detail: "Rendement voté en LFI 2025.",
    reactions: { entreprises: -2 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "supprimer-les-soutiens-fiscaux-aux-agrocarburants",
    chapitre: "Écologie et transports",
    titre: "Supprimer les soutiens fiscaux aux agrocarburants",
    effet: 700,
    detail: "Dépenses fiscales recensées.",
    reactions: { territoires: -2, entreprises: -1 },
    bloqueePar: ["sans-impot"],
  },
  {
    id: "doubler-le-fonds-velo-et-mobilites-actives",
    chapitre: "Écologie et transports",
    titre: "Doubler le fonds vélo et mobilités actives",
    effet: -250,
    detail: "Crédits votés du fonds actuel.",
    reactions: { opinion: 1, territoires: 1 },
  },
  {
    id: "doubler-le-soutien-a-l-agriculture-bio",
    chapitre: "Écologie et transports",
    titre: "Doubler le soutien à l'agriculture bio et aux haies",
    effet: -300,
    detail: "Crédits votés des programmes concernés.",
    reactions: { territoires: 2 },
  },
  {
    id: "revaloriser-les-enseignants-de-5",
    chapitre: "École et culture",
    titre: "Revaloriser les enseignants de 5 %",
    effet: -3000,
    detail: "5 % de la masse salariale de l'enseignement scolaire (88 817 M€ votés).",
    reactions: { opinion: 4 },
    rejet: { opinion: -4 },
    bloqueePar: ["ecole-sante"],
  },
  {
    id: "generaliser-le-service-national-universel",
    chapitre: "École et culture",
    titre: "Généraliser le service national universel",
    effet: -2000,
    detail: "Chiffrages de la généralisation (rapports parlementaires).",
    reactions: { opinion: -2 },
  },
  {
    id: "cantine-a-1-generalisee-dans-les-communes",
    chapitre: "École et culture",
    titre: "Cantine à 1 € généralisée dans les communes pauvres",
    effet: -800,
    detail: "Extension du dispositif existant, chiffrée par l'État.",
    reactions: { opinion: 4, territoires: 2 },
    rejet: { opinion: -2 },
  },
  {
    id: "etendre-le-dedoublement-des-classes-au-cm1",
    chapitre: "École et culture",
    titre: "Étendre le dédoublement des classes au CM1-CM2 en éducation prioritaire",
    effet: -400,
    detail: "Coût par classe dédoublée, constaté sur les vagues précédentes.",
    reactions: { opinion: 3 },
    bloqueePar: ["ecole-sante"],
  },
  {
    id: "recentrer-le-pass-culture",
    chapitre: "École et culture",
    titre: "Recentrer le pass Culture",
    effet: 100,
    detail: "Réforme déjà engagée, économie constatée.",
    reactions: { opinion: -1 },
  },
  {
    id: "privatiser-l-audiovisuel-public",
    chapitre: "École et culture",
    titre: "Privatiser l'audiovisuel public",
    effet: 4000,
    detail: "Financement public actuel de l'audiovisuel.",
    reactions: { opinion: -5, entreprises: 2 },
  },
  {
    id: "doubler-les-bourses-etudiantes-sur-criteres",
    chapitre: "École et culture",
    titre: "Doubler les bourses étudiantes sur critères sociaux",
    effet: -2400,
    detail: "Budget voté des bourses, doublé.",
    reactions: { opinion: 3 },
    rejet: { opinion: -2 },
    bloqueePar: ["ecole-sante"],
  },
  {
    id: "financer-100-000-logements-sociaux-de-plus",
    chapitre: "Logement",
    titre: "Financer 100 000 logements sociaux de plus par an",
    effet: -1500,
    detail: "Aides à la pierre et TVA réduite, coûts constatés par logement.",
    reactions: { opinion: 3, territoires: 3 },
    rejet: { opinion: -2 },
  },
  {
    id: "retablir-un-dispositif-d-investissement-locatif-recentre",
    chapitre: "Logement",
    titre: "Rétablir un dispositif d'investissement locatif recentré",
    effet: -1000,
    detail: "Dépense fiscale du dispositif éteint, recentrée.",
    reactions: { entreprises: 2 },
  },
  {
    id: "revaloriser-les-apl-de-5",
    chapitre: "Logement",
    titre: "Revaloriser les APL de 5 %",
    effet: -700,
    detail: "5 % des aides personnalisées au logement versées.",
    reactions: { opinion: 3 },
  },
  {
    id: "durcir-l-assurance-chomage-degressivite-duree",
    exclut: ["revenir-sur-la-reforme-du-chomage-de"],
    chapitre: "Travail et solidarité",
    titre: "Durcir l'assurance chômage (dégressivité, durée)",
    effet: 2200,
    detail: "Études d'impact des réformes successives (Unédic).",
    reactions: { opinion: -6, marches: 2 },
    rejet: { opinion: 2, marches: -2 },
    bloqueePar: ["sans-prestation"],
  },
  {
    id: "revenir-sur-la-reforme-du-chomage-de",
    chapitre: "Travail et solidarité",
    titre: "Revenir sur la réforme du chômage de 2023",
    effet: -2500,
    detail: "Mêmes études, en sens inverse.",
    reactions: { opinion: 4, marches: -2 },
    rejet: { opinion: -2, marches: 2 },
  },
  {
    id: "verser-le-rsa-automatiquement-fin-du-non",
    chapitre: "Travail et solidarité",
    titre: "Verser le RSA automatiquement (fin du non-recours)",
    effet: -2600,
    detail: "Taux de non-recours mesuré (~un tiers) × montant moyen.",
    reactions: { opinion: 5 },
  },
  {
    id: "allocations-familiales-des-le-premier-enfant",
    chapitre: "Travail et solidarité",
    titre: "Allocations familiales dès le premier enfant",
    effet: -1800,
    detail: "Chiffrages CNAF des propositions.",
    reactions: { opinion: 3 },
    rejet: { opinion: -2 },
  },
  {
    id: "conditionner-le-rsa-a-15-heures",
    exclut: ["verser-le-rsa-automatiquement-fin-du-non"],
    chapitre: "Travail et solidarité",
    titre: "Conditionner le RSA à 15 heures d'activité par semaine",
    effet: -300,
    precision: "coût d'accompagnement",
    detail: "La généralisation de 2025 coûte d'abord son accompagnement (France Travail, départements) ; les économies revendiquées ne sont documentées nulle part. La carte affiche le coût, pas la promesse.",
    reactions: { opinion: 3, entreprises: 2, territoires: -2 },
    bloqueePar: ["sans-prestation"],
  },
  {
    id: "porter-le-rsa-au-seuil-de",
    chapitre: "Travail et solidarité",
    titre: "Porter le RSA au seuil de pauvreté (environ +30 %)",
    effet: -3500,
    detail: "Chiffrages associatifs et parlementaires de la revalorisation, non-recours constant.",
    reactions: { opinion: 2, entreprises: -2, marches: -2 },
  },
  {
    id: "conge-de-naissance-mieux-remunere",
    chapitre: "Travail et solidarité",
    titre: "Congé de naissance mieux rémunéré, en remplacement du congé parental",
    effet: -1300,
    detail: "Évaluations de la réforme annoncée en PLFSS.",
    reactions: { opinion: 3, entreprises: -1 },
    rejet: { opinion: -2 },
  },
  {
    id: "ouvrir-200-000-places-de-creche",
    chapitre: "Travail et solidarité",
    titre: "Ouvrir 200 000 places de crèche (service public de la petite enfance)",
    effet: -1500,
    detail: "Chiffrages du comité de filière petite enfance, en rythme annuel.",
    reactions: { opinion: 3, entreprises: 2 },
    rejet: { opinion: -2, entreprises: -1 },
    bloqueePar: ["sans-collectivites"],
  },
  {
    id: "geler-le-point-d-indice-en-2026",
    chapitre: "État et institutions",
    titre: "Geler le point d'indice en 2026",
    effet: 3400,
    detail: "Un point sur 370 016 M€ de rémunérations publiques (2025).",
    reactions: { opinion: -6, territoires: -2 },
    rejet: { opinion: 2, marches: -1 },
  },
  {
    id: "deux-jours-de-carence-dans-la-fonction",
    chapitre: "État et institutions",
    titre: "Deux jours de carence dans la fonction publique",
    effet: 1000,
    detail: "Études d'impact des jours de carence.",
    reactions: { opinion: -4 },
    rejet: { opinion: 1 },
  },
  {
    id: "ne-pas-remplacer-un-depart-administratif-sur",
    chapitre: "État et institutions",
    titre: "Ne pas remplacer un départ administratif sur trois",
    effet: 1500,
    precision: "montée",
    detail: "Masse salariale des fonctions support ; hors enseignants et soignants.",
    reactions: { opinion: -3, territoires: -2 },
  },
  {
    id: "fermer-un-tiers-des-agences-et-operateurs",
    chapitre: "État et institutions",
    titre: "Fermer un tiers des agences et opérateurs",
    effet: 1800,
    detail: "Revues parlementaires des opérateurs, hors coûts de transition.",
    reactions: { territoires: -4 },
  },
  {
    id: "diviser-par-deux-le-nombre-de-parlementaires",
    chapitre: "État et institutions",
    titre: "Diviser par deux le nombre de parlementaires",
    effet: 150,
    detail: "Budgets des assemblées ; symbolique face aux masses, et le jeu l'affichera tel quel.",
    reactions: { opinion: 4 },
  },
  {
    id: "supprimer-le-cese",
    chapitre: "État et institutions",
    titre: "Supprimer le CESE",
    effet: 40,
    detail: "Dotation votée. Le plus petit montant de la pile, exprès.",
    reactions: { opinion: 1 },
  },
  {
    id: "ceder-des-participations-non-strategiques-de-l",
    chapitre: "État et institutions",
    titre: "Céder des participations non stratégiques de l'État",
    effet: 2000,
    precision: "une seule fois",
    detail: "Valorisations publiées de l'Agence des participations. Une cession réduit la dette, pas le déficit récurrent.",
    reactions: { marches: 1, opinion: -2 },
  },
  {
    id: "reduire-de-5-les-dotations-aux-collectivites",
    chapitre: "État et institutions",
    titre: "Réduire de 5 % les dotations aux collectivités",
    effet: 2200,
    detail: "Concours financiers de l'État aux collectivités.",
    reactions: { territoires: -8, opinion: -2 },
    rejet: { territoires: 3, marches: -1 },
    bloqueePar: ["sans-collectivites"],
  },
  {
    id: "doubler-les-moyens-contre-la-fraude-fiscale",
    chapitre: "État et institutions",
    titre: "Doubler les moyens contre la fraude fiscale et sociale",
    effet: 2000,
    precision: "net",
    detail: "Rendement supplémentaire visé par les plans fraude publiés.",
    reactions: { opinion: 5 },
  },
];
