/** Présentation du projet et voies de correction, identiques avec ou sans JS. */
export function renduProjet(): string {
  return `<article class="analyse-rendu analyse-rendu--long dossier-journal" id="projet-contenu">
    <header class="analyse-longue__entete"><p class="analyse-longue__meta">À propos de 500 Signatures</p><h1 class="analyse-rendu__titre">Le projet et ses corrections.</h1><p class="analyse-longue__chapo">Nous rendons les comptes publics plus faciles à lire, avec leurs sources, leurs périodes et leurs limites.</p></header>
    <section class="analyse-longue__section"><h2>Responsabilité éditoriale</h2><div class="analyse-longue__prose"><p>La publication et la maintenance sont portées par le projet 500 Signatures, identifié par son dépôt public et son compte X. Les organismes cités produisent les données ; ils ne sont pas les éditeurs de ce site.</p><p>Nous proposons trois lectures complémentaires : les comptes nationaux et locaux, les dossiers qui expliquent une question précise, et Mandats, un jeu de décisions. Les données observées, les calculs dérivés et les hypothèses de simulation sont distingués.</p></div></section>
    <section class="analyse-longue__section"><h2>Comment nous travaillons</h2><div class="analyse-longue__prose"><p>Nous transformons les fichiers publics en séries, tableaux et graphiques. Les dossiers ajoutent une explication, un calcul ou une comparaison et indiquent les sources utilisées. Le développement et la rédaction peuvent s’appuyer sur des outils d’intelligence artificielle.</p><p>Les contrôles automatiques rapprochent les observations référencées des fichiers publiés et vérifient leur structure. Ils ne certifient pas toutes les affirmations, les liens externes ou les raisonnements. Une vérification éditoriale des sources et de l’interprétation reste nécessaire.</p><p><a href="/sources/">Consulter les sources et le détail des contrôles</a></p></div></section>
    <section class="analyse-longue__section" id="corrections"><h2>Signaler une erreur</h2><div class="analyse-longue__prose"><p>Pour nous permettre de reproduire le problème, indiquez l’adresse de la page, le passage ou le chiffre concerné, sa période et, si possible, la source qui étaye la correction. Évitez de publier des informations personnelles dans un signalement public.</p><p><a href="https://github.com/supertrampsss/500SIGNATURESV2/issues" target="_blank" rel="noopener noreferrer">Signaler une correction sur GitHub</a> · <a href="https://x.com/500signaturesfr" target="_blank" rel="noopener noreferrer">Contacter 500 Signatures sur X</a></p><p>Une correction substantielle publiée est datée dans l’article. Le dépôt conserve également l’historique des modifications du site.</p></div></section>
    <section class="analyse-longue__section"><h2>Accès et financement</h2><div class="analyse-longue__prose"><p>La consultation des données, des dossiers et du jeu est gratuite. La publicité est le mode de financement prévu ; sa diffusion reste désactivée pendant l’examen AdSense. Elle est exclue du déroulement et des résultats de Mandats.</p><p><a href="/confidentialite/">Consulter les informations de confidentialité et de mesure d’audience</a></p></div></section>
    <p class="dossier-date">Mis à jour le <time datetime="2026-10-03">3 octobre 2026</time>.</p>
  </article>`;
}
