import type { CrisisRule } from "./types.ts";

export const SCENARIO_V3_CRISIS_RULES: readonly CrisisRule[] = Object.freeze([{
  id: "flat-tax-revolt",
  title: "Le pays se fracture sur l'impôt unique",
  body: "Le taux unique dès le premier euro déclenche une contestation nationale. La réforme a presque effacé le déficit, mais son effort sur les revenus modestes menace votre majorité.",
  indicator: "opinion",
  threshold: 40,
  comparator: "lte",
  aggravatingDecisionIds: ["flat-tax-a-20-des-le-premier"],
  concessions: [{
    id: "suspend-flat-tax",
    label: "Suspendre la flat tax et rétablir le barème",
    targetDecisionId: "flat-tax-a-20-des-le-premier",
    policyChange: "suspend",
    effects: [
      {
        id: "flat-tax-suspension:budget",
        target: "indicator",
        key: "annualBalance",
        delta: -150_000,
        timing: { kind: "immediate" },
        duration: "annual",
        explanation: "La suspension annule l'économie annuelle attribuée à la réforme.",
      },
      {
        id: "flat-tax-suspension:opinion",
        target: "indicator",
        key: "opinion",
        delta: 10,
        timing: { kind: "immediate" },
        duration: "once",
        explanation: "Le retrait apaise une partie de la contestation.",
      },
      {
        id: "flat-tax-suspension:capacity",
        target: "indicator",
        key: "reformCapacity",
        delta: -6,
        timing: { kind: "immediate" },
        duration: "once",
        explanation: "Le recul réduit votre capacité à imposer la prochaine réforme.",
      },
    ],
  }],
  holdCourseEffects: [
    {
      id: "flat-tax-hold:opinion",
      target: "indicator",
      key: "opinion",
      delta: -8,
      timing: { kind: "immediate" },
      duration: "once",
      explanation: "Le maintien du cap élargit la contestation.",
    },
    {
      id: "flat-tax-hold:majority",
      target: "indicator",
      key: "majority",
      delta: -7,
      timing: { kind: "immediate" },
      duration: "once",
      explanation: "Une partie de la majorité refuse d'assumer le coût politique.",
    },
    {
      id: "flat-tax-hold:trust",
      target: "indicator",
      key: "institutionalTrust",
      delta: -4,
      timing: { kind: "immediate" },
      duration: "once",
      explanation: "La confrontation durable dégrade la confiance institutionnelle.",
    },
  ],
}]);
