import type { DecisionDisplayCopy, DecisionOptionDisplayCopy } from "./types.ts";

/** Player text is deliberately kept apart from the engine profiles. */
export type V11Copy = Readonly<{ decision: DecisionDisplayCopy; options: readonly DecisionOptionDisplayCopy[] }>;

const rows: readonly [string, readonly string[]][] = [
  ["Réunir l'impôt sur le revenu et la CSG ?", ["Créer un prélèvement progressif unique", "Garder les deux prélèvements"]],
  ["Quels taux de TVA appliquer ?", ["Garder les taux", "Passer le taux normal à 21 %", "Relever la TVA de la restauration"]],
  ["Comment faire contribuer les grands groupes ?", ["Garder les règles", "Pérenniser la surtaxe sur les bénéfices", "Augmenter la taxe sur les rachats d'actions"]],
  ["Comment taxer les très grandes fortunes ?", ["Garder les règles", "Taxer le patrimoine financier", "Taxer 2 % au-delà de 100 M€"]],
  ["Supprimer certaines réductions sur l'épargne ?", ["Supprimer une liste publiée", "Garder la liste actuelle"]],
  ["Comment taxer les héritages ?", ["Garder les règles", "Abattement de 300 000 € par enfant", "Réduire l'avantage de l'assurance-vie", "Supprimer les droits"]],
  ["Quelles aides à l'emploi conserver ?", ["Garder les aides", "Cibler l'apprentissage", "Réduire les exonérations au-dessus de 2,5 SMIC"]],
  ["Réduire les aides fiscales aux entreprises ?", ["Garder les dispositifs", "Réduire les subventions directes", "Recentrer le crédit impôt recherche"]],
  ["À quel âge partir à la retraite ?", ["Revenir à 62 ans", "Garder la règle actuelle", "Aller vers 65 ans"]],
  ["Faire progresser les pensions moins vite que les prix ?", ["Indexer sur les prix", "Retirer un point à la revalorisation"]],
  ["Réduire l'assurance chômage ?", ["Garder les droits", "Réduire les droits selon un barème"]],
  ["Ajouter une retraite par capitalisation ?", ["Garder la répartition seule", "Ajouter un fonds collectif"]],
  ["Passer la durée légale à 39 heures ?", ["Garder 35 heures", "Passer à 39 heures, salaire précisé"]],
  ["Comment augmenter le revenu tiré du travail ?", ["Garder les règles", "Augmenter le SMIC", "Remplacer la prime par moins de prélèvements"]],
  ["Qui doit financer davantage les soins ?", ["Garder les règles", "Doubler les franchises", "Taxer davantage le sucre et l'alcool"]],
  ["Acheter d'abord les médicaments comparables ?", ["Privilégier les équivalents, sauf raison médicale", "Garder les règles"]],
  ["Réduire les arrêts maladie évitables ?", ["Renforcer prévention et contrôle médical", "Garder le dispositif"]],
  ["Où recruter dans les métiers du soin ?", ["À l'hôpital", "Dans le grand âge", "Dans les deux", "Ne pas ajouter de postes"]],
  ["Simplifier l'accès aux prestations sociales ?", ["Garder les démarches", "Unifier la demande et le versement"]],
  ["Augmenter le RSA ?", ["Garder le montant", "Le relever selon un barème publié"]],
  ["Supprimer l'aide médicale d'État ?", ["Garder l'AME", "La supprimer en maintenant les soins obligatoires"]],
  ["Remplacer les complémentaires par une couverture publique ?", ["Garder le système", "Créer une couverture publique unique"]],
  ["Réduire les effectifs ou les rémunérations publiques ?", ["Garder la trajectoire", "Ne pas remplacer une partie des départs", "Geler temporairement les rémunérations"]],
  ["Réduire les frais de structure de l'État ?", ["Garder l'organisation", "Regrouper des opérateurs", "Mutualiser achats, immobilier et fonctions support"]],
  ["Quel rôle d'actionnaire pour l'État ?", ["Vendre des participations nommées", "Les conserver", "Nationaliser des entreprises nommées"]],
  ["Réorganiser les collectivités ?", ["Garder l'organisation", "Transférer les compétences et leur financement", "Transférer et réduire les dotations"]],
  ["Élire l'Assemblée à la proportionnelle ?", ["Garder le scrutin", "Passer à la proportionnelle"]],
  ["Où mettre plus de moyens dans l'école ?", ["Garder les moyens", "Augmenter les salaires enseignants", "Réduire la taille des classes prioritaires"]],
  ["Doubler les bourses étudiantes ?", ["Garder le barème", "Doubler le montant des étudiants déjà éligibles"]],
  ["Construire des logements ou augmenter les APL ?", ["Garder les règles", "Financer plus de logements sociaux", "Augmenter les APL"]],
  ["Créer 200 000 places de crèche ?", ["Garder le rythme", "Financer 200 000 places"]],
  ["Verser les allocations dès le premier enfant ?", ["Garder le droit au deuxième enfant", "Ouvrir dès le premier enfant"]],
  ["Qui doit piloter et financer l'école ?", ["Garder le cadre national", "Donner plus d'autonomie et de choix", "Réduire le financement du privé"]],
  ["Rendre un service national obligatoire ?", ["Le garder volontaire", "L'étendre à une classe d'âge avec exemptions"]],
  ["Où renforcer la sécurité et la justice ?", ["Garder la trajectoire", "Recruter police et gendarmerie", "Recruter magistrats et greffiers", "Construire des places de prison"]],
  ["Décider plus vite sur les demandes d'asile ?", ["Garder les moyens", "Renforcer l'instruction et réduire les délais"]],
  ["Exécuter davantage d'OQTF ?", ["Garder les moyens", "Augmenter les éloignements et la rétention"]],
  ["Doubler les cours de français et l'aide vers l'emploi ?", ["Garder les moyens", "Doubler cours et accompagnement"]],
  ["Imposer cinq ans de résidence pour certaines aides ?", ["Garder les règles", "Exiger cinq ans quand le droit l'autorise"]],
  ["Fixer des objectifs d'immigration de travail ?", ["Garder les règles par titre", "Fixer des objectifs par métier"]],
  ["Fixer des peines minimales en cas de récidive ?", ["Garder l'individualisation", "Fixer un seuil avec dérogation motivée"]],
  ["Légaliser et taxer le cannabis ?", ["Garder l'interdiction", "Créer un marché légal encadré et taxé"]],
  ["Rénover davantage les logements ?", ["Garder le budget", "Doubler l'aide avec des règles publiées"]],
  ["Rénover davantage le réseau ferroviaire ?", ["Garder les crédits", "Augmenter les crédits"]],
  ["Comment aider au passage à l'électrique ?", ["Cibler les ménages modestes qui roulent beaucoup", "Garder le bonus large", "Supprimer les aides"]],
  ["Quel avenir pour le nucléaire ?", ["Construire six EPR2 et prolonger le parc", "Prolonger sans nouvel EPR2", "Fermer d'ici 2040"]],
  ["Taxer davantage les énergies fossiles ?", ["Ne pas relever", "Relever sans remboursement", "Relever et verser une aide ciblée"]],
  ["Arrêter les nouveaux projets renouvelables ?", ["Poursuivre les projets autorisés", "Suspendre les nouveaux projets"]],
  ["Supprimer des avantages fiscaux sur les fossiles ?", ["Garder les avantages", "Supprimer une liste publiée avec transition"]],
  ["À quel rythme augmenter le budget militaire ?", ["Accélérer vers 3 % du PIB", "Tenir la programmation", "Décaler la hausse"]],
  ["Comment renforcer les effectifs disponibles ?", ["Doubler la réserve", "Créer un service militaire volontaire", "Garder les dispositifs"]],
  ["Renforcer le renseignement intérieur ?", ["Garder la trajectoire", "Doubler recrutements, outils et contrôles"]],
  ["Quel niveau de défense partager en Europe ?", ["Garder les décisions nationales", "Acheter et financer en commun", "Intégrer des unités sous commandement commun"]],
  ["Quitter l'euro ?", ["Rester dans l'euro", "Rétablir une monnaie nationale"]],
  ["Organiser un référendum sur la sortie de l'Union ?", ["Ne pas l'organiser", "Organiser le référendum"]],
];

const contexts = [
  "Deux prélèvements sont aujourd'hui retirés des revenus : l'impôt sur le revenu et la contribution sociale généralisée.",
  "La taxe sur la valeur ajoutée est payée sur les achats, mais tous les produits et services ne sont pas au même taux.",
  "Les grands groupes peuvent être davantage imposés sur leurs bénéfices ou sur leurs rachats d'actions.",
  "Le choix porte sur les patrimoines très élevés, financiers ou non.",
  "Certaines règles réduisent l'impôt lié à l'épargne ou au patrimoine.",
  "Les droits de succession, l'abattement par enfant et l'assurance-vie changent ce qui est payé lors d'une transmission.",
  "Les aides à l'apprentissage et les exonérations de cotisations réduisent le coût d'embauche, mais ne visent pas les mêmes emplois.",
  "Les subventions directes et le crédit d'impôt recherche soutiennent certaines entreprises.",
  "L'âge légal fixe le premier âge de départ possible ; carrières longues, handicap et pénibilité gardent leurs règles propres.",
  "La revalorisation annuelle décide si les pensions suivent entièrement l'inflation.",
  "L'assurance chômage verse un revenu temporaire aux personnes qui remplissent les conditions d'ouverture de droits.",
  "Une part des cotisations peut être placée pour plus tard au lieu de financer tout de suite les pensions actuelles.",
  "La durée légale fixe le seuil avant lequel les heures ne reçoivent pas la majoration prévue aujourd'hui.",
  "On peut relever le salaire minimum ou changer l'aide versée aux travailleurs aux revenus modestes.",
  "On peut faire payer davantage les patients à chaque soin ou taxer davantage le sucre et l'alcool.",
  "Les médicaments comparables peuvent être choisis quand ils conviennent au patient, avec une exception médicale.",
  "Prévention, accompagnement et contrôle médical peuvent réduire les arrêts évitables sans juger un arrêt sans décision médicale.",
  "L'hôpital et les établissements pour personnes âgées ont tous deux besoin de professionnels du soin.",
  "Des démarches séparées peuvent retarder l'accès aux prestations sociales.",
  "Le revenu de solidarité active assure un revenu minimum aux personnes qui remplissent ses conditions.",
  "L'aide médicale de l'État permet l'accès aux soins des personnes qui remplissent ses conditions.",
  "Les complémentaires santé couvrent une partie des dépenses qui ne sont pas remboursées par l'assurance maladie.",
  "Les départs à la retraite et les rémunérations déterminent une grande part des dépenses publiques.",
  "Les opérateurs, les achats, l'immobilier et les fonctions support représentent des frais de structure de l'État.",
  "L'État peut vendre, conserver ou acheter des participations dans des entreprises.",
  "Les collectivités se partagent des compétences et leur financement.",
  "Le mode de scrutin détermine comment les voix sont transformées en sièges à l'Assemblée nationale.",
  "Les salaires des enseignants et la taille des classes sont deux façons d'améliorer les moyens de l'école.",
  "Les bourses aident les étudiants selon leur situation et les règles du barème.",
  "Construire des logements sociaux agit avec le temps ; l'aide personnelle au logement agit plus vite sur le loyer.",
  "Créer des places de crèche demande des personnels, des locaux et un financement durable.",
  "Les allocations familiales commencent aujourd'hui au deuxième enfant dans la plupart des cas.",
  "L'État fixe le cadre commun de l'école ; les établissements peuvent aussi recevoir davantage d'autonomie.",
  "Un service national peut rester volontaire ou être étendu à une classe d'âge avec des exemptions.",
  "Police, gendarmerie, justice et prison ne répondent pas aux mêmes besoins ni aux mêmes délais.",
  "Les demandes d'asile doivent être instruites, avec des recours et des conditions d'accueil.",
  "Une obligation de quitter le territoire français doit respecter les recours et les documents nécessaires au retour.",
  "Les cours de français et l'accompagnement vers l'emploi aident les personnes nouvellement arrivées à s'insérer.",
  "Certaines aides peuvent être soumises à une durée de résidence, dans les limites du droit.",
  "L'immigration de travail répond à des besoins de métiers, distincts de l'asile et du regroupement familial.",
  "Le juge adapte aujourd'hui la peine au dossier ; un seuil minimum limiterait cette marge dans les cas définis.",
  "Un marché légal du cannabis demanderait des règles de vente, de prévention et de contrôle.",
  "Rénover un logement réduit ses besoins d'énergie, mais suppose de fixer les ménages et travaux éligibles.",
  "Le réseau ferroviaire doit être entretenu avant que les retards et pannes ne s'accumulent.",
  "Les aides à la voiture électrique peuvent être concentrées sur les ménages qui en ont le plus besoin ou rester ouvertes plus largement.",
  "Le choix porte sur le parc actuel et sur les réacteurs nucléaires de nouvelle génération qui produiraient après les fermetures.",
  "Hausser la taxe sur les carburants et combustibles augmente leur coût ; une aide ne protège que les ménages qui la reçoivent.",
  "Suspendre les nouveaux projets éoliens et solaires oblige à préparer d'autres moyens de production d'électricité.",
  "Retirer des taux réduits ou remboursements augmente le coût de certains carburants ou usages.",
  "La part du produit intérieur brut consacrée à la défense détermine la date des commandes, des stocks et des recrutements.",
  "La réserve ajoute des personnes mobilisables ; un service volontaire demande davantage d'encadrement et de places.",
  "Plus d'agents et d'outils permettent de traiter plus de signalements, avec des règles sur les données et les libertés.",
  "Acheter ou commander en commun avec d'autres pays européens partage les coûts et une part de la décision.",
  "Rétablir une monnaie nationale obligerait à traiter les contrats, les dépôts, la dette et les paiements.",
  "Un référendum ouvre un choix politique ; une sortie de l'Union ne commencerait qu'après un vote favorable et une procédure distincte.",
] as const;

const cardPayers = [
  "Les contribuables versent selon le barème retenu.", "Les clients paient la taxe sur les achats concernés.", "Les groupes visés paient sur leurs bénéfices ou leurs rachats.", "Les détenteurs des patrimoines au-dessus du seuil paient davantage.", "Les utilisateurs des avantages supprimés paient davantage.", "Les héritiers paient selon la transmission.", "Les employeurs concernés versent davantage de cotisations ou perdent une aide.", "Les entreprises visées perdent une aide ou un avantage fiscal.", "Les régimes de retraite, salariés et employeurs sont concernés par la date de départ.", "Les retraités et les régimes de retraite sont concernés.", "Les demandeurs d'emploi concernés reçoivent moins longtemps ou moins.", "Les actifs financent aussi les pensions en cours pendant la transition.", "Les salariés et les employeurs sont concernés par les heures et le salaire.", "Les employeurs ou le budget de la prime financent le changement.", "Les patients ou consommateurs des produits taxés paient davantage.", "L'assurance maladie et les hôpitaux achètent les produits concernés.", "Les organismes d'assurance maladie financent prévention et contrôle.", "L'État finance les postes, la formation et les lieux de travail.", "Les organismes qui versent les prestations financent la mise en place.", "Les départements et organismes payeurs versent le revenu de solidarité active.", "L'État et les hôpitaux supportent les dépenses de soins.", "Les ménages, employeurs et assureurs financent selon la couverture choisie.", "L'État et les employeurs publics financent les effectifs et rémunérations.", "L'État finance la réorganisation et les outils partagés.", "L'État finance l'achat ou reçoit le produit de la vente.", "L'État et les collectivités financent les compétences transférées.", "L'État organise le scrutin selon les règles retenues.", "L'État finance les salaires ou les postes nécessaires.", "L'État verse les bourses aux étudiants éligibles.", "L'État finance les logements ou verse l'aide au logement.", "L'État, les collectivités et les familles financent les places.", "Les caisses familiales versent les allocations selon la règle retenue.", "L'État, les collectivités et les établissements financent l'organisation.", "L'État finance l'encadrement, l'hébergement et les exemptions.", "L'État finance recrutements, formation et fonctionnement.", "L'État finance l'instruction, l'hébergement et les recours.", "L'État finance les moyens d'éloignement et de rétention.", "L'État finance les cours et l'accompagnement.", "Les organismes versent les aides selon les conditions de résidence.", "Les employeurs recrutent selon les titres et métiers autorisés.", "L'État finance les conséquences pour la justice et les prisons.", "L'État finance le contrôle, la prévention et les soins.", "L'État finance l'aide et les contrôles des travaux.", "L'État finance les travaux sur le réseau ferroviaire.", "L'État finance l'aide à l'achat ou à la location.", "L'État et les consommateurs financent les travaux et les installations.", "Les usagers des carburants et combustibles paient la taxe retenue.", "Les contrats et soutiens existants restent à la charge de leurs financeurs.", "Les bénéficiaires des avantages supprimés paient davantage.", "L'État finance les commandes, stocks et recrutements militaires.", "L'État finance formation, équipement et disponibilité des effectifs.", "L'État finance recrutements, outils et contrôles.", "La France finance sa part des programmes et unités retenus.", "L'État, les banques et les entreprises financent la conversion éventuelle.", "L'État finance l'organisation du vote.",
] as const;

const outcomeRows = [
  ["Les deux prélèvements fusionnent dans un barème progressif.", "Les deux prélèvements restent séparés."],
  ["Les taux actuels restent en place.", "Les achats au taux normal peuvent coûter plus cher et l'État reçoit plus de taxe.", "Restaurants, prix ou marges absorbent la hausse de taxe."],
  ["La surtaxe et la taxe suivent leur calendrier actuel.", "La surtaxe sur les bénéfices devient durable.", "Les rachats d'actions sont davantage taxés."],
  ["L'impôt sur la fortune immobilière reste inchangé.", "Les actifs financiers au-dessus du seuil entrent dans l'impôt.", "Un minimum annuel de 2 % s'applique au-delà de 100 millions d'euros."],
  ["Les avantages listés sont retirés.", "Les avantages fiscaux actuels restent disponibles."],
  ["Les règles actuelles de succession restent en place.", "Davantage de transmissions par enfant échappent aux droits.", "Les héritiers de contrats visés paient davantage.", "Les droits de succession disparaissent."],
  ["Les aides et exonérations actuelles continuent.", "Les aides sont réservées aux contrats et formations retenus.", "Les employeurs visés cotisent davantage au-dessus du seuil."],
  ["Subventions et crédit d'impôt recherche restent inchangés.", "Les entreprises perdent les subventions visées à la fin des contrats.", "Le taux, les plafonds ou la liste du crédit d'impôt recherche changent."],
  ["Les générations concernées peuvent partir plus tôt.", "La montée vers 64 ans continue.", "Les générations concernées partent plus tard."],
  ["Les pensions suivent l'inflation.", "Chaque revalorisation augmente d'un point de moins que les prix."],
  ["Durée et montant des droits restent inchangés.", "Les droits concernés baissent ou durent moins longtemps."],
  ["Les cotisations financent directement les pensions actuelles.", "Une part des cotisations est investie pour les pensions futures."],
  ["Les heures au-delà de 35 restent majorées.", "Quatre heures supplémentaires deviennent normales selon les contrats."],
  ["Le salaire minimum et l'aide au travail suivent leurs règles actuelles.", "Les salariés payés au minimum reçoivent davantage en brut.", "La prime est remplacée par moins de prélèvements sur les premiers revenus."],
  ["Franchises et taxes concernées ne changent pas.", "Les patients paient davantage sur médicaments et actes concernés.", "Les consommateurs de sucre et d'alcool paient davantage."],
  ["Les prescriptions privilégient les produits comparables quand le soin le permet.", "Les habitudes de prescription et d'achat ne changent pas."],
  ["Prévention et contrôle médical sont renforcés.", "Le dispositif actuel est conservé."],
  ["Des postes sont ajoutés à l'hôpital.", "Des postes sont ajoutés dans le grand âge.", "Les recrutements sont répartis entre hôpital et grand âge.", "Aucun poste supplémentaire n'est créé."],
  ["Les démarches restent séparées.", "Une même demande déclenche instruction et versement."],
  ["Le montant actuel du revenu de solidarité active reste en place.", "Les personnes éligibles reçoivent un revenu de solidarité active plus élevé selon le barème."],
  ["L'aide médicale de l'État reste en place.", "Les soins obligatoires restent assurés sans cette aide."],
  ["Complémentaires et assurance maladie gardent leur rôle actuel.", "Une couverture publique unique remplace les complémentaires."],
  ["Les départs et rémunérations suivent la trajectoire actuelle.", "Une partie des départs n'est pas remplacée.", "Les rémunérations publiques sont temporairement gelées."],
  ["L'organisation actuelle est conservée.", "Des opérateurs sont regroupés.", "Achats, immobilier et fonctions support sont partagés."],
  ["Des participations publiques sont vendues.", "Le portefeuille public est conservé.", "L'État achète les entreprises désignées."],
  ["L'organisation territoriale reste inchangée.", "Compétences et financement sont transférés ensemble.", "Le transfert s'accompagne d'une réduction des dotations."],
  ["Le scrutin actuel est conservé.", "Les sièges sont répartis à la proportionnelle."],
  ["Les moyens actuels sont maintenus.", "Les salaires enseignants augmentent.", "Les classes prioritaires accueillent moins d'élèves."],
  ["Le barème actuel est conservé.", "Les étudiants déjà éligibles reçoivent le double."],
  ["Les règles actuelles sont maintenues.", "Des logements sont financés d'abord ; leurs effets sur les loyers arrivent plus tard.", "L'aide personnelle au logement augmente."],
  ["Le rythme actuel est maintenu.", "Deux cent mille places sont financées."],
  ["Le droit commence au deuxième enfant.", "Le droit s'ouvre dès le premier enfant."],
  ["Le cadre national est conservé.", "Les établissements reçoivent plus d'autonomie.", "Le financement public du privé diminue."],
  ["Le service national reste volontaire.", "Une classe d'âge est appelée avec les exemptions prévues."],
  ["La trajectoire actuelle est maintenue.", "Police et gendarmerie recrutent davantage.", "Magistrats et greffiers recrutent davantage.", "De nouvelles places de prison sont construites."],
  ["Les moyens actuels sont conservés.", "L'instruction est renforcée pour réduire les délais."],
  ["Les moyens actuels sont conservés.", "Les moyens d'éloignement et de rétention augmentent sans promettre un nombre de retours."],
  ["Les moyens actuels sont conservés.", "Les cours de français et l'accompagnement vers l'emploi doublent."],
  ["Les règles actuelles continuent.", "Le délai de résidence s'applique aux aides autorisées par le droit."],
  ["Les règles restent fixées par titre.", "Des objectifs sont fixés métier par métier."],
  ["Le juge conserve son individualisation.", "Un seuil minimum s'applique sauf dérogation motivée."],
  ["L'interdiction actuelle continue.", "La vente devient légale dans un cadre contrôlé et taxé."],
  ["Le budget actuel est conservé.", "L'aide à la rénovation double avec des règles d'accès publiées."],
  ["Les crédits actuels sont conservés.", "Les crédits de rénovation ferroviaire augmentent."],
  ["L'aide est ciblée sur les ménages modestes qui roulent beaucoup.", "Le bonus reste ouvert à tous les ménages éligibles.", "Les aides à l'achat et à la location s'arrêtent."],
  ["La France engage six nouveaux réacteurs et garde le parc actuel tant qu'il est autorisé et sûr.", "Le parc actuel est prolongé sans nouveau réacteur.", "Les fermetures sont préparées avec des capacités de remplacement."],
  ["La taxe ne change pas.", "La hausse de taxe ne donne lieu à aucun remboursement.", "Une partie de la recette est versée aux ménages retenus."],
  ["Les projets autorisés continuent.", "Les nouveaux projets éoliens et solaires sont suspendus."],
  ["Les avantages existants restent en place.", "Les avantages listés sont supprimés avec un délai de transition."],
  ["Les commandes, stocks et recrutements peuvent être avancés si les capacités suivent.", "La programmation votée continue.", "Une partie de la hausse est reportée."],
  ["La réserve reçoit plus de formation, d'équipement et de jours d'activité.", "Un service volontaire organise encadrement, solde et hébergement.", "Les volumes actuels sont conservés."],
  ["La trajectoire actuelle est conservée.", "Les services reçoivent plus d'agents, d'outils et de contrôles."],
  ["Les décisions restent nationales.", "Certains programmes sont achetés et financés en commun.", "Des unités désignées passent sous commandement commun."],
  ["Contrats, dépôts et paiements restent en euro.", "Les contrats, dépôts, dettes et paiements sont préparés pour une nouvelle monnaie."],
  ["Aucun référendum n'est lancé.", "Le vote est préparé et tenu ; la sortie n'est pas encore décidée."],
] as const;

function writtenOption(index: number, optionIndex: number, label: string): DecisionOptionDisplayCopy {
  const outcome = outcomeRows[index]?.[optionIndex];
  if (!outcome) throw new Error(`missing-v11-copy:${index}:${optionIndex}:${label}`);
  return {
    shortLabel: label,
    outcome,
    details: {
      whatChanges: outcome,
      whoPays: [cardPayers[index]!],
      when: /^(Garder|Ne pas|Le garder|Rester|Poursuivre|Prolonger|Tenir|Indexer|Les conserver)/i.test(label) ? "Le calendrier actuel continue." : "La règle prend effet après les textes et préparatifs nécessaires.",
    },
  };
}

const deckCopy: readonly V11Copy[] = rows.map(([question, labels], index) => ({
  decision: { question, context: contexts[index]! },
  options: labels.map((label, optionIndex) => writtenOption(index, optionIndex, label)),
}));

// These two cards have already been approved word for word by the user.
const approvedCopy: Readonly<Record<number, V11Copy>> = {
  0: {
    decision: {
      question: "Fusionner l'impôt sur le revenu et la CSG ?",
      context: "L'impôt sur le revenu dépend des revenus du foyer. La CSG est retirée des salaires, retraites et revenus du patrimoine pour financer la Sécurité sociale.",
    },
    options: [
      { shortLabel: "Créer un impôt unique et progressif", outcome: "Tout le monde contribue dès le premier euro et le taux augmente avec le revenu.", details: { whatChanges: "L'impôt sur le revenu et la CSG sont remplacés par un seul prélèvement.", howItWorks: "Le taux augmente progressivement avec le revenu, sans saut brutal entre deux niveaux.", whoPays: ["Chaque personne ayant un revenu contribue selon ce barème."] } },
      { shortLabel: "Garder le système actuel", outcome: "L'impôt sur le revenu et la CSG restent calculés séparément.", details: { whatChanges: "Les deux prélèvements restent distincts.", howItWorks: "L'impôt sur le revenu dépend du foyer et la CSG reste retirée directement des revenus concernés." } },
    ],
  },
  38: {
    decision: {
      question: "Attendre cinq ans avant de recevoir certaines aides ?",
      context: "La mesure vise les étrangers hors Union européenne récemment installés. Elle concerne les aides pour les enfants, la naissance, la rentrée scolaire et celles qui réduisent le loyer.",
    },
    options: [
      { shortLabel: "Garder les règles actuelles", outcome: "Chaque aide conserve ses propres conditions d'accès.", details: { whatChanges: "Les conditions d'accès aux aides concernées ne changent pas.", howItWorks: "Chaque aide continue d'être versée selon ses règles actuelles." } },
      { shortLabel: "Exiger cinq ans de résidence régulière", outcome: "Les aides concernées sont versées après cinq ans de résidence régulière.", details: { whatChanges: "Le délai s'applique aux aides pour les enfants, la naissance, la rentrée scolaire et celles qui réduisent le loyer.", howItWorks: "Une personne concernée attend cinq ans de résidence régulière avant de recevoir ces aides.", whoPays: ["Les organismes qui versent ces aides les paient moins souvent pendant les cinq premières années."], whoGainsOrLoses: ["Les étrangers hors Union européenne installés depuis moins de cinq ans reçoivent ces aides plus tard.", "Le revenu minimum, l'assurance chômage, les retraites, les aides liées au handicap et les remboursements de soins ne sont pas inclus."], when: "La règle commence après le changement de la loi et la date d'application retenue." } },
    ],
  },
};

export const V11_COPY: readonly V11Copy[] = deckCopy.map((copy, index) => approvedCopy[index] ?? copy);
