import type { Choice, Dossier, Effect, Mode } from './types.ts';

/** Authored v3 campaign. Money is synthetic M€ (city) or Md€ (APU).
 * Recurring effects persist; investments/grants/repayments concern one exercise.
 * Delays are whole YEARS, never the number of cards clicked. */
type Option = { title: string; description: string; effect: Effect; sacrifice: string; delayed?: Choice['delayed'] };
type Brief = { category: string; title: string; story: string; advisor: string; options: [Option, Option, Option] };
const o = (title: string, description: string, effect: Effect, sacrifice: string, delayed?: Choice['delayed']): Option => ({ title, description, effect, sacrifice, ...(delayed ? { delayed } : {}) });
const later = (after: number, label: string, effect: Effect): Choice['delayed'] => ({ after, label, effect });
const b = (category: string, title: string, story: string, advisor: string, ...options: [Option, Option, Option]): Brief => ({ category, title, story, advisor, options });

const municipalBriefs: Brief[] = [
  // Année 1 : prendre la mesure. Huit décisions, une seule clôture.
  b('Écoles', 'Les premières pluies dans les classes', 'Deux toitures réclament une intervention. Rénover leur enveloppe prend deux ans ; les réparations seules ne réduiront pas les pertes de chaleur.', 'Bâtiments municipaux · La commune entretient les locaux scolaires, pas les postes enseignants.',
    o('Rénover par étapes', 'Engager isolation et ventilation sur les locaux prioritaires.', { investment: 2.4 }, 'Le confort ne progresse qu’à la livraison.', later(2, 'La rénovation scolaire est livrée : locaux plus confortables et économies d’énergie modélisées.', { services: 3, resilience: 3, assets: 3, operating: -.2, area: 'hauts' })),
    o('Réparer les toitures', 'Protéger les classes sans reprendre toute l’enveloppe.', { investment: .7, assets: 2, area: 'hauts' }, 'La consommation d’énergie reste élevée.'),
    o('Réorganiser les salles', 'Écarter les locaux les plus dégradés dans le parc existant.', { services: -1, assets: -1, area: 'hauts' }, 'Des classes disposent de moins d’espace.')),
  b('Accueil municipal', 'Une mairie ouverte quand les habitants travaillent ?', 'Les horaires actuels obligent certains habitants à poser une demi-journée. Les équipes peuvent changer leur organisation, mais pas tout absorber.', 'Ressources humaines · Toute ouverture supplémentaire doit trouver ses moyens.',
    o('Ouvrir une soirée', 'Financer une permanence hebdomadaire avec des agents supplémentaires.', { operating: .2, services: 2 }, 'La charge revient chaque année.'),
    o('Déplacer une permanence', 'Remplacer une matinée peu fréquentée par une fin de journée.', { services: 1, cohesion: -1 }, 'Certains usagers perdent leur créneau habituel.'),
    o('Conserver les horaires', 'Stabiliser l’organisation pendant le diagnostic des besoins.', {}, 'Les contraintes des actifs restent entières.')),
  b('Recettes locales', 'Une petite hausse, une marge durable', 'Les recettes héritées laissent peu de place aux nouveaux engagements. Modifier les taux communaux répartit autrement l’effort entre contribuables et budget.', 'Finances · Rendements de jeu, pas calcul de taxe foncière individuelle.',
    o('Ajuster les taux', 'Augmenter modestement les recettes récurrentes du scénario.', { revenue: .6, trust: -2 }, 'Les contribuables concernés paient davantage.'),
    o('Alléger les taux', 'Réduire les recettes pour laisser davantage aux contribuables.', { revenue: -.4, trust: 2 }, 'La marge se réduit pour tout le mandat.'),
    o('Maintenir les taux', 'Garder les règles actuelles et financer les choix par ailleurs.', {}, 'Aucune recette nouvelle.')),
  b('Voirie communale', 'Refaire la rue, ou traiter les points dangereux ?', 'Une rue communale cumule chaussée usée et traversées difficiles. Le chantier complet mobiliserait une part importante du programme annuel.', 'Voirie · Intervention sur une voie supposée communale dans ce scénario.',
    o('Reprendre la rue', 'Rénover chaussée et traversées accessibles.', { investment: 1.4, assets: 2, services: 1, area: 'centre' }, 'Les autres rues devront patienter.'),
    o('Sécuriser les traversées', 'Traiter les intersections les plus exposées.', { investment: .3, services: 1, area: 'centre' }, 'L’usure de la chaussée demeure.'),
    o('Réaffecter l’entretien', 'Donner la priorité à cette rue dans le planning existant.', { assets: -1 }, 'Moins de passages sur les autres voies.')),
  b('Énergie des bâtiments', 'Chauffer des murs, ou rendre les bâtiments sobres ?', 'Plusieurs bâtiments municipaux consomment beaucoup. Un programme technique peut réduire les charges, à condition d’accepter le délai des travaux.', 'Énergie · Les économies sont des hypothèses de simulation.',
    o('Rénover les installations', 'Engager régulation et isolation sur un premier lot.', { investment: 1.8 }, 'Le budget est engagé avant les économies.', later(1, 'Le premier lot énergétique entre en service.', { operating: -.3, resilience: 2, assets: 2 })),
    o('Financer des réglages', 'Ajouter un suivi technique permanent des consommations.', { operating: .1, resilience: 1 }, 'Une charge récurrente sans rénovation lourde.'),
    o('Réduire les plages chauffées', 'Concentrer les activités dans les espaces déjà occupés.', { operating: -.1, services: -1 }, 'Certains locaux deviennent moins disponibles.')),
  b('Cofinancement', 'Une aide arrive avec son calendrier', 'Un appel à projets cofinance des cheminements accessibles. Il impose un chantier cette année, alors que d’autres besoins ne bénéficient d’aucune aide.', 'Finances · La subvention est affectée au projet, jamais aux charges courantes.',
    o('Engager le chantier aidé', 'Financer des accès piétons avec le cofinanceur du scénario.', { investment: 1.6, grants: .6, services: 2 }, 'La commune finance le solde du chantier.'),
    o('Limiter le périmètre', 'Traiter seulement un accès prioritaire sans aide.', { investment: .4, services: 1 }, 'L’amélioration reste localisée.'),
    o('Renoncer à cette aide', 'Conserver le calendrier municipal et ses priorités.', {}, 'Le cofinancement de cet appel est perdu.')),
  b('Précaution', 'Quelle marge garder pour l’imprévu ?', 'Le premier budget prend forme. Réduire les achats non essentiels crée une réserve, mais les services avaient prévu de renouveler du petit matériel.', 'Finances · Une économie augmente la marge ; elle ne constitue pas une recette supplémentaire.',
    o('Réduire les achats récurrents', 'Allonger le cycle de renouvellement du petit matériel.', { operating: -.3, services: -1 }, 'Les équipes travaillent avec du matériel plus ancien.'),
    o('Accélérer le remplacement', 'Renouveler les matériels municipaux les plus fragiles.', { investment: .5, assets: 1 }, 'Moins de trésorerie disponible cette année.'),
    o('Garder le programme actuel', 'Conserver achats et entretien prévus au départ.', {}, 'Pas de réserve supplémentaire.')),
  b('Premier budget', 'Un dernier engagement avant la clôture ?', 'Les services proposent une amélioration supplémentaire de l’accueil. Elle est utile, mais s’ajoutera aux dépenses de chaque exercice suivant.', 'Conseil municipal · Les comptes se ferment après ce dossier, pas après chaque carte.',
    o('Pérenniser l’accompagnement', 'Renforcer l’aide aux démarches municipales.', { operating: .2, cohesion: 2, area: 'hauts' }, 'Une dépense durable commence cette année.'),
    o('Aménager l’accueil existant', 'Rendre les guichets plus accessibles sans agrandir les équipes.', { investment: .5, services: 1, assets: 1 }, 'Les horaires ne changent pas.'),
    o('Clore sans nouvel engagement', 'Laisser le budget absorber les décisions déjà prises.', {}, 'L’accueil conserve ses limites.')),
  // Année 2 : mettre en chantier.
  b('Suivi des écoles', 'Le calendrier scolaire rencontre les travaux', 'Qu’une rénovation soit engagée ou encore à préparer, les périodes d’intervention sont rares. Réserver les vacances facilite les chantiers, mais concentre les contraintes.', 'Bâtiments municipaux · Ce dossier organise les interventions, sans présumer d’une rénovation antérieure.',
    o('Préparer des locaux relais', 'Aménager temporairement des salles municipales disponibles.', { investment: .6, services: 1, area: 'hauts' }, 'Une dépense supplémentaire avant tout confort durable.'),
    o('Renforcer la coordination', 'Financer un suivi régulier des interventions scolaires.', { operating: .1, assets: 1 }, 'La coordination devient une charge récurrente.'),
    o('Intervenir pendant les vacances', 'Conserver les moyens existants et limiter les plages de chantier.', {}, 'La programmation dispose de moins de souplesse.')),
  b('Prix des travaux', 'Les devis laissent moins de place', 'Un lot d’entretien prévu coûte davantage que l’enveloppe souhaitée. Vous pouvez maintenir son contenu, le phaser ou reprendre la consultation.', 'Commande publique · Le dépassement concerne ce lot de scénario, pas tous les projets de la ville.',
    o('Maintenir le contenu', 'Ajouter une petite tranche de travaux sans rogner la prestation.', { investment: .7, assets: 2 }, 'Le financement des autres priorités se resserre.'),
    o('Réduire le lot', 'Réparer uniquement les éléments les plus dégradés.', { investment: .3, assets: 1 }, 'La finition reste incomplète.'),
    o('Revoir la consultation', 'Chercher un autre phasage avant de signer.', { trust: -1 }, 'Les habitants attendent plus longtemps.')),
  b('Petite enfance', 'Des familles sans solution de garde', 'Le service municipal de petite enfance reçoit plus de demandes. Une extension exige des locaux et des professionnels ; l’organisation existante peut aussi être adaptée.', 'Petite enfance · Offre municipale du scénario ; autorisations et partenaires restent nécessaires.',
    o('Aménager une petite extension', 'Préparer de nouvelles places municipales pour l’année suivante.', { investment: 1.2 }, 'Les familles n’en bénéficient pas immédiatement.', later(1, 'L’extension de petite enfance ouvre avec ses charges de personnel.', { operating: .3, services: 2, cohesion: 2 })),
    o('Élargir les horaires', 'Renforcer durablement les équipes sur les créneaux tendus.', { operating: .2, services: 1, cohesion: 1 }, 'Pas de places supplémentaires dans la journée.'),
    o('Réorganiser les créneaux', 'Mieux répartir l’offre existante entre les demandes.', {}, 'Le nombre total de places ne progresse pas.')),
  b('Logement', 'Agir sur le logement avec les bons partenaires', 'La commune souhaite remettre un petit site en usage. La politique de l’habitat dépend aussi de l’intercommunalité et des bailleurs : aucun logement ne se décide seul.', 'Habitat · Négociation avec l’EPCI et les bailleurs, pas construction municipale automatique.',
    o('Cofinancer la préparation', 'Contribuer à un site dont les partenaires acceptent le programme dans le scénario.', { investment: 1 }, 'La commune engage des moyens avant la livraison.', later(2, 'Le programme de logement cofinancé améliore l’accès dans le scénario.', { cohesion: 3, services: 1 })),
    o('Renforcer la médiation', 'Financer l’orientation vers les bailleurs et les dispositifs existants.', { operating: .1, cohesion: 1 }, 'L’offre de logements ne progresse pas.'),
    o('Négocier sans apport nouveau', 'Porter la priorité au programme intercommunal.', {}, 'Aucune livraison supplémentaire n’est garantie.')),
  b('Déplacements à pied', 'Le chemin de l’école coupe un axe fréquenté', 'Des familles demandent un accès plus confortable. La commune peut aménager la rue de son ressort ; les habitudes de circulation devront changer.', 'Espaces publics · La répartition réelle des compétences doit être lue dans le profil communal.',
    o('Aménager un cheminement', 'Élargir les passages et rendre les traversées accessibles.', { investment: .9, services: 2, resilience: 1, area: 'hauts' }, 'Le chantier occupe l’espace public.'),
    o('Financer une présence aux sorties', 'Renforcer l’accompagnement municipal sur les horaires scolaires.', { operating: .1, services: 1 }, 'La dépense revient chaque année.'),
    o('Ajuster le plan de circulation', 'Réorganiser les accès avec les équipes actuelles.', { services: 1, trust: -1 }, 'Certains trajets deviennent moins directs.')),
  b('Achats et équipes', 'Mutualiser sans désorganiser', 'Plusieurs services achètent séparément les mêmes fournitures. Un regroupement peut économiser de l’argent, mais demande de changer les habitudes.', 'Commande publique · Les gains présentés sont des hypothèses prudentes de jeu.',
    o('Mutualiser les achats', 'Réduire les références et regrouper les commandes récurrentes.', { operating: -.2, services: -1 }, 'Les services perdent de la souplesse.'),
    o('Moderniser la gestion des stocks', 'Équiper les services avant de changer leur organisation.', { investment: .4 }, 'Le gain arrive plus tard.', later(1, 'La gestion commune des stocks évite des achats redondants.', { operating: -.1, assets: 1 })),
    o('Garder les achats séparés', 'Préserver l’autonomie des équipes.', {}, 'Les doublons subsistent.')),
  b('Sport et culture', 'Un gymnase usé, une salle très demandée', 'Les associations ont besoin de créneaux. Rénover améliore l’existant ; ouvrir davantage nécessite des équipes et du chauffage.', 'Vie associative · Le choix porte sur des équipements municipaux existants.',
    o('Réhabiliter le gymnase', 'Traiter les vestiaires et les accès.', { investment: 1.7, assets: 2, services: 1, area: 'centre' }, 'La salle culturelle conserve ses limites.'),
    o('Ouvrir plus de créneaux', 'Financer l’exploitation de soirées supplémentaires.', { operating: .2, services: 2, cohesion: 1 }, 'L’usure des locaux reste à traiter.'),
    o('Partager autrement les créneaux', 'Réserver davantage de temps aux publics jusque-là moins servis.', { cohesion: 1, trust: -1 }, 'Certaines associations perdent leur horaire.')),
  b('Programme d’investissement', 'Tout le programme ne tiendra pas en même temps', 'Les petites décisions ont formé un portefeuille de besoins. Une enveloppe ciblée peut traiter les urgences ; la reporter protège la marge annuelle.', 'Finances · Les investissements déjà engagés restent dus.',
    o('Ajouter un lot prioritaire', 'Financer une tranche d’entretien sur les équipements les plus usés.', { investment: 1.1, assets: 2 }, 'Le programme financier se densifie.'),
    o('Protéger l’entretien courant', 'Renforcer les moyens récurrents de petites réparations.', { operating: .2, assets: 1 }, 'Une dépense durable remplace une partie des grands travaux.'),
    o('Geler les nouveaux lots', 'Terminer les engagements pris avant d’en ajouter.', {}, 'Le retard de patrimoine n’est pas réduit.')),
  // Année 3 : encaisser une crise.
  b('Préparation à la chaleur', 'L’été se prépare avant les alertes', 'Les secteurs les moins ombragés sont exposés. Planter agit lentement ; mobiliser les lieux existants protège plus vite sans transformer les rues.', 'Prévention · Exposition et besoins sont des indices de jeu, pas un diagnostic sanitaire local.',
    o('Créer des îlots de fraîcheur', 'Désimperméabiliser et planter une première série de places.', { investment: 1.5 }, 'La protection complète attend la livraison.', later(1, 'Les nouveaux îlots de fraîcheur sont accessibles.', { resilience: 3, services: 1, area: 'rives' })),
    o('Renforcer le plan estival', 'Financer chaque été des lieux frais et leur accueil.', { operating: .2, resilience: 2, cohesion: 1 }, 'Les charges se prolongent au-delà de la crise.'),
    o('Coordonner les lieux existants', 'Adapter les horaires et les informations sans nouvelle équipe.', { resilience: 1, services: -1 }, 'L’organisation sollicite les autres services.')),
  b('Réponse à la chaleur', 'La chaleur arrive maintenant', 'Une période difficile est annoncée dans le scénario. L’urgence porte sur l’accès aux lieux frais et l’organisation quotidienne, quelle que soit votre stratégie d’aménagement.', 'Cellule de crise · L’aide renforcée ci-dessous s’éteint après un exercice.',
    o('Ouvrir un accueil renforcé', 'Déployer une aide municipale temporaire aux habitants exposés.', { operating: .3, cohesion: 2, resilience: 1 }, 'Une dépense immédiate sans transformation du bâti.', later(1, 'Le renfort exceptionnel d’accueil estival prend fin.', { operating: -.3 })),
    o('Équiper les lieux d’accueil', 'Installer des protections solaires réutilisables.', { investment: .5, resilience: 2 }, 'La capacité d’accompagnement humain ne progresse pas.'),
    o('Redéployer les équipes', 'Concentrer les moyens existants sur les lieux frais.', { resilience: 1, services: -1 }, 'D’autres permanences sont réduites.')),
  b('Facture énergétique', 'Le prix de l’énergie tend le budget', 'Les consommations héritées restent coûteuses. Réduire les horaires limite la charge ; corriger les équipements exige des moyens avant les économies.', 'Énergie · Aucun choix municipal ne fixe le prix de marché.',
    o('Corriger les installations', 'Financer un lot supplémentaire de régulation et d’étanchéité.', { investment: .8 }, 'L’économie ne finance pas les travaux immédiatement.', later(1, 'Les corrections techniques réduisent les consommations modélisées.', { operating: -.2, resilience: 1 })),
    o('Maintenir le confort', 'Ajouter une marge récurrente pour maintenir les usages.', { operating: .2, services: 1 }, 'Le fonctionnement absorbe davantage de ressources.'),
    o('Regrouper les activités', 'Fermer les espaces sous-utilisés à certains horaires.', { operating: -.2, services: -1 }, 'Les usagers ont moins de choix de lieux.')),
  b('Solidarités', 'L’accueil social voit les demandes monter', 'Le centre communal d’action sociale constate des besoins accrus dans le scénario. La commune peut agir en proximité et orienter vers les autres acteurs.', 'Solidarités · L’action municipale complète celle du département et des organismes sociaux.',
    o('Renforcer l’accompagnement', 'Financer des permanences sociales durables.', { operating: .2, cohesion: 2, area: 'hauts' }, 'L’engagement se poursuit les années suivantes.'),
    o('Adapter les locaux d’accueil', 'Créer un espace confidentiel dans un bâtiment existant.', { investment: .3, services: 1, cohesion: 1 }, 'Pas de professionnel supplémentaire.'),
    o('Coordonner les relais existants', 'Mieux orienter les demandes entre partenaires.', {}, 'Les capacités d’accueil restent limitées.')),
  b('Patrimoine exposé', 'Un équipement ferme après un incident', 'Dans ce scénario, un équipement municipal nécessite une remise en état. La fermeture est locale, mais son absence déplace les usages vers les autres sites.', 'Bâtiments · Incident fictif ; aucun bâtiment réel n’est déclaré dangereux.',
    o('Réhabiliter l’équipement', 'Réparer les parties endommagées et améliorer leur résistance.', { investment: 1.3, assets: 2, resilience: 1 }, 'La dépense s’ajoute au programme de l’année.'),
    o('Remettre le minimum en service', 'Financer une réparation limitée aux usages prioritaires.', { investment: .4, services: 1 }, 'Le patrimoine reste fragile.'),
    o('Maintenir la fermeture', 'Reporter les activités vers les sites existants.', { services: -2, assets: -1 }, 'Les usagers perdent un lieu de proximité.')),
  b('Commerces et espace public', 'Une place doit-elle changer d’usage ?', 'Commerçants, riverains et piétons souhaitent des choses différentes. La commune peut aménager l’espace public ; les aides économiques relèvent d’autres compétences à coordonner.', 'Attractivité · Pas de subvention municipale directe aux entreprises supposée ici.',
    o('Transformer la place', 'Créer des cheminements et du mobilier ombragé.', { investment: 1.1, services: 1, resilience: 2, area: 'centre' }, 'Le chantier perturbe temporairement les accès.'),
    o('Renforcer la gestion des usages', 'Financer propreté et médiation sur les horaires fréquentés.', { operating: .1, cohesion: 1, services: 1 }, 'L’espace conserve son aménagement actuel.'),
    o('Tester une nouvelle circulation', 'Réorganiser les usages avec le matériel disponible.', { services: 1, trust: -1 }, 'Les habitudes de livraison doivent changer.')),
  b('Réception des travaux', 'Livrer vite ou vérifier chaque réserve ?', 'Des interventions arrivent à leur réception annuelle. Les contrôles portent sur les travaux réellement engagés ; les besoins restés sans chantier demeurent dans le programme.', 'Maîtrise d’ouvrage · Cette enveloppe de contrôle ne crée pas une livraison fictive.',
    o('Renforcer les vérifications', 'Équiper le suivi des petits travaux et des réserves.', { investment: .3, assets: 1 }, 'Un budget supplémentaire pour une amélioration peu visible.'),
    o('Pérenniser le suivi technique', 'Ajouter une capacité récurrente de contrôle des bâtiments.', { operating: .1, assets: 1 }, 'Une charge durable de supervision.'),
    o('Garder la procédure existante', 'Réceptionner uniquement les interventions achevées avec les moyens actuels.', {}, 'Moins de capacité pour les contrôles supplémentaires.')),
  b('Correction du budget', 'La crise a consommé de la marge', 'Avant la clôture, il reste à choisir la place des services non prioritaires. Corriger les charges améliore le budget, mais rend l’effort concret pour les habitants.', 'Finances · Le besoin réel de correction dépend de vos décisions antérieures.',
    o('Réduire les prestations secondaires', 'Diminuer un ensemble de dépenses courantes non essentielles.', { operating: -.4, services: -2, trust: -1 }, 'L’offre municipale recule.'),
    o('Ajuster les recettes', 'Ajouter une ressource fiscale récurrente modeste au modèle.', { revenue: .4, trust: -2 }, 'Les contribuables supportent l’ajustement.'),
    o('Maintenir le périmètre', 'Conserver les prestations et les recettes décidées.', {}, 'Aucune nouvelle marge pour absorber la crise.')),
  // Année 4 : faire fonctionner.
  b('Exploitation', 'Les équipements ont besoin d’équipes', 'Les locaux en service demandent de l’accueil et du nettoyage. Un bâtiment rénové ne remplace pas les agents qui le font fonctionner.', 'Services · Les charges de livraison déjà engagées restent comptées séparément.',
    o('Renforcer les équipes d’accueil', 'Ajouter des moyens sur les plages les plus fréquentées.', { operating: .3, services: 2 }, 'Une dépense annuelle supplémentaire.'),
    o('Adapter les espaces', 'Simplifier les circulations et les postes d’accueil.', { investment: .6, services: 1, assets: 1 }, 'Les horaires restent les mêmes.'),
    o('Concentrer les ouvertures', 'Conserver les effectifs et regrouper les activités.', { operating: -.1, services: -1 }, 'Moins de liberté dans les horaires.')),
  b('Entretien préventif', 'Une fuite réparée avant qu’elle coûte cher', 'Le service technique propose un programme de contrôles réguliers. L’absence d’incident visible rend la dépense difficile à défendre, mais le patrimoine continue de vieillir.', 'Patrimoine · Prévention et remplacement répondent à des besoins différents.',
    o('Renouveler les éléments fragiles', 'Remplacer une première série d’installations vieillissantes.', { investment: .9, assets: 2 }, 'Les moyens sont engagés avant la panne.'),
    o('Pérenniser les tournées', 'Financer un entretien préventif plus régulier.', { operating: .2, assets: 1, resilience: 1 }, 'La dépense revient chaque année.'),
    o('Intervenir à la demande', 'Maintenir les tournées actuelles et réparer les urgences.', { assets: -1 }, 'Les défauts sont repérés plus tard.')),
  b('Accès aux services', 'La même démarche, deux expériences', 'Certains habitants utilisent les services à distance ; d’autres ont besoin d’un guichet. La simplification peut améliorer le parcours sans imposer le tout numérique.', 'Accueil · Toujours une voie humaine pour les démarches municipales.',
    o('Renforcer les permanences', 'Ajouter une présence de proximité aux horaires utiles.', { operating: .2, services: 2, area: 'hauts' }, 'Une charge durable pour les équipes.'),
    o('Aménager un guichet mobile', 'Équiper les agents pour des permanences dans les locaux municipaux.', { investment: .4, services: 1, cohesion: 1 }, 'Les permanences utilisent les effectifs existants.'),
    o('Simplifier les démarches', 'Réduire les étapes internes avec l’équipe actuelle.', { services: 1, trust: -1 }, 'La réorganisation perturbe temporairement l’accueil.')),
  b('Partenariat mobilité', 'Une desserte à négocier', 'L’autorité organisatrice de la mobilité étudie une amélioration de desserte. La commune peut financer ses accès et porter la demande, pas décider seule d’une ligne.', 'Mobilité · Partenariat avec l’AOM ou l’EPCI selon le territoire.',
    o('Cofinancer les accès', 'Aménager des cheminements vers les arrêts retenus par les partenaires.', { investment: 1.2, services: 2, resilience: 1 }, 'Le financement de l’exploitation relève du partenaire.'),
    o('Soutenir l’information locale', 'Financer l’accompagnement des habitants vers l’offre existante.', { operating: .1, services: 1 }, 'Aucune fréquence supplémentaire garantie.'),
    o('Porter la demande à l’AOM', 'Négocier l’amélioration sans nouvel apport communal.', {}, 'Le calendrier reste celui de l’autorité compétente.')),
  b('Renaturation', 'Rendre le sol à la pluie', 'Une cour et un parking stockent la chaleur et ruissellent. Transformer les sols améliore leur usage, tandis que l’entretien des espaces plantés devra être assuré.', 'Espaces publics · Les gains sont des indices de jeu, pas une mesure hydrologique.',
    o('Désimperméabiliser un premier site', 'Remplacer une partie des sols minéraux par des espaces perméables.', { investment: 1.4 }, 'Le chantier ne protège pas immédiatement.', later(1, 'Le site renaturé ouvre ; son entretien végétal est financé.', { resilience: 3, operating: .1, area: 'rives' })),
    o('Entretenir davantage les plantations', 'Renforcer le soin aux espaces verts existants.', { operating: .1, resilience: 1, assets: 1 }, 'Aucune nouvelle surface perméable.'),
    o('Garder les surfaces actuelles', 'Réserver les moyens à un autre engagement.', {}, 'L’exposition du site reste inchangée.')),
  b('Ressources humaines', 'Recruter ou réorganiser ?', 'Les demandes se concentrent sur quelques équipes municipales. Le recrutement améliore la capacité, tandis que la réorganisation redistribue la charge.', 'Ressources humaines · Les indices ne mesurent pas l’opinion réelle des agents.',
    o('Renforcer les métiers en tension', 'Pérenniser des moyens dans les services les plus sollicités.', { operating: .3, services: 2 }, 'La masse salariale augmente durablement.'),
    o('Financer la formation interne', 'Donner aux agents des compétences partagées entre services.', { operating: .1 }, 'Le bénéfice demande du temps.', later(1, 'La formation facilite les remplacements entre services.', { services: 1, assets: 1 })),
    o('Redistribuer les missions', 'Réorganiser les priorités avec les effectifs existants.', { operating: -.1, services: -1 }, 'Certaines tâches seront moins fréquentes.')),
  b('Point de financement', 'Une dette moins lourde, des projets moins rapides', 'Les engagements s’accumulent. Un remboursement supplémentaire diminue la dette ; un nouveau chantier améliore le patrimoine mais consomme la marge disponible.', 'Finances · Tout remboursement supplémentaire reste soumis à la capacité financière du modèle.',
    o('Rembourser davantage', 'Affecter une partie des ressources propres au capital restant dû.', { repayment: .8 }, 'Cette marge ne finance pas un nouveau chantier.'),
    o('Rénover un petit équipement', 'Engager un lot ciblé sur le patrimoine existant.', { investment: 1.1, assets: 2 }, 'La capacité de financement est mobilisée.'),
    o('Conserver la marge disponible', 'Ne pas ajouter de projet ni de remboursement anticipé.', {}, 'La dette suit son calendrier normal.')),
  // Année 5 : choisir ce qui reste possible.
  b('Bilan d’usage', 'Les équipements servent-ils les bons besoins ?', 'La fréquentation observée dans le scénario est inégale. Avant de construire encore, la commune peut améliorer les usages du parc en service.', 'Évaluation · Ces usages sont hypothétiques, même pour une commune réelle.',
    o('Adapter les aménagements', 'Reconfigurer un équipement pour accueillir davantage d’activités.', { investment: .7, services: 2 }, 'Un investissement supplémentaire dans l’existant.'),
    o('Renforcer la médiation', 'Financer l’accès des publics qui utilisent peu les équipements.', { operating: .1, cohesion: 2 }, 'Les coûts deviennent récurrents.'),
    o('Redistribuer les créneaux', 'Faire plus de place aux besoins moins servis.', { cohesion: 1, trust: -1 }, 'Les usagers habituels doivent partager davantage.')),
  b('Patrimoine en retard', 'Les petites réparations forment un grand retard', 'Le service technique présente la liste des interventions différées. Une opération groupée coûte aujourd’hui ; traiter seulement les urgences laisse les autres défauts vieillir.', 'Patrimoine · Le niveau d’usure dépend aussi des choix précédents.',
    o('Résorber un lot de retard', 'Réhabiliter une série de composants déjà identifiés.', { investment: 1.8, assets: 3 }, 'Moins de marge pour les derniers projets.'),
    o('Renforcer les réparations courantes', 'Pérenniser une capacité supplémentaire de maintenance.', { operating: .2, assets: 1 }, 'Le rattrapage restera progressif.'),
    o('Se limiter aux urgences', 'Maintenir les équipes et le calendrier actuels.', { assets: -1 }, 'Une partie du retard sera transmise.')),
  b('Tarif d’un service', 'Faire payer l’usage ou le budget commun ?', 'Un service municipal facultatif est partiellement financé par ses usagers. Le tarif peut couvrir davantage de coûts, mais l’accès doit rester intelligible et accessible.', 'Tarification · Hypothèse de rendement ; aucune facture individuelle n’est simulée.',
    o('Relever le tarif moyen', 'Augmenter les recettes du service dans le scénario.', { revenue: .2, cohesion: -1, trust: -1 }, 'Les usagers contribuent davantage.'),
    o('Élargir les tarifs solidaires', 'Réduire la recette pour faciliter certains usages.', { revenue: -.2, cohesion: 2 }, 'Le budget communal compense davantage.'),
    o('Conserver la grille', 'Maintenir tarifs et recettes au niveau actuel.', {}, 'Les difficultés d’accès existantes demeurent.')),
  b('Cofinancement limité', 'Une dernière enveloppe, un seul projet', 'Un partenaire propose une aide pour l’accessibilité d’un bâtiment. Elle réduit le reste à charge sans le supprimer, alors que le mandat entre dans sa dernière phase.', 'Finances · Aide conditionnelle de scénario, non promesse d’un financeur réel.',
    o('Financer le projet aidé', 'Engager un aménagement complet avec une participation extérieure.', { investment: 1.5, grants: .5, services: 2, assets: 1 }, 'La commune doit financer sa part.'),
    o('Traiter un accès prioritaire', 'Financer seule un chantier plus limité.', { investment: .4, services: 1 }, 'Le reste du bâtiment attendra.'),
    o('Décliner l’enveloppe', 'Garder les ressources pour les engagements en cours.', {}, 'L’aide proposée n’est pas conservée.')),
  b('Accessibilité', 'Un service proche mais encore difficile d’accès', 'Un cheminement et un accueil compliquent les démarches de certains habitants. Adapter le lieu rend l’accès plus autonome ; renforcer l’aide humaine répond à un autre besoin.', 'Accessibilité · Le jeu ne certifie pas la conformité réelle d’un bâtiment.',
    o('Adapter le parcours complet', 'Améliorer cheminement, entrée et accueil.', { investment: .9, services: 2, cohesion: 1, area: 'centre' }, 'Le budget est mobilisé sur un site.'),
    o('Renforcer l’accompagnement', 'Ajouter une aide municipale sur les créneaux prioritaires.', { operating: .1, cohesion: 1 }, 'L’autonomie d’accès ne progresse pas autant.'),
    o('Réorienter vers un site accessible', 'Proposer le service dans un local existant adapté.', { services: -1 }, 'Certains habitants doivent se déplacer davantage.')),
  b('Dette et réserve', 'Une marge peut rester disponible', 'Après plusieurs années, les finances portent votre stratégie. Un remboursement réduit la dette ; garder des ressources permet de répondre à un besoin imprévu.', 'Finances · La possibilité de rembourser dépend de l’épargne disponible et de la dette restante.',
    o('Réduire le capital restant', 'Affecter une marge de ressources propres au désendettement.', { repayment: 1 }, 'La réserve de précaution est moins élevée.'),
    o('Conforter une recette durable', 'Ajuster modestement la ressource fiscale du modèle.', { revenue: .3, trust: -1 }, 'Les contribuables financent davantage la marge.'),
    o('Garder les moyens disponibles', 'Ne pas ajouter d’engagement à la trajectoire actuelle.', {}, 'Pas d’accélération du désendettement.')),
  b('Fin du programme', 'Un dernier projet peut dépasser le mandat', 'Une amélioration utile pourrait être lancée maintenant, mais sa livraison interviendrait après votre dernière année. Son financement et ses coûts doivent rester visibles.', 'Programmation · Les engagements futurs apparaîtront dans l’héritage.',
    o('Engager une rénovation longue', 'Préparer un bâtiment plus sobre avec deux ans de travaux.', { investment: 1.6 }, 'Le prochain mandat recevra le chantier.', later(2, 'La rénovation engagée en fin de mandat est livrée après transmission.', { assets: 3, resilience: 2, operating: -.2 })),
    o('Préférer une réparation immédiate', 'Traiter une usure précise dans le parc existant.', { investment: .5, assets: 1 }, 'La transformation énergétique est limitée.'),
    o('Laisser le projet à arbitrer', 'Transmettre les besoins sans engager les travaux.', {}, 'Aucune amélioration supplémentaire n’est programmée.')),
  // Année 6 : transmettre.
  b('Dernières livraisons', 'Ouvrir dans de bonnes conditions', 'Les bâtiments actuellement en service demandent une prise en main. La dernière année peut améliorer leur utilisation sans promettre des chantiers qui n’ont pas été engagés.', 'Exploitation · Seuls les projets effectivement financés ont leur livraison propre.',
    o('Adapter les derniers usages', 'Compléter les aménagements du parc ouvert.', { investment: .5, services: 1, assets: 1 }, 'Une dépense s’ajoute au budget final.'),
    o('Pérenniser l’accompagnement', 'Renforcer les équipes pour les usages les plus complexes.', { operating: .1, services: 1, cohesion: 1 }, 'La charge sera transmise.'),
    o('Ouvrir avec les moyens prévus', 'Conserver l’organisation déjà financée.', {}, 'Pas d’accompagnement supplémentaire.')),
  b('Urgences résiduelles', 'Ce qui ne peut plus attendre', 'Des défauts restent signalés dans le patrimoine. Une remise en état rapide évite de transmettre toute la liste, mais consomme les moyens du dernier exercice.', 'Patrimoine · Les urgences sont fictives et ne qualifient aucun bâtiment réel.',
    o('Traiter un lot d’urgences', 'Réparer les composants les plus dégradés.', { investment: 1.2, assets: 2 }, 'Moins de marge au dernier budget.'),
    o('Limiter les usages fragiles', 'Réorganiser les activités et les petites réparations existantes.', { services: -1 }, 'Une partie de l’équipement reste moins accessible.'),
    o('Reporter les interventions', 'Transmettre le retard avec le diagnostic de fin de mandat.', { assets: -2, trust: -1 }, 'Le prochain exécutif reprend les défauts.')),
  b('Charges pérennes', 'La dépense de demain se décide aujourd’hui', 'Plusieurs services demandent un renfort durable. Le bénéfice peut être immédiat, mais l’engagement survivra à votre mandat.', 'Finances · Les dépenses récurrentes ne disparaissent pas au bilan final.',
    o('Pérenniser un service prioritaire', 'Ajouter des moyens réguliers à l’accompagnement municipal.', { operating: .2, services: 1, cohesion: 1 }, 'Une charge annuelle est transmise.'),
    o('Réduire le périmètre secondaire', 'Retirer certaines prestations moins prioritaires.', { operating: -.2, services: -1 }, 'Des habitants perdent un service.'),
    o('Maintenir les engagements actuels', 'Transmettre les moyens déjà en place.', {}, 'Les demandes nouvelles ne sont pas financées.')),
  b('Contrat d’entretien', 'Signer pour entretenir, pas seulement réparer', 'Les équipements ont besoin d’un suivi régulier. Un contrat durable stabilise les interventions, tandis que les réparations à la demande conservent plus de souplesse.', 'Commande publique · Les obligations réelles ne sont pas reproduites intégralement dans le jeu.',
    o('Renforcer l’entretien durable', 'Financer une couverture préventive plus régulière.', { operating: .2, assets: 2 }, 'Une charge annuelle supplémentaire.'),
    o('Renouveler le matériel technique', 'Équiper les équipes existantes pour certaines interventions.', { investment: .6, assets: 1 }, 'Pas de capacité humaine supplémentaire.'),
    o('Conserver les interventions actuelles', 'Garder le niveau de service du contrat existant.', {}, 'Pas de protection additionnelle du patrimoine.')),
  b('Après le mandat', 'Engager un chantier que l’on ne verra pas finir ?', 'Un projet d’adaptation pourrait démarrer. Sa livraison et une partie de ses effets appartiendraient au mandat suivant ; les habitants doivent connaître cet horizon.', 'Héritage · Un engagement non livré n’est pas présenté comme un équipement ouvert.',
    o('Lancer l’adaptation du site', 'Financer une transformation dont la livraison demande deux ans.', { investment: 1.8 }, 'Les effets arrivent après le mandat.', later(2, 'L’adaptation engagée avant transmission entre en service.', { resilience: 3, assets: 2, operating: .1, area: 'rives' })),
    o('Préférer une amélioration légère', 'Aménager immédiatement un accès dans le parc existant.', { investment: .4, services: 1 }, 'Le site reste peu transformé.'),
    o('Transmettre le projet sans engagement', 'Laisser le choix et les moyens au prochain exécutif.', {}, 'La transformation n’est pas financée.')),
  b('Marge de transmission', 'Dette réduite ou latitude pour la suite ?', 'La dernière marge disponible peut rembourser du capital, améliorer les équipements ou rester mobilisable après votre départ.', 'Finances · Aucune de ces options n’efface les engagements précédents.',
    o('Accélérer le remboursement', 'Affecter une part des ressources propres au capital.', { repayment: 1.2 }, 'Moins de liquidité pour le prochain budget.'),
    o('Conforter le patrimoine', 'Traiter une dernière tranche de petits travaux.', { investment: .8, assets: 2 }, 'La dette ne baisse pas plus vite.'),
    o('Conserver la marge', 'Laisser la trajectoire et les ressources disponibles en l’état.', {}, 'Pas de nouveau progrès matériel.')),
  b('Héritage municipal', 'Quel dernier engagement assumer ?', 'Votre héritage résulte de six budgets, pas d’un seul geste final. Il reste à décider si vous ajoutez un service, une ressource ou aucun engagement nouveau.', 'Bilan · Les indices mesurent une stratégie de jeu, jamais une intention de vote.',
    o('Conforter l’accès de proximité', 'Transmettre un renfort pérenne d’accueil municipal.', { operating: .2, services: 1, cohesion: 2 }, 'Le prochain mandat devra financer ce service.'),
    o('Conforter les ressources', 'Assumer une dernière hausse modeste des recettes du modèle.', { revenue: .3, trust: -2 }, 'L’effort repose sur les contribuables.'),
    o('Transmettre sans ajout', 'Clore le mandat avec les engagements déjà pris.', {}, 'Les besoins restants figurent dans le bilan.')),
];

const nationalBriefs: Brief[] = [
  // Année 1 : orienter. Périmètre APU consolidé, coordination abstraite.
  b('Assiette fiscale', 'Financer le mandat sans cacher qui contribue', 'Les recettes héritées ne couvrent pas les engagements publics. Une modification fiscale agit sur plusieurs années ; son rendement reste une hypothèse du modèle.', 'Conseil budgétaire · Périmètre APU consolidé, pas seulement budget de l’État.',
    o('Réduire certaines exemptions', 'Élargir modestement l’assiette dans le scénario.', { revenue: 4, trust: -2 }, 'Les contribuables concernés contribuent davantage.'),
    o('Alléger les prélèvements', 'Laisser davantage de ressources aux contribuables.', { revenue: -3, trust: 2 }, 'Le besoin de financement augmente durablement.'),
    o('Maintenir les règles', 'Conserver la fiscalité héritée pour ce premier arbitrage.', {}, 'Aucune ressource nouvelle.')),
  b('Dépenses héritées', 'Tout conserver ou revoir un premier périmètre ?', 'Les dépenses publiques comprennent déjà des engagements durables. Une revue ciblée crée de la marge ; elle peut aussi retirer des prestations utiles.', 'Conseil budgétaire · Les arbitrages supposent une coordination entre administrations.',
    o('Réduire un périmètre secondaire', 'Diminuer un ensemble de dépenses courantes du modèle.', { operating: -4, services: -2 }, 'Des bénéficiaires perdent une prestation.'),
    o('Renforcer les moyens prioritaires', 'Ajouter une enveloppe récurrente aux services sous tension.', { operating: 3, services: 2 }, 'Le déficit est plus élevé chaque année.'),
    o('Conserver les engagements', 'Ne pas modifier le périmètre à ce stade.', {}, 'Le déséquilibre hérité demeure.')),
  b('Services de proximité', 'Un service accessible sans long déplacement', 'Dans le scénario, les espaces ruraux disposent de moins de points d’accueil. Renforcer la présence, aménager les locaux ou mieux organiser les relais produit des résultats différents.', 'Coordination territoriale · Les partenaires publics conservent leurs compétences.',
    o('Renforcer les permanences', 'Financer durablement des capacités de proximité.', { operating: 2, services: 2, cohesion: 1, area: 'rural' }, 'Une dépense récurrente pour plusieurs administrations.'),
    o('Aménager les lieux d’accueil', 'Moderniser des locaux partagés entre acteurs publics.', { investment: 4 }, 'L’amélioration attend les travaux.', later(1, 'Les lieux d’accueil partagés modernisés entrent en service.', { services: 2, assets: 1, area: 'rural' })),
    o('Coordonner les relais actuels', 'Partager les horaires et l’orientation sans budget supplémentaire.', {}, 'La capacité d’accueil reste limitée.')),
  b('Capacités de santé', 'Des équipes ou des équipements ?', 'Les capacités de santé demandent à la fois des professionnels et des installations adaptées. Un achat ne forme pas une équipe ; un renfort courant ne répare pas un bâtiment.', 'Santé · Coordination avec les organismes sociaux et acteurs de soins dans le modèle APU.',
    o('Renforcer les équipes', 'Financer des capacités pérennes de prise en charge.', { operating: 3, services: 2, cohesion: 1 }, 'Une charge durable supplémentaire.'),
    o('Moderniser un parc d’équipements', 'Engager un programme ciblé de rénovation technique.', { investment: 6 }, 'Les capacités progressent plus tard.', later(2, 'Le programme d’équipements de santé entre en service.', { services: 3, assets: 2 })),
    o('Réorganiser les capacités existantes', 'Concentrer les moyens sur les prises en charge prioritaires.', { services: 1, cohesion: -1 }, 'D’autres accès deviennent moins commodes.')),
  b('Éducation', 'Accompagner maintenant ou préparer les capacités ?', 'Les besoins éducatifs dépassent un seul financeur. Accompagnement, bâtiments et formation n’ont pas le même calendrier ni les mêmes responsables.', 'Éducation · Les collectivités restent partenaires du patrimoine scolaire.',
    o('Renforcer l’accompagnement', 'Ajouter des moyens durables au soutien des parcours.', { operating: 2, services: 2 }, 'Le coût revient chaque année.'),
    o('Cofinancer les équipements', 'Coordonner un programme ciblé de modernisation avec les collectivités.', { investment: 5 }, 'Le bénéfice dépend du délai de réalisation.', later(2, 'Le programme éducatif cofinancé est livré.', { assets: 2, services: 2, cohesion: 1 })),
    o('Conserver le programme actuel', 'Stabiliser l’offre et les engagements hérités.', {}, 'Les besoins supplémentaires restent ouverts.')),
  b('Énergie', 'Réduire l’exposition avant le prochain choc', 'Les bassins industriels dépendent de l’énergie et des réseaux. Une transformation demande du temps ; un accompagnement immédiat ne remplace pas les infrastructures.', 'Énergie · La production seule ne détermine pas le prix final payé.',
    o('Investir dans l’efficacité', 'Engager un programme ciblé de réduction des consommations.', { investment: 7 }, 'Pas de protection immédiate contre les prix.', later(2, 'Le programme d’efficacité réduit l’exposition énergétique modélisée.', { resilience: 3, assets: 2, operating: -1, area: 'industrie' })),
    o('Renforcer l’appui technique', 'Financer un accompagnement durable des acteurs exposés.', { operating: 1, resilience: 1 }, 'Peu de transformation physique des installations.'),
    o('Conserver les programmes existants', 'Ne pas ajouter de nouvelle enveloppe énergétique.', {}, 'L’exposition héritée demeure.')),
  b('Investissement public', 'Une première impulsion, avec quel horizon ?', 'Des infrastructures existantes demandent des travaux. Une modernisation promet des gains différés ; l’entretien ciblé améliore plus vite une partie du parc.', 'Investissement · Rendements hypothétiques et financeurs consolidés sans doubles comptes.',
    o('Moderniser un réseau prioritaire', 'Engager une tranche pluriannuelle d’infrastructures.', { investment: 8 }, 'La dette augmente avant le bénéfice.', later(2, 'La tranche de modernisation entre en service.', { assets: 3, services: 2, growth: .0002 })),
    o('Réparer les points fragiles', 'Cibler une intervention plus petite sur le parc existant.', { investment: 3, assets: 1 }, 'Les gains d’usage restent limités.'),
    o('Différer toute nouvelle tranche', 'Terminer les engagements hérités avant d’en lancer.', {}, 'Le programme ne gagne aucune capacité nouvelle.')),
  b('Financement', 'Le déficit engage les budgets suivants', 'Le coût du financement absorbe une partie des moyens publics. Modifier les recettes ou les charges agit sur le besoin d’emprunt, avec des conséquences différentes.', 'Dette · Le coût moyen de financement évolue progressivement dans le modèle.',
    o('Conforter une recette', 'Ajouter une ressource fiscale durable et limitée.', { revenue: 3, trust: -2 }, 'Les contribuables supportent l’effort.'),
    o('Réduire une charge courante', 'Diminuer certains moyens non prioritaires.', { operating: -3, services: -1 }, 'L’offre publique se resserre.'),
    o('Maintenir la trajectoire', 'Financer les engagements en l’état.', {}, 'Le besoin d’emprunt n’est pas corrigé.')),
  b('Clôture budgétaire', 'Le premier budget révèle votre priorité', 'Les premiers choix forment désormais un programme. Ajouter un engagement avant la clôture améliore certains services mais laisse moins de latitude pour les années suivantes.', 'Conseil budgétaire · Une clôture annuelle suit ce neuvième dossier.',
    o('Conforter les services essentiels', 'Ajouter une enveloppe courante ciblée.', { operating: 2, services: 1, cohesion: 1 }, 'La dépense s’installe pour le mandat.'),
    o('Financer un entretien ciblé', 'Traiter une petite série de besoins sur le patrimoine public.', { investment: 3, assets: 1 }, 'Un effort de financement dès cette année.'),
    o('Clore sans nouvel engagement', 'Laisser les programmes décidés suivre leur calendrier.', {}, 'Les demandes nouvelles attendent.')),
  // Année 2 : déployer.
  b('Mise en œuvre fiscale', 'Une règle fiscale doit pouvoir s’appliquer', 'La qualité d’application compte autant que la règle. Simplifier le traitement, améliorer les outils ou conserver les procédures pose des compromis de coût et de capacité.', 'Fiscalité · Aucun rendement de contrôle fiscal automatique n’est supposé.',
    o('Moderniser les outils', 'Investir dans les systèmes de traitement des administrations.', { investment: 3 }, 'Les gains sont différés.', later(1, 'Les outils de traitement fiscal modernisés réduisent certaines charges du modèle.', { operating: -1, services: 1 })),
    o('Renforcer l’accompagnement', 'Financer un appui durable aux usagers des démarches fiscales.', { operating: 1, services: 1, trust: 1 }, 'Une charge publique récurrente.'),
    o('Stabiliser les procédures', 'Conserver les moyens et outils disponibles.', {}, 'Les frictions administratives demeurent.')),
  b('Capacités administratives', 'Des politiques décidées mais des équipes chargées', 'Les administrations mettent en œuvre le programme. Ajouter des tâches sans moyens ralentit certaines démarches ; recruter ou équiper n’agit pas au même rythme.', 'Administration · Le modèle ne confond pas réduction d’effectifs et gain certain de productivité.',
    o('Renforcer les services instructeurs', 'Financer des moyens humains durables.', { operating: 2, services: 2 }, 'La dépense reste après les premiers déploiements.'),
    o('Moderniser les outils de travail', 'Équiper les équipes avant de réorganiser les procédures.', { investment: 4 }, 'L’amélioration attend la prise en main.', later(1, 'Les nouveaux outils administratifs facilitent le traitement des dossiers.', { services: 2, assets: 1 })),
    o('Réduire les démarches secondaires', 'Concentrer les capacités existantes sur les priorités.', { services: 1, trust: -1 }, 'Des demandes deviennent moins bien servies.')),
  b('Rénovation publique', 'Rénover un parc, bâtiment après bâtiment', 'Les bâtiments publics représentent des usages et des consommations très différents. Un programme ciblé peut réduire les charges sans prétendre rénover tout le pays.', 'Patrimoine · Les administrations propriétaires coordonnent leurs interventions.',
    o('Financer une nouvelle tranche', 'Rénover un ensemble ciblé de bâtiments énergivores.', { investment: 6 }, 'Les économies arrivent après les travaux.', later(2, 'La tranche de rénovation publique est livrée.', { assets: 2, resilience: 2, operating: -1 })),
    o('Renforcer l’entretien courant', 'Ajouter des moyens aux interventions préventives.', { operating: 1, assets: 1 }, 'Pas de rénovation thermique complète.'),
    o('Regrouper les usages', 'Concentrer certaines activités dans les locaux occupés.', { operating: -1, services: -1 }, 'Des services deviennent moins proches.')),
  b('Réseau énergétique', 'La production ne suffit pas sans réseau', 'Des usages nouveaux demandent des capacités de réseau. Le soutien public peut accélérer un programme avec les opérateurs, mais ne livre pas les raccordements instantanément.', 'Énergie · Programme coordonné ; aucun pilotage direct de tous les opérateurs n’est supposé.',
    o('Cofinancer une tranche de réseau', 'Engager une participation publique dans le scénario.', { investment: 7 }, 'Les usages attendent la livraison.', later(2, 'La tranche de réseau cofinancée entre en service.', { resilience: 3, assets: 2, area: 'industrie' })),
    o('Renforcer l’ingénierie', 'Financer durablement la préparation des projets.', { operating: 1, resilience: 1 }, 'Les travaux ne sont pas financés par cette seule mesure.'),
    o('Conserver le calendrier prévu', 'Ne pas ajouter de participation nouvelle.', {}, 'Aucune accélération supplémentaire.')),
  b('Industrie', 'Soutenir une transformation, pas seulement une dépense', 'Les bassins industriels demandent un appui pour s’adapter. Un soutien d’investissement agit lentement ; un accompagnement courant coûte moins aujourd’hui mais reste récurrent.', 'Industrie · Résultats hypothétiques, sans garantie de créations d’emplois.',
    o('Cofinancer la transformation', 'Soutenir un programme ciblé d’adaptation productive.', { investment: 5 }, 'Le résultat demande deux années.', later(2, 'Le programme industriel soutenu améliore les capacités du scénario.', { assets: 2, resilience: 2, growth: .0002, area: 'industrie' })),
    o('Renforcer l’appui aux transitions', 'Financer l’accompagnement des parcours professionnels.', { operating: 2, cohesion: 2, area: 'industrie' }, 'La dépense devient durable.'),
    o('Mobiliser les dispositifs existants', 'Orienter les demandes sans nouvel apport financier.', {}, 'Les capacités du programme n’augmentent pas.')),
  b('Formation', 'Les compétences demandent plus qu’une annonce', 'Les reconversions impliquent organismes de formation, régions et employeurs. Le financement public peut améliorer les parcours sans garantir chaque débouché.', 'Formation · Coordination avec les régions et les partenaires concernés.',
    o('Renforcer les parcours', 'Financer un accompagnement durable des transitions.', { operating: 2, cohesion: 2 }, 'Les dépenses se prolongent après la formation initiale.'),
    o('Équiper les lieux de formation', 'Moderniser les supports et installations partagés.', { investment: 3 }, 'Le bénéfice est différé.', later(1, 'Les équipements de formation modernisés deviennent disponibles.', { services: 2, assets: 1, area: 'industrie' })),
    o('Réorienter l’offre actuelle', 'Donner davantage de place aux parcours prioritaires.', { cohesion: 1, trust: -1 }, 'D’autres filières perdent des créneaux.')),
  b('Logement', 'L’accès au logement ne répond pas à un seul levier', 'Les territoires tendus demandent des logements et des services. Les acteurs publics peuvent cofinancer, accompagner ou conserver leurs programmes, avec des délais différents.', 'Logement · Collectivités, bailleurs et opérateurs restent partenaires du modèle.',
    o('Cofinancer une transformation', 'Engager un programme ciblé de remise en usage du bâti.', { investment: 5 }, 'L’offre ne progresse pas immédiatement.', later(2, 'Le programme de logement cofinancé améliore l’accès dans le scénario.', { cohesion: 3, assets: 1, area: 'metropoles' })),
    o('Renforcer l’accompagnement', 'Ajouter des moyens durables pour les ménages en difficulté.', { operating: 2, cohesion: 2 }, 'Pas de capacité bâtie supplémentaire.'),
    o('Conserver les programmes actuels', 'Ne pas ajouter d’enveloppe nouvelle.', {}, 'Les tensions héritées persistent.')),
  b('Disparités territoriales', 'La moyenne nationale cache des distances', 'L’amélioration d’un indicateur national ne garantit pas un accès homogène. Les espaces ruraux demandent des capacités que les pôles plus denses possèdent déjà.', 'Territoires · Les zones de jeu ne sont pas des statistiques sur une région réelle.',
    o('Financer des équipements partagés', 'Cibler un programme d’accès dans les espaces ruraux.', { investment: 4 }, 'L’amélioration prend une année.', later(1, 'Les équipements partagés ruraux ouvrent.', { services: 2, cohesion: 1, area: 'rural' })),
    o('Renforcer les permanences', 'Ajouter des moyens courants d’accompagnement territorial.', { operating: 1, services: 1, cohesion: 1, area: 'rural' }, 'Le fonctionnement est durablement accru.'),
    o('Répartir autrement les moyens', 'Donner la priorité aux zones moins servies dans l’offre existante.', { cohesion: 1, trust: -1 }, 'Des territoires mieux dotés perdent un avantage.')),
  b('Recalage budgétaire', 'Le déploiement a un coût durable', 'Les programmes commencent à consommer leurs moyens. Avant la clôture, une correction peut limiter la trajectoire de dette ou préserver toute l’offre décidée.', 'Conseil budgétaire · Les effets récurrents s’appliquent une fois au budget de chaque exercice.',
    o('Corriger certaines dépenses', 'Réduire une part des charges secondaires du scénario.', { operating: -3, services: -1, trust: -1 }, 'Une partie de l’offre publique se réduit.'),
    o('Renforcer les recettes', 'Assumer une ressource fiscale récurrente complémentaire.', { revenue: 3, trust: -2 }, 'Les contribuables financent la correction.'),
    o('Maintenir le programme', 'Conserver les moyens des politiques déjà engagées.', {}, 'Aucune correction nouvelle du déficit.')),
  // Année 3 : absorber.
  b('Choc économique', 'L’activité ralentit, les demandes augmentent', 'Un ralentissement hypothétique met les revenus et les services sous pression. Une aide temporaire amortit la situation ; l’investissement agit sur un horizon plus long.', 'Scénario · Il ne s’agit pas d’une prévision économique française.',
    o('Déployer un soutien temporaire', 'Renforcer l’accompagnement des acteurs exposés pendant un exercice.', { operating: 4, cohesion: 2 }, 'Un déficit supplémentaire sans investissement.', later(1, 'Le soutien exceptionnel au ralentissement arrive à échéance.', { operating: -4 })),
    o('Accélérer un entretien utile', 'Financer des interventions sur les infrastructures existantes.', { investment: 5, assets: 2 }, 'L’aide immédiate aux revenus est limitée.'),
    o('Redéployer les moyens existants', 'Concentrer l’effort sur les besoins prioritaires.', { cohesion: -1 }, 'La capacité totale d’aide ne progresse pas.')),
  b('Soutien temporaire', 'Protéger une année sans promettre toujours', 'Une aide ciblée peut répondre à la phase difficile. Sa date de fin est aussi une décision : une dépense temporaire ne doit pas devenir permanente par oubli.', 'Finances · L’extinction de cette aide est enregistrée dès sa création.',
    o('Financer un appui exceptionnel', 'Ajouter une protection limitée à l’exercice.', { operating: 3, cohesion: 2, trust: 1 }, 'Aucune ressource durable pour ses bénéficiaires.', later(1, 'L’appui exceptionnel aux ménages s’éteint comme prévu.', { operating: -3 })),
    o('Renforcer l’appui permanent', 'Pérenniser une enveloppe plus modeste de proximité.', { operating: 1, cohesion: 1 }, 'Le coût revient après la crise.'),
    o('Mobiliser l’offre actuelle', 'Orienter les demandes vers les dispositifs existants.', {}, 'Pas d’enveloppe additionnelle face au choc.')),
  b('Énergie en crise', 'Protéger la facture ou réduire l’exposition ?', 'La tension énergétique frappe inégalement les acteurs. Soutenir les charges aide cette année ; améliorer les installations change surtout les suivantes.', 'Énergie · Les effets restent ceux d’un scénario, pas une estimation tarifaire.',
    o('Financer une aide ciblée', 'Soutenir temporairement les usages les plus exposés.', { operating: 4, cohesion: 2, area: 'industrie' }, 'L’exposition technique reste entière.', later(1, 'L’aide énergétique exceptionnelle prend fin.', { operating: -4 })),
    o('Accélérer l’efficacité énergétique', 'Engager une tranche rapide de modernisation.', { investment: 6 }, 'La crise présente reste difficile.', later(1, 'La tranche rapide d’efficacité énergétique est livrée.', { resilience: 3, operating: -1, area: 'industrie' })),
    o('Adapter les usages', 'Accompagner les changements avec les moyens existants.', { resilience: 1, cohesion: -1 }, 'Les acteurs doivent absorber davantage le choc.')),
  b('Services sous tension', 'Quand la file d’attente s’allonge', 'La crise augmente la demande de services. Renforcer durablement les capacités ou réorganiser les priorités n’a pas le même effet sur le budget à venir.', 'Services publics · Les capacités humaines et matérielles restent distinctes.',
    o('Ajouter des moyens durables', 'Pérenniser une capacité de prise en charge supplémentaire.', { operating: 3, services: 2 }, 'Les charges survivent à la crise.'),
    o('Adapter les lieux existants', 'Financer des aménagements pour faciliter l’accueil.', { investment: 3, services: 1, assets: 1 }, 'Les effectifs restent les mêmes.'),
    o('Prioriser les demandes urgentes', 'Réaffecter les capacités disponibles.', { services: 1, cohesion: -1 }, 'D’autres demandes attendent davantage.')),
  b('Recettes dégradées', 'Les recettes ne suivent pas les besoins', 'Dans le scénario, la conjoncture rend l’équilibre plus difficile. Une mesure récurrente peut compenser une partie de la pression, mais son effort dépasse la crise.', 'Fiscalité · Rendement fixe de jeu, distinct des variations conjoncturelles du moteur.',
    o('Conforter l’assiette', 'Ajouter une ressource fiscale ciblée au programme.', { revenue: 4, trust: -2 }, 'La contribution reste après le ralentissement.'),
    o('Réduire des prestations secondaires', 'Corriger une part des dépenses courantes.', { operating: -3, services: -1, cohesion: -1 }, 'Des besoins deviennent moins bien couverts.'),
    o('Laisser le financement absorber le choc', 'Conserver les recettes et les services décidés.', {}, 'Le déficit ne reçoit pas de correction supplémentaire.')),
  b('Approvisionnements', 'La disponibilité devient une question stratégique', 'Des approvisionnements essentiels connaissent des tensions dans le scénario. Une capacité publique de préparation coûte même quand la crise s’éloigne.', 'Résilience · Aucun stock physique réel n’est décrit par les indices.',
    o('Moderniser les capacités logistiques', 'Investir dans des installations stratégiques ciblées.', { investment: 5 }, 'La capacité arrive après un délai.', later(1, 'Les capacités logistiques modernisées améliorent la résilience.', { resilience: 3, assets: 1 })),
    o('Renforcer la veille et la coordination', 'Financer durablement l’anticipation entre partenaires.', { operating: 1, resilience: 1 }, 'Peu de capacité matérielle supplémentaire.'),
    o('Mobiliser les réseaux actuels', 'Partager les informations et prioriser les usages existants.', { resilience: 1, services: -1 }, 'Certains usages sont moins bien approvisionnés.')),
  b('Adaptation climatique', 'Le littoral ne peut pas attendre tous les budgets', 'Les territoires littoraux sont exposés dans le scénario. Les collectivités et partenaires peuvent adapter les équipements ou renforcer la préparation immédiate.', 'Climat · Les zones et indices ne valent pas cartographie réelle du risque.',
    o('Cofinancer l’adaptation', 'Engager une tranche de protection et d’adaptation des infrastructures.', { investment: 7 }, 'L’effet complet demande deux ans.', later(2, 'La tranche d’adaptation littorale est livrée.', { resilience: 3, assets: 2, area: 'littoraux' })),
    o('Renforcer la préparation', 'Financer durablement l’organisation territoriale de prévention.', { operating: 1, resilience: 1, cohesion: 1, area: 'littoraux' }, 'Le patrimoine reste exposé.'),
    o('Prioriser les plans existants', 'Réorganiser la prévention sans nouvelle enveloppe.', {}, 'Aucune capacité physique supplémentaire.')),
  b('Financement de crise', 'Un emprunt aujourd’hui, des intérêts demain', 'Les engagements de crise augmentent les besoins de financement. Une correction immédiate a un coût social ; attendre conserve les services mais transmet la pression.', 'Dette · Le stock de dette et son taux moyen évoluent selon les règles annuelles.',
    o('Corriger les charges courantes', 'Réduire des dépenses non prioritaires dans le modèle.', { operating: -4, services: -2 }, 'Une partie de l’offre publique recule en période difficile.'),
    o('Assumer une recette supplémentaire', 'Renforcer durablement les ressources fiscales.', { revenue: 3, trust: -2 }, 'Les contribuables financent une part de la crise.'),
    o('Conserver les moyens mobilisés', 'Financer les engagements sans nouvelle correction.', {}, 'Le besoin d’emprunt reste plus élevé.')),
  b('Sortie de crise', 'Préparer la suite sans effacer les fragilités', 'La phase la plus tendue du scénario passe. Les aides temporaires suivront leur échéance, mais les services et le patrimoine conservent les conséquences de la crise.', 'Conseil budgétaire · Une reprise ne supprime pas les engagements déjà pris.',
    o('Réparer les capacités fragilisées', 'Financer une tranche ciblée de remise en état.', { investment: 4, assets: 2 }, 'Le financement reste nécessaire malgré la reprise.'),
    o('Pérenniser un appui ciblé', 'Ajouter une protection de proximité plus modeste et durable.', { operating: 1, cohesion: 1 }, 'Une charge se poursuit après les aides exceptionnelles.'),
    o('Revenir au programme engagé', 'Laisser les dispositifs temporaires suivre leur fin prévue.', {}, 'Pas de soutien additionnel à la sortie de crise.')),
  // Année 4 : corriger.
  b('Livraisons', 'Un projet livré doit devenir un service utile', 'Les programmes arrivés à maturité réclament une prise en main. Le suivi concerne uniquement les investissements financés ; les projets refusés ne deviennent pas des réalisations.', 'Maîtrise d’ouvrage · Les livraisons propres à chaque engagement restent dans le journal.',
    o('Financer l’adaptation des usages', 'Compléter les aménagements des installations en service.', { investment: 3, services: 1, assets: 1 }, 'Une dépense additionnelle après les travaux.'),
    o('Renforcer l’exploitation', 'Ajouter des moyens courants pour les équipements ouverts.', { operating: 1, services: 1 }, 'La charge devient pérenne.'),
    o('Conserver les moyens prévus', 'Faire fonctionner le parc avec les budgets déjà votés.', {}, 'Les difficultés de prise en main restent plus lentes à corriger.')),
  b('Productivité publique', 'Un outil neuf ne change pas seul l’organisation', 'Les investissements peuvent faciliter le travail, mais leur appropriation demande des choix d’organisation. Les gains du modèle restent modestes et incertains dans le monde réel.', 'Évaluation · Aucun rendement macroéconomique universel n’est affirmé.',
    o('Accompagner les nouvelles pratiques', 'Financer un appui durable à la transformation des services.', { operating: 1 }, 'Le coût précède le bénéfice.', later(1, 'L’accompagnement améliore l’usage des outils publics.', { services: 2, growth: .0001 })),
    o('Simplifier les organisations', 'Réduire certaines tâches et leurs moyens récurrents.', { operating: -2, services: -1 }, 'Des fonctions secondaires sont abandonnées.'),
    o('Stabiliser les méthodes', 'Laisser les équipes consolider les usages actuels.', {}, 'Pas de gain supplémentaire financé.')),
  b('Taux de financement', 'Les intérêts prennent une place durable', 'Le renouvellement de la dette diffuse progressivement les conditions de financement. Les moyens utilisés pour les intérêts ne financent pas les services ou l’investissement.', 'Finances · Le scénario ne prétend pas prévoir les taux de marché.',
    o('Conforter les recettes', 'Réduire une part du besoin de financement par une ressource durable.', { revenue: 3, trust: -2 }, 'Les contribuables supportent la correction.'),
    o('Réduire les charges secondaires', 'Limiter le déficit par un effort sur la dépense courante.', { operating: -3, services: -1 }, 'L’offre publique se resserre.'),
    o('Préserver les engagements', 'Maintenir le programme malgré le poids du financement.', {}, 'Les intérêts conservent leur pression sur la marge.')),
  b('Correction graduelle', 'Corriger sans tout remettre en cause', 'Une correction modérée peut réduire le déficit sans annuler les investissements passés. Son effort reste visible, même s’il est étalé.', 'Conseil budgétaire · Les dépenses d’investissement déjà engagées ne sont pas annulées.',
    o('Corriger progressivement les charges', 'Réduire un périmètre limité de dépenses courantes.', { operating: -2, services: -1 }, 'Certains services disposent de moins de moyens.'),
    o('Partager l’effort par les recettes', 'Ajouter une ressource fiscale modeste et durable.', { revenue: 2, trust: -1 }, 'L’effort concerne les contribuables.'),
    o('Ne pas ajouter de correction', 'Conserver les recettes et les moyens actuels.', {}, 'La trajectoire ne s’améliore pas par ce dossier.')),
  b('Accès territorial', 'Les zones moins denses attendent encore', 'Certains gains nationaux restent éloignés des espaces ruraux. Ajouter de la capacité locale améliore la proximité sans résoudre tous les écarts territoriaux.', 'Territoires · Arbitrage coordonné avec les acteurs locaux, pas réaffectation autoritaire générale.',
    o('Cofinancer des lieux partagés', 'Aménager une nouvelle tranche d’équipements de proximité.', { investment: 4 }, 'Les usagers attendent une année.', later(1, 'La nouvelle tranche de lieux partagés ruraux ouvre.', { services: 2, cohesion: 1, area: 'rural' })),
    o('Renforcer les équipes mobiles', 'Financer durablement un accompagnement de proximité.', { operating: 1, services: 1, cohesion: 1, area: 'rural' }, 'Une charge récurrente supplémentaire.'),
    o('Partager les créneaux existants', 'Réorienter l’offre vers les zones moins servies.', { cohesion: 1, trust: -1 }, 'D’autres lieux disposent de moins de créneaux.')),
  b('Entretien national', 'Le patrimoine vieillit pendant les nouveaux projets', 'Les infrastructures héritées continuent de nécessiter de l’entretien. Investir dans de nouvelles capacités ne dispense pas de préserver celles qui servent déjà.', 'Patrimoine · Les administrations propriétaires restent responsables de leurs équipements.',
    o('Réhabiliter une tranche prioritaire', 'Financer le renouvellement de composants dégradés.', { investment: 6, assets: 3 }, 'Moins de marge pour un nouveau programme.'),
    o('Renforcer la prévention', 'Pérenniser les moyens d’entretien courant.', { operating: 1, assets: 1, resilience: 1 }, 'Les dépenses reviennent chaque année.'),
    o('Se limiter au programme actuel', 'Conserver les interventions déjà financées.', { assets: -1 }, 'Une partie de l’usure n’est pas rattrapée.')),
  b('Recherche', 'Investir au-delà de l’horizon du mandat', 'La recherche prépare des capacités dont le résultat dépasse souvent le calendrier politique. Un engagement peut rester pertinent sans devenir immédiatement un gain de croissance.', 'Recherche · Aucun brevet ni découverte ne découle automatiquement du financement.',
    o('Moderniser les équipements', 'Engager une tranche de capacités scientifiques partagées.', { investment: 5 }, 'La livraison dépasse le mandat.', later(2, 'Les équipements scientifiques engagés en fin de mandat entrent en service.', { assets: 2, resilience: 1, growth: .0001 })),
    o('Conforter les moyens récurrents', 'Financer durablement les activités de recherche du scénario.', { operating: 2, resilience: 1 }, 'Le rendement n’est pas immédiat ni garanti.'),
    o('Conserver les programmes engagés', 'Stabiliser les moyens sans nouvelle enveloppe.', {}, 'Pas de capacité supplémentaire financée.')),
  b('Engagements sociaux', 'Une protection durable a un financement durable', 'La demande de protection reste forte après la crise. L’amélioration peut être ciblée, financée par une recette ou différée, avec des conséquences différentes.', 'Protection sociale · Organismes sociaux et État sont consolidés dans le périmètre du modèle.',
    o('Renforcer une protection ciblée', 'Ajouter une enveloppe récurrente d’accompagnement.', { operating: 2, cohesion: 2 }, 'Le déficit augmente durablement.'),
    o('Conforter le financement social', 'Ajouter une recette durable au périmètre consolidé.', { revenue: 2, trust: -1 }, 'Les contributeurs financent davantage le système.'),
    o('Maintenir la couverture actuelle', 'Ne pas ajouter d’engagement social à ce stade.', {}, 'Les besoins supplémentaires restent sans réponse.')),
  b('Programmation finale', 'Tout ne sera pas livré avant la fin', 'Un dernier programme peut renforcer la résilience future. Le laisser en préparation préserve les ressources mais transmet un besoin sans financement.', 'Programmation · Les engagements non livrés restent visibles dans le bilan.',
    o('Engager une adaptation longue', 'Financer des infrastructures dont les travaux durent deux ans.', { investment: 6 }, 'Le prochain mandat recevra la livraison.', later(2, 'Le programme d’adaptation de fin de mandat est livré.', { resilience: 3, assets: 2 })),
    o('Préférer une intervention immédiate', 'Réparer une tranche limitée du patrimoine existant.', { investment: 2, assets: 1 }, 'Peu de transformation structurelle.'),
    o('Transmettre le programme à arbitrer', 'Conserver les moyens sans lancer les travaux.', {}, 'Le programme n’est pas financé.')),
  // Année 5 : transmettre.
  b('Fin des aides', 'Ne pas prolonger par habitude', 'Les aides exceptionnelles ont leurs échéances propres. Une nouvelle prolongation serait un choix explicite, distinct de la fin des dispositifs précédents.', 'Finances · Aucune aide non accordée auparavant n’est retranchée par ce dossier.',
    o('Créer un dernier appui temporaire', 'Financer un soutien ciblé pour le dernier exercice.', { operating: 2, cohesion: 1 }, 'Le besoin pourrait rester après sa fin.', later(1, 'Le dernier appui temporaire arrive à son terme après le mandat.', { operating: -2 })),
    o('Pérenniser un appui plus petit', 'Conserver une protection récurrente ciblée.', { operating: 1, cohesion: 1 }, 'La dépense est transmise au prochain mandat.'),
    o('Respecter les échéances prévues', 'Ne pas ajouter de nouvel appui aux dispositifs décidés.', {}, 'Certains besoins restent après les aides.')),
  b('Engagements en cours', 'Les annonces doivent devenir des engagements lisibles', 'Des programmes peuvent être livrés, encore en cours ou avoir été refusés. La transmission doit distinguer leurs états et préserver les obligations déjà prises.', 'Maîtrise d’ouvrage · Cette décision de suivi ne livre aucun projet à elle seule.',
    o('Renforcer le suivi des programmes', 'Financer une capacité durable de pilotage et d’évaluation.', { operating: 1, assets: 1 }, 'Une charge supplémentaire pour superviser les engagements.'),
    o('Améliorer les outils de suivi', 'Moderniser les systèmes de suivi des équipements publics.', { investment: 2, assets: 1 }, 'Un coût additionnel pour une amélioration peu visible.'),
    o('Transmettre le suivi existant', 'Conserver les outils et responsabilités actuels.', {}, 'Pas de capacité supplémentaire de contrôle.')),
  b('Services essentiels', 'Quelle continuité pour le quotidien ?', 'Les services publics restent nécessaires après le dernier bilan. Renforcer leurs moyens, adapter leurs lieux ou conserver le programme engage des héritages différents.', 'Services publics · Le score ne décrit pas une préférence électorale.',
    o('Conforter les équipes de proximité', 'Pérenniser des moyens supplémentaires d’accueil.', { operating: 2, services: 2 }, 'Le financement devra continuer après le mandat.'),
    o('Adapter les installations existantes', 'Financer une intervention immédiate et limitée.', { investment: 3, assets: 1, services: 1 }, 'Pas de moyen humain supplémentaire.'),
    o('Maintenir les capacités actuelles', 'Transmettre les moyens déjà financés.', {}, 'Les manques restants demeurent au bilan.')),
  b('Infrastructures', 'Transmettre un réseau entretenu', 'Le parc public garde l’empreinte des choix passés. Une dernière tranche d’entretien améliore sa condition ; garder la marge laisse plus de latitude budgétaire.', 'Patrimoine · Les effets sont des indices de jeu et non des audits d’ouvrages réels.',
    o('Réhabiliter une tranche du parc', 'Financer les composants les plus dégradés.', { investment: 5, assets: 2, resilience: 1 }, 'La dette reçoit un nouvel effort de financement.'),
    o('Pérenniser l’entretien préventif', 'Ajouter des moyens réguliers de maintenance.', { operating: 1, assets: 1 }, 'Une charge annuelle est transmise.'),
    o('Conserver le programme existant', 'Ne pas ajouter de nouvelle tranche.', {}, 'Le retard résiduel n’est pas réduit.')),
  b('Résilience', 'Préparer un choc que l’on ne connaîtra pas', 'Une capacité de prévention est utile même sans crise visible. Elle doit pourtant être financée aujourd’hui, avec un bénéfice qui n’a pas de date certaine.', 'Résilience · Les indices ne constituent pas une probabilité réelle de catastrophe.',
    o('Renforcer les équipements de prévention', 'Financer une tranche courte de modernisation.', { investment: 4, resilience: 2, assets: 1 }, 'Un financement supplémentaire au dernier budget.'),
    o('Pérenniser la préparation', 'Ajouter des moyens durables d’organisation territoriale.', { operating: 1, resilience: 1, cohesion: 1 }, 'La dépense reste même en l’absence de choc.'),
    o('Garder les capacités actuelles', 'Transmettre les programmes déjà en place.', {}, 'Pas de protection additionnelle.')),
  b('Trajectoire de recettes', 'Une dernière décision fiscale survit au mandat', 'Les recettes du prochain exercice dépendront aussi de votre dernier arbitrage. Alléger les prélèvements, les conforter ou les stabiliser modifie la marge transmise.', 'Fiscalité · Les rendements sont des paramètres de simulation, pas des chiffrages officiels.',
    o('Conforter la ressource', 'Ajouter une recette fiscale durable limitée.', { revenue: 3, trust: -2 }, 'La contribution des ménages ou entreprises concernés augmente.'),
    o('Alléger la contribution', 'Réduire une part des recettes récurrentes.', { revenue: -2, trust: 2 }, 'Le prochain budget dispose de moins de moyens.'),
    o('Stabiliser les recettes', 'Transmettre les règles déjà décidées.', {}, 'Pas de marge fiscale supplémentaire.')),
  b('Charge de dette', 'Réduire le déficit ne suffit pas à effacer la dette', 'La dette reflète les déficits passés et les règles de financement du modèle. Une correction finale améliore les flux sans annuler le stock hérité.', 'Dette · Les comptes distinguent un flux annuel de déficit et un stock de dette.',
    o('Réduire les charges secondaires', 'Corriger durablement une part de la dépense courante.', { operating: -3, services: -1 }, 'Certains services disposent de moins de moyens.'),
    o('Conforter une recette durable', 'Réduire le besoin de financement par les prélèvements.', { revenue: 2, trust: -1 }, 'L’effort repose sur les contribuables.'),
    o('Maintenir les engagements', 'Conserver la trajectoire de recettes et de dépenses.', {}, 'Pas de réduction additionnelle du besoin de financement.')),
  b('Capacité future', 'Laisser des moyens ou un chantier engagé ?', 'Un investissement pourrait améliorer les capacités après votre départ. Sa pertinence doit être jugée avec son délai et ses coûts, pas comme une réalisation déjà acquise.', 'Héritage · Les projets au-delà du mandat restent des engagements simulés.',
    o('Engager une capacité future', 'Financer un programme dont la livraison demande deux ans.', { investment: 6 }, 'Les résultats appartiennent au mandat suivant.', later(2, 'La capacité publique engagée avant transmission entre en service.', { assets: 2, services: 2, operating: 1 })),
    o('Réparer un besoin immédiat', 'Financer une tranche limitée sur l’existant.', { investment: 2, assets: 1 }, 'La capacité structurelle progresse peu.'),
    o('Garder le projet à arbitrer', 'Laisser au prochain exécutif le choix et le financement.', {}, 'Aucune nouvelle capacité n’est engagée.')),
  b('Héritage national', 'Quel dernier choix assumer devant le bilan ?', 'Votre trajectoire rassemble quarante-cinq décisions, cinq budgets et leurs effets différés. La dernière décision ne remplace ni les services rendus ni la dette transmise.', 'Bilan · Résultat de simulation, jamais prévision économique ou électorale.',
    o('Conforter la cohésion', 'Transmettre un renfort pérenne d’accompagnement.', { operating: 2, cohesion: 2, services: 1 }, 'Le prochain mandat devra le financer.'),
    o('Conforter les ressources futures', 'Assumer une dernière ressource fiscale récurrente.', { revenue: 3, trust: -2 }, 'Les contributeurs supportent l’effort.'),
    o('Clore sans nouvel engagement', 'Présenter le bilan et les besoins restants en l’état.', {}, 'Pas d’amélioration supplémentaire au dernier dossier.')),
];

const metricNames: Record<string, string> = { services: 'Services', cohesion: 'Cohésion', resilience: 'Résilience', trust: 'Confiance', assets: 'Patrimoine' };
const money = (value: number, unit: string) => `${Math.abs(value).toLocaleString('fr-FR', { maximumFractionDigits: 2 })} ${unit}`;
export function campaignCost(effect: Effect, delayed: Choice['delayed'], unit: string): string {
  const parts: string[] = [];
  if (effect.investment) parts.push(`${money(effect.investment, unit)} d’investissement`);
  if (effect.grants) parts.push(`${money(effect.grants, unit)} de subvention`);
  if (effect.repayment) parts.push(`${money(effect.repayment, unit)} de remboursement`);
  if (effect.operating) parts.push(`${effect.operating > 0 ? '+' : '−'}${money(effect.operating, unit)}/an de charges`);
  if (effect.revenue) parts.push(`${effect.revenue > 0 ? '+' : '−'}${money(effect.revenue, unit)}/an de recettes`);
  if (delayed?.effect.operating) parts.push(`puis ${delayed.effect.operating > 0 ? '+' : '−'}${money(delayed.effect.operating, unit)}/an de charges`);
  if (delayed?.effect.revenue) parts.push(`puis ${delayed.effect.revenue > 0 ? '+' : '−'}${money(delayed.effect.revenue, unit)}/an de recettes dans ${delayed.after} an${delayed.after > 1 ? 's' : ''}`);
  return parts.join(' · ') || 'Aucun budget supplémentaire';
}
function benefit(option: Option): string {
  const values = Object.entries(option.effect).filter(([key, value]) => key in metricNames && typeof value === 'number' && value > 0);
  if (values.length) return values.slice(0, 2).map(([key, value]) => `${metricNames[key]} +${value}`).join(' · ');
  if (option.delayed && Object.entries(option.delayed.effect).some(([key, value]) => key in metricNames && typeof value === 'number' && value > 0)) return `Effets dans ${option.delayed.after} an${option.delayed.after > 1 ? 's' : ''}`;
  if ((option.effect.revenue ?? 0) > 0 || (option.effect.operating ?? 0) < 0) return 'Marge annuelle améliorée';
  if ((option.effect.repayment ?? 0) > 0) return 'Dette et intérêts futurs réduits';
  return 'Moyens financiers préservés';
}
function compile(briefs: Brief[], mode: Mode): Dossier[] {
  const prefix = mode === 'municipal' ? 'm' : 'n';
  const unit = mode === 'municipal' ? 'M€' : 'Md€';
  return briefs.map(({ options, ...brief }, index) => ({ ...brief, choices: options.map((option, rank) => ({
    id: `${prefix}${String(index + 1).padStart(2, '0')}${String.fromCharCode(97 + rank)}`,
    title: option.title, description: option.description, effect: { ...option.effect },
    cost: campaignCost(option.effect, option.delayed, unit), benefit: benefit(option), sacrifice: option.sacrifice,
    ...(option.delayed ? { delayed: { ...option.delayed, effect: { ...option.delayed.effect } } } : {}),
  })) }));
}

/** Fresh objects prevent a city adapter or test from mutating the canonical content. */
export function longDossiers(mode: Mode): Dossier[] {
  return compile(mode === 'municipal' ? municipalBriefs : nationalBriefs, mode);
}

export const LONG_CALENDARS: Record<Mode, readonly number[]> = {
  municipal: [8, 8, 8, 7, 7, 7], national: [9, 9, 9, 9, 9],
};

/** Optional contextual cues. Indexes are zero-based dossier positions, not years.
 * These cues never grant effects or claim a project exists if its choice was not taken.
 * Delivery itself remains exclusively the engine's responsibility. */
export type CampaignThread = { id: string; launchChoice: string; followUps: readonly number[]; underway: string; absent: string };
export const CAMPAIGN_THREADS: Record<Mode, readonly CampaignThread[]> = {
  municipal: [
    { id: 'ecoles', launchChoice: 'm01a', followUps: [8, 9, 22, 24, 38], underway: 'Votre rénovation scolaire fait partie des engagements à suivre.', absent: 'Vous n’avez pas engagé la rénovation scolaire initiale ; les besoins du parc restent à traiter.' },
    { id: 'energie-batiments', launchChoice: 'm05a', followUps: [18, 24, 25, 32], underway: 'Le premier lot énergétique engagé reste inscrit dans votre trajectoire.', absent: 'Le premier lot de rénovation énergétique n’a pas été lancé.' },
    { id: 'petite-enfance', launchChoice: 'm11a', followUps: [24, 29, 31, 40], underway: 'L’extension de petite enfance comporte des charges après livraison.', absent: 'Sans extension engagée, l’offre de garde repose sur le parc existant.' },
    { id: 'fraicheur', launchChoice: 'm17a', followUps: [17, 28, 31, 42], underway: 'Vos îlots de fraîcheur suivent leur calendrier propre.', absent: 'Les îlots de fraîcheur initiaux n’ont pas été financés.' },
    { id: 'renovation-tardive', launchChoice: 'm38a', followUps: [38, 40, 44], underway: 'Votre rénovation longue doit être transmise avec sa livraison après mandat.', absent: 'Aucune rénovation longue n’a été ajoutée au programme de fin de mandat.' },
  ],
  national: [
    { id: 'sante', launchChoice: 'n04b', followUps: [12, 21, 27, 38], underway: 'Votre programme d’équipements de santé figure parmi les engagements à suivre.', absent: 'Le programme initial d’équipements de santé n’a pas été engagé.' },
    { id: 'efficacite-energie', launchChoice: 'n06a', followUps: [12, 20, 28, 40], underway: 'L’efficacité énergétique financée contribue selon sa livraison à la résilience du scénario.', absent: 'Le programme initial d’efficacité énergétique n’a pas été financé.' },
    { id: 'infrastructures', launchChoice: 'n07a', followUps: [27, 28, 32, 39], underway: 'La modernisation du réseau engagé suit son calendrier de livraison.', absent: 'La tranche initiale de modernisation du réseau n’a pas été financée.' },
    { id: 'adaptation-littorale', launchChoice: 'n25a', followUps: [35, 37, 40, 44], underway: 'L’adaptation littorale engagée doit rester visible jusqu’à sa livraison.', absent: 'La tranche d’adaptation littorale n’a pas été lancée.' },
    { id: 'recherche', launchChoice: 'n34a', followUps: [37, 43, 44], underway: 'Les équipements scientifiques engagés seront livrés après le mandat.', absent: 'Aucune nouvelle tranche d’équipements scientifiques n’a été financée.' },
  ],
};
