import type { NationalSettlement } from "./map-city-national.ts";

/** Eleven decorative farm groups fill the north-east and central plain.
 * Existing kit geometry, UVs, materials and regional LODs are reused.
 * Each house keeps the prefab’s exact XYZ proportions and ground pivot.
 * These identifiers are scenery only: no markers, subjects or game roots.
 * Generated by tools/mandats-assets/rural_fine.py; architecture SHA256:
 * bf89b1435204c6ab9883b21a6893f01a0473859c3a188c73318bbd9e70cc7717
 */
export const RURAL_FINE_SETTLEMENTS: readonly NationalSettlement[] = [
  {
    "name": "hameau-rural36-champagne-nord",
    "lon": 4.68,
    "lat": 49.36,
    "region": "north",
    "major": false,
    "blocks": [
      {
        "id": "hameau-rural36-champagne-nord-cour",
        "outline": [
          [
            -0.19363948538915604,
            0.027173892596401863
          ],
          [
            -0.17314004021965113,
            -0.11988561768196684
          ],
          [
            0.15823784659430387,
            -0.16287446032387337
          ],
          [
            0.18078089844002784,
            -0.06659561808240372
          ],
          [
            0.16563165171340927,
            0.10697555272450528
          ],
          [
            0.002867078538604226,
            0.1449013490406434
          ],
          [
            -0.17683128455094554,
            0.16656925855993782
          ]
        ],
        "buildings": [
          {
            "id": "hameau-rural36-champagne-nord-logis-ferme",
            "model": "ferme_02",
            "x": -0.09596910617137878,
            "z": 0.08120343645838321,
            "angle": 0.12,
            "width": 0.151,
            "depth": 0.11040506994950622,
            "height": 0.0872407953367399,
            "footprintOffset": 0.004869200554426858,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-champagne-nord-maison-cour",
            "model": "maison_brique_02",
            "x": 0.09738724276392431,
            "z": 0.06546906331018082,
            "angle": 0.16499999999999998,
            "width": 0.091,
            "depth": 0.06761074308664959,
            "height": 0.0680394179296283,
            "footprintOffset": 0.003346694727974262,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-champagne-nord-maison-rue",
            "model": "maison_ardoise_01",
            "x": -0.1025025083205878,
            "z": -0.06320304394856809,
            "angle": 3.2115926535897934,
            "width": 0.103,
            "depth": 0.08499739315193411,
            "height": 0.0845853941769267,
            "footprintOffset": 0.003985651658631442,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-champagne-nord-grange",
            "model": "ferme_01",
            "x": 0.09392981533647127,
            "z": -0.09319464808202636,
            "angle": 3.371592653589793,
            "width": 0.127,
            "depth": 0.06888278237325646,
            "height": 0.06119549526249649,
            "footprintOffset": 0.0037427146939581733,
            "ruralInfill": true
          }
        ]
      }
    ],
    "streets": [],
    "trees": []
  },
  {
    "name": "hameau-rural36-argonne",
    "lon": 5.2,
    "lat": 49.18,
    "region": "north",
    "major": false,
    "blocks": [
      {
        "id": "hameau-rural36-argonne-cour",
        "outline": [
          [
            -0.24126828468628447,
            0.09783422405969673
          ],
          [
            -0.2324080060852057,
            -0.05996264426706839
          ],
          [
            -0.14008118894039545,
            -0.17067804594621508
          ],
          [
            0.05056609682592089,
            -0.1385134089767675
          ],
          [
            0.20533060806426906,
            -0.0906391354976305
          ],
          [
            0.2238831394688211,
            0.0527289281285369
          ],
          [
            0.11135041904783158,
            0.16452517912488468
          ],
          [
            -0.06530440879000449,
            0.1581062273411422
          ]
        ],
        "buildings": [
          {
            "id": "hameau-rural36-argonne-logis-ferme",
            "model": "ferme_02",
            "x": -0.1283153103990921,
            "z": 0.05506738358235796,
            "angle": -0.32999999999999996,
            "width": 0.156,
            "depth": 0.1140608669677018,
            "height": 0.09012956339424784,
            "footprintOffset": 0.005030432360864834,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-argonne-maison-cour",
            "model": "maison_pierre_01",
            "x": 0.05731558607021485,
            "z": 0.09648997683568371,
            "angle": -0.13999999999999999,
            "width": 0.096,
            "depth": 0.08182018011976268,
            "height": 0.07729320989375828,
            "footprintOffset": 0.003919266659470363,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-argonne-maison-rue",
            "model": "maison_brique_02",
            "x": -0.08292070098824186,
            "z": -0.10173767557329151,
            "angle": 2.971592653589793,
            "width": 0.106,
            "depth": 0.07875537106796544,
            "height": 0.07925470659934725,
            "footprintOffset": 0.003898347705112876,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-argonne-grange",
            "model": "ferme_01",
            "x": 0.11178711563136988,
            "z": -0.062331387151405494,
            "angle": 2.8415926535897933,
            "width": 0.132,
            "depth": 0.0715947029391327,
            "height": 0.06360476672952392,
            "footprintOffset": 0.0038900656661612514,
            "ruralInfill": true
          }
        ]
      }
    ],
    "streets": [
      {
        "id": "hameau-rural36-argonne-chemin",
        "width": 0.01,
        "points": [
          [
            -0.2324080060852057,
            -0.05996264426706839
          ],
          [
            -0.07913325374672518,
            -0.013188182265058586
          ],
          [
            0.07937095637315232,
            0.012216844290206558
          ],
          [
            0.2238831394688211,
            0.0527289281285369
          ]
        ]
      }
    ],
    "trees": []
  },
  {
    "name": "hameau-rural36-lorraine-ouest",
    "lon": 5.33,
    "lat": 48.82,
    "region": "north",
    "major": false,
    "blocks": [
      {
        "id": "hameau-rural36-lorraine-ouest-cour",
        "outline": [
          [
            -0.2468560710641595,
            0.03983817489251544
          ],
          [
            -0.1710962237431688,
            -0.14895733559515295
          ],
          [
            0.017144253074075716,
            -0.19623983944788595
          ],
          [
            0.17173693546236823,
            -0.13800773530130825
          ],
          [
            0.19674142895227412,
            -0.020694200860385703
          ],
          [
            0.14825071287335218,
            0.12202840505029064
          ],
          [
            0.006472552969896211,
            0.1563474914975979
          ],
          [
            -0.17992385985224946,
            0.19802934950604395
          ]
        ],
        "buildings": [
          {
            "id": "hameau-rural36-lorraine-ouest-logis-ferme",
            "model": "ferme_02",
            "x": -0.10397670430777246,
            "z": 0.10004373087943733,
            "angle": 0.22,
            "width": 0.161,
            "depth": 0.11771666398589736,
            "height": 0.09301833145175578,
            "footprintOffset": 0.005191664167302809,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-lorraine-ouest-maison-cour",
            "model": "maison_brique_02",
            "x": 0.08063655526999931,
            "z": 0.07950295728127911,
            "angle": 0.15,
            "width": 0.091,
            "depth": 0.06761074308664959,
            "height": 0.0680394179296283,
            "footprintOffset": 0.003346694727974262,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-lorraine-ouest-maison-rue",
            "model": "maison_ardoise_01",
            "x": 0.11714528112397532,
            "z": -0.060737841268887906,
            "angle": 3.351592653589793,
            "width": 0.109,
            "depth": 0.08994869760738658,
            "height": 0.08951269869208749,
            "footprintOffset": 0.004217825541658516,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-lorraine-ouest-grange",
            "model": "ferme_01",
            "x": -0.1145344577308435,
            "z": -0.07788423478515118,
            "angle": 1.7157963267948966,
            "width": 0.127,
            "depth": 0.06888278237325646,
            "height": 0.06119549526249649,
            "footprintOffset": 0.0037427146939581733,
            "ruralInfill": true
          }
        ]
      }
    ],
    "streets": [
      {
        "id": "hameau-rural36-lorraine-ouest-chemin",
        "width": 0.01,
        "points": [
          [
            -0.2468560710641595,
            0.03983817489251544
          ],
          [
            -0.0679739106280394,
            0.017451288603748304
          ],
          [
            0.0364909124588195,
            -0.011722342254121925
          ],
          [
            0.0330795230310819,
            -0.09749741102222215
          ],
          [
            0.017144253074075716,
            -0.19623983944788595
          ]
        ]
      }
    ],
    "trees": []
  },
  {
    "name": "hameau-rural36-toul-plaine",
    "lon": 5.56,
    "lat": 48.24,
    "region": "north",
    "major": false,
    "blocks": [
      {
        "id": "hameau-rural36-toul-plaine-cour",
        "outline": [
          [
            -0.23947119467781708,
            -0.018802843390801984
          ],
          [
            -0.14039693725259467,
            -0.15343087689553495
          ],
          [
            0.19493155083062289,
            -0.12192348961262187
          ],
          [
            0.22714886417350005,
            0.03746189403499012
          ],
          [
            0.13751394359213626,
            0.14925656465125986
          ],
          [
            -0.03165852897836634,
            0.14142969502926472
          ],
          [
            -0.21135689206791614,
            0.11976178550997034
          ]
        ],
        "buildings": [
          {
            "id": "hameau-rural36-toul-plaine-logis-ferme",
            "model": "ferme_02",
            "x": -0.11252070735793311,
            "z": 0.05606387292771015,
            "angle": -0.12,
            "width": 0.151,
            "depth": 0.11040506994950622,
            "height": 0.0872407953367399,
            "footprintOffset": 0.004869200554426858,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-toul-plaine-maison-cour",
            "model": "maison_ardoise_01",
            "x": 0.07906133954534607,
            "z": 0.08637473811682649,
            "angle": -0.075,
            "width": 0.096,
            "depth": 0.07922087128723955,
            "height": 0.07883687224257245,
            "footprintOffset": 0.0037147821284331884,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-toul-plaine-maison-rue",
            "model": "maison_brique_02",
            "x": -0.0845076130273613,
            "z": -0.08595141775751539,
            "angle": 2.971592653589793,
            "width": 0.103,
            "depth": 0.07652644547170227,
            "height": 0.07701164886540346,
            "footprintOffset": 0.0037880171096851536,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-toul-plaine-grange",
            "model": "ferme_01",
            "x": 0.11338873574003966,
            "z": -0.06804879332503223,
            "angle": 3.131592653589793,
            "width": 0.132,
            "depth": 0.0715947029391327,
            "height": 0.06360476672952392,
            "footprintOffset": 0.0038900656661612514,
            "ruralInfill": true
          }
        ]
      }
    ],
    "streets": [
      {
        "id": "hameau-rural36-toul-plaine-chemin",
        "width": 0.01,
        "points": [
          [
            -0.23947119467781708,
            -0.018802843390801984
          ],
          [
            -0.06889804347332605,
            -0.013343897689493688
          ],
          [
            0.06877833126603713,
            0.014336706325347554
          ],
          [
            0.22714886417350005,
            0.03746189403499012
          ]
        ]
      }
    ],
    "trees": []
  },
  {
    "name": "hameau-rural36-barrois",
    "lon": 5.18,
    "lat": 48.45,
    "region": "stone",
    "major": false,
    "blocks": [
      {
        "id": "hameau-rural36-barrois-cour",
        "outline": [
          [
            -0.22947523268190154,
            0.0703570720367693
          ],
          [
            -0.21078294933701866,
            -0.07766913532655254
          ],
          [
            -0.029498289778162053,
            -0.15543561091518004
          ],
          [
            0.12262096043040921,
            -0.1942780325181401
          ],
          [
            0.21842660380082718,
            -0.07206815352176343
          ],
          [
            0.17526463648521268,
            0.07531064492929805
          ],
          [
            0.023753179835722227,
            0.1545536410581354
          ],
          [
            -0.1577637457397704,
            0.19514435095117708
          ]
        ],
        "buildings": [
          {
            "id": "hameau-rural36-barrois-logis-ferme",
            "model": "ferme_01",
            "x": -0.08051441921401711,
            "z": 0.11443771253809787,
            "angle": 0.22,
            "width": 0.156,
            "depth": 0.08461192165533862,
            "height": 0.07516926977125553,
            "footprintOffset": 0.004597350332736024,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-barrois-maison-cour",
            "model": "maison_pierre_02",
            "x": 0.09957819114550995,
            "z": 0.052948862602015166,
            "angle": 0.41000000000000003,
            "width": 0.091,
            "depth": 0.06492777962951644,
            "height": 0.06172833158272282,
            "footprintOffset": 0.003213889507273942,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-barrois-maison-rue",
            "model": "maison_pierre_01",
            "x": -0.12370972457652392,
            "z": -0.0429937113440705,
            "angle": 3.521592653589793,
            "width": 0.106,
            "depth": 0.09034311554890463,
            "height": 0.0853445859243581,
            "footprintOffset": 0.004327523603165193,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-barrois-grange",
            "model": "ferme_02",
            "x": 0.06277221008957475,
            "z": -0.11136989138445555,
            "angle": 3.391592653589793,
            "width": 0.127,
            "depth": 0.09285724426216749,
            "height": 0.07337470866070177,
            "footprintOffset": 0.004095287883524576,
            "ruralInfill": true
          }
        ]
      }
    ],
    "streets": [
      {
        "id": "hameau-rural36-barrois-chemin",
        "width": 0.01,
        "points": [
          [
            -0.22947523268190154,
            0.0703570720367693
          ],
          [
            -0.07435633377219641,
            0.03011869233478976
          ],
          [
            0.07405127513575296,
            -0.031071025904675476
          ],
          [
            0.21842660380082718,
            -0.07206815352176343
          ]
        ]
      }
    ],
    "trees": []
  },
  {
    "name": "hameau-rural36-champagne-sud",
    "lon": 4.33,
    "lat": 48.3,
    "region": "stone",
    "major": false,
    "blocks": [
      {
        "id": "hameau-rural36-champagne-sud-cour",
        "outline": [
          [
            -0.24935553561893536,
            0.07043242492506548
          ],
          [
            -0.23489037074012242,
            -0.08574096881635902
          ],
          [
            -0.08861837500686186,
            -0.22079359008768154
          ],
          [
            0.11076237725850112,
            -0.16289780779386037
          ],
          [
            0.21545527197940503,
            -0.030790355888438606
          ],
          [
            0.18360687102016643,
            0.0721668662264304
          ],
          [
            0.0701082721499729,
            0.18518587177925427
          ]
        ],
        "buildings": [
          {
            "id": "hameau-rural36-champagne-sud-logis-ferme",
            "model": "ferme_01",
            "x": -0.1397119807413651,
            "z": 0.036981854825933705,
            "angle": -0.29000000000000004,
            "width": 0.161,
            "depth": 0.08732384222121486,
            "height": 0.07757854123828295,
            "footprintOffset": 0.004744701304939101,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-champagne-sud-maison-cour",
            "model": "maison_ardoise_01",
            "x": 0.0316932436295156,
            "z": 0.10840620902973541,
            "angle": -0.36,
            "width": 0.096,
            "depth": 0.07922087128723955,
            "height": 0.07883687224257245,
            "footprintOffset": 0.0037147821284331884,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-champagne-sud-maison-rue",
            "model": "maison_pierre_02",
            "x": 0.13199754976094052,
            "z": 0.00382726789500554,
            "angle": 2.841592653589793,
            "width": 0.109,
            "depth": 0.07777063713865157,
            "height": 0.07393833123644822,
            "footprintOffset": 0.0038496039153061512,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-champagne-sud-grange",
            "model": "ferme_02",
            "x": -0.06241796506315384,
            "z": -0.12406955672002525,
            "angle": 1.2057963267948966,
            "width": 0.132,
            "depth": 0.09651304128036306,
            "height": 0.07626347671820971,
            "footprintOffset": 0.004256519689962552,
            "ruralInfill": true
          }
        ]
      }
    ],
    "streets": [
      {
        "id": "hameau-rural36-champagne-sud-chemin",
        "width": 0.01,
        "points": [
          [
            -0.23489037074012242,
            -0.08574096881635902
          ],
          [
            -0.06784317918896143,
            -0.017952800269998855
          ],
          [
            0.03756982419605305,
            0.007583423361363063
          ],
          [
            0.0764659897319575,
            -0.0689416594978114
          ],
          [
            0.11076237725850112,
            -0.16289780779386037
          ]
        ]
      }
    ],
    "trees": []
  },
  {
    "name": "hameau-rural36-morvan-nord",
    "lon": 4.42,
    "lat": 47.8,
    "region": "stone",
    "major": false,
    "blocks": [
      {
        "id": "hameau-rural36-morvan-nord-cour",
        "outline": [
          [
            -0.2300649416180095,
            0.06906607443819195
          ],
          [
            -0.18722033541868616,
            -0.09642914943088415
          ],
          [
            0.13156573521761775,
            -0.19323194725536313
          ],
          [
            0.22532389658599353,
            -0.047213786411433825
          ],
          [
            0.17771169609405846,
            0.08331783188836787
          ],
          [
            0.06193863687321577,
            0.11849735375332865
          ],
          [
            -0.15727223380453714,
            0.17427764376335433
          ]
        ],
        "buildings": [
          {
            "id": "hameau-rural36-morvan-nord-logis-ferme",
            "model": "ferme_01",
            "x": -0.08452885875525894,
            "z": 0.09336527527128782,
            "angle": 0.25,
            "width": 0.151,
            "depth": 0.08190000108946238,
            "height": 0.07275999830422811,
            "footprintOffset": 0.004449999360532946,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-morvan-nord-maison-cour",
            "model": "maison_pierre_02",
            "x": 0.10509111651895044,
            "z": 0.05241898499745631,
            "angle": 0.295,
            "width": 0.091,
            "depth": 0.06492777962951644,
            "height": 0.06172833158272282,
            "footprintOffset": 0.003213889507273942,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-morvan-nord-maison-rue",
            "model": "maison_ardoise_01",
            "x": -0.10983085367410539,
            "z": -0.0493819051636736,
            "angle": 3.3415926535897933,
            "width": 0.103,
            "depth": 0.08499739315193411,
            "height": 0.0845853941769267,
            "footprintOffset": 0.003985651658631442,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-morvan-nord-grange",
            "model": "ferme_02",
            "x": 0.08118021972048198,
            "z": -0.10425480068563782,
            "angle": 3.501592653589793,
            "width": 0.127,
            "depth": 0.09285724426216749,
            "height": 0.07337470866070177,
            "footprintOffset": 0.004095287883524576,
            "ruralInfill": true
          }
        ]
      }
    ],
    "streets": [
      {
        "id": "hameau-rural36-morvan-nord-chemin",
        "width": 0.01,
        "points": [
          [
            -0.2300649416180095,
            0.06906607443819195
          ],
          [
            -0.06906088931601775,
            0.012473715039263382
          ],
          [
            0.06930829327527228,
            -0.011504802617552738
          ],
          [
            0.22532389658599353,
            -0.047213786411433825
          ]
        ]
      }
    ],
    "trees": []
  },
  {
    "name": "hameau-rural36-auxerrois",
    "lon": 3.62,
    "lat": 47.85,
    "region": "stone",
    "major": false,
    "blocks": [
      {
        "id": "hameau-rural36-auxerrois-cour",
        "outline": [
          [
            -0.23645659339030772,
            -0.041198051437545916
          ],
          [
            -0.15341329664423015,
            -0.15738134127215406
          ],
          [
            0.04205407470014036,
            -0.1542702479812753
          ],
          [
            0.20014946149169843,
            -0.11891704904217443
          ],
          [
            0.2273809115896227,
            0.03466873295452533
          ],
          [
            0.12414226704437867,
            0.15510044461988254
          ],
          [
            -0.04881764250529813,
            0.14855261457429828
          ],
          [
            -0.22903535294347804,
            0.10253547815295702
          ]
        ],
        "buildings": [
          {
            "id": "hameau-rural36-auxerrois-logis-ferme",
            "model": "ferme_01",
            "x": -0.12361137345233911,
            "z": 0.06556515923529174,
            "angle": -0.25,
            "width": 0.156,
            "depth": 0.08461192165533862,
            "height": 0.07516926977125553,
            "footprintOffset": 0.004597350332736024,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-auxerrois-maison-cour",
            "model": "maison_pierre_01",
            "x": 0.06484324096244103,
            "z": 0.09160101603044474,
            "angle": -0.06,
            "width": 0.096,
            "depth": 0.08182018011976268,
            "height": 0.07729320989375828,
            "footprintOffset": 0.003919266659470363,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-auxerrois-maison-rue",
            "model": "maison_pierre_02",
            "x": -0.09077192757223673,
            "z": -0.09493977625789249,
            "angle": 3.051592653589793,
            "width": 0.106,
            "depth": 0.07563016088712904,
            "height": 0.07190333129416066,
            "footprintOffset": 0.0037436515139674495,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-auxerrois-grange",
            "model": "ferme_02",
            "x": 0.1063684227516285,
            "z": -0.07070784465698296,
            "angle": 2.921592653589793,
            "width": 0.132,
            "depth": 0.09651304128036306,
            "height": 0.07626347671820971,
            "footprintOffset": 0.004256519689962552,
            "ruralInfill": true
          }
        ]
      }
    ],
    "streets": [
      {
        "id": "hameau-rural36-auxerrois-chemin",
        "width": 0.01,
        "points": [
          [
            -0.23645659339030772,
            -0.041198051437545916
          ],
          [
            -0.07993409190973563,
            -0.0068220928288859175
          ],
          [
            0.08009341011634988,
            0.00583486554551029
          ],
          [
            0.2273809115896227,
            0.03466873295452533
          ]
        ]
      }
    ],
    "trees": []
  },
  {
    "name": "hameau-rural36-beauce",
    "lon": 1.3533526689520659,
    "lat": 47.769746127667844,
    "region": "stone",
    "major": false,
    "blocks": [
      {
        "id": "hameau-rural36-beauce-cour",
        "outline": [
          [
            -0.2490379159933601,
            0.022474794719510218
          ],
          [
            -0.1722122416091592,
            -0.15966129646962626
          ],
          [
            0.030827839934685016,
            -0.19456013025530547
          ],
          [
            0.18096900571249638,
            -0.12565798413324974
          ],
          [
            0.19770702057415074,
            -0.006882865037543054
          ],
          [
            0.1392454287079955,
            0.1307614432194021
          ],
          [
            -0.195604886188453,
            0.16993421704834333
          ]
        ],
        "buildings": [
          {
            "id": "hameau-rural36-beauce-logis-ferme",
            "model": "ferme_01",
            "x": -0.1106526154857989,
            "z": 0.09296824100301103,
            "angle": 0.15,
            "width": 0.161,
            "depth": 0.08732384222121486,
            "height": 0.07757854123828295,
            "footprintOffset": 0.004744701304939101,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-beauce-maison-cour",
            "model": "maison_pierre_02",
            "x": 0.07488902625112955,
            "z": 0.08508058530470779,
            "angle": 0.08,
            "width": 0.091,
            "depth": 0.06492777962951644,
            "height": 0.06172833158272282,
            "footprintOffset": 0.003213889507273942,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-beauce-maison-rue",
            "model": "maison_ardoise_01",
            "x": 0.12110656991965431,
            "z": -0.05239561979703749,
            "angle": 3.281592653589793,
            "width": 0.109,
            "depth": 0.08994869760738658,
            "height": 0.08951269869208749,
            "footprintOffset": 0.004217825541658516,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-beauce-grange",
            "model": "ferme_02",
            "x": -0.10915809977149327,
            "z": -0.08567794419995789,
            "angle": 1.6457963267948967,
            "width": 0.127,
            "depth": 0.09285724426216749,
            "height": 0.07337470866070177,
            "footprintOffset": 0.004095287883524576,
            "ruralInfill": true
          }
        ]
      }
    ],
    "streets": [
      {
        "id": "hameau-rural36-beauce-chemin",
        "width": 0.01,
        "points": [
          [
            -0.2490379159933601,
            0.022474794719510218
          ],
          [
            -0.06902803535278292,
            0.012654261548385722
          ],
          [
            0.0372214402181686,
            -0.009141355921596126
          ],
          [
            0.039817757822489114,
            -0.09494496385796145
          ],
          [
            0.030827839934685016,
            -0.19456013025530547
          ]
        ]
      }
    ],
    "trees": []
  },
  {
    "name": "hameau-rural36-sologne",
    "lon": 2.8518520037644235,
    "lat": 47.46111094124938,
    "region": "stone",
    "major": false,
    "blocks": [
      {
        "id": "hameau-rural36-sologne-cour",
        "outline": [
          [
            -0.22449616947087275,
            0.06862013213686498
          ],
          [
            -0.19249811517010745,
            -0.03860735857697648
          ],
          [
            -0.11292164677469739,
            -0.1735403584648594
          ],
          [
            0.2149794292096829,
            -0.0994448314197488
          ],
          [
            0.19232985339645578,
            0.02502422629937963
          ],
          [
            0.11028007182069999,
            0.1703699284879177
          ],
          [
            -0.011957231125852077,
            0.13980783156455764
          ]
        ],
        "buildings": [
          {
            "id": "hameau-rural36-sologne-logis-ferme",
            "model": "ferme_01",
            "x": -0.12050358436773154,
            "z": 0.036620878518665745,
            "angle": -0.29,
            "width": 0.151,
            "depth": 0.08190000108946238,
            "height": 0.07275999830422811,
            "footprintOffset": 0.004449999360532946,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-sologne-maison-cour",
            "model": "maison_ardoise_01",
            "x": 0.06330857081270623,
            "z": 0.09850540927841181,
            "angle": -0.245,
            "width": 0.096,
            "depth": 0.07922087128723955,
            "height": 0.07883687224257245,
            "footprintOffset": 0.0037147821284331884,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-sologne-maison-rue",
            "model": "maison_pierre_02",
            "x": -0.06869782421406533,
            "z": -0.09915131751513853,
            "angle": 2.8015926535897933,
            "width": 0.103,
            "depth": 0.07348968463560653,
            "height": 0.06986833135187309,
            "footprintOffset": 0.0036376991126287482,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-sologne-grange",
            "model": "ferme_02",
            "x": 0.1232012592828589,
            "z": -0.04752394795747827,
            "angle": 2.961592653589793,
            "width": 0.132,
            "depth": 0.09651304128036306,
            "height": 0.07626347671820971,
            "footprintOffset": 0.004256519689962552,
            "ruralInfill": true
          }
        ]
      }
    ],
    "streets": [],
    "trees": []
  },
  {
    "name": "hameau-rural36-berry",
    "lon": 2.05,
    "lat": 46.62,
    "region": "stone",
    "major": false,
    "blocks": [
      {
        "id": "hameau-rural36-berry-cour",
        "outline": [
          [
            -0.2362475931130744,
            0.04238012208900833
          ],
          [
            -0.19996918876437672,
            -0.10234388041550693
          ],
          [
            -0.010678616760721238,
            -0.15784912221640415
          ],
          [
            0.1449966005525005,
            -0.1782016826076962
          ],
          [
            0.22548325628701918,
            -0.04540155431482967
          ],
          [
            0.16498864112546946,
            0.09575037515086617
          ],
          [
            0.005080404554286197,
            0.15628573513344046
          ],
          [
            -0.17999037018742658,
            0.17485475062975048
          ]
        ],
        "buildings": [
          {
            "id": "hameau-rural36-berry-logis-ferme",
            "model": "ferme_01",
            "x": -0.0936350018714652,
            "z": 0.10397619043249047,
            "angle": 0.1,
            "width": 0.156,
            "depth": 0.08461192165533862,
            "height": 0.07516926977125553,
            "footprintOffset": 0.004597350332736024,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-berry-maison-cour",
            "model": "maison_pierre_02",
            "x": 0.09252346289644434,
            "z": 0.0644888131097874,
            "angle": 0.29000000000000004,
            "width": 0.091,
            "depth": 0.06492777962951644,
            "height": 0.06172833158272282,
            "footprintOffset": 0.003213889507273942,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-berry-maison-rue",
            "model": "maison_pierre_01",
            "x": -0.1176732108141349,
            "z": -0.057494092101961485,
            "angle": 3.401592653589793,
            "width": 0.106,
            "depth": 0.09034311554890463,
            "height": 0.0853445859243581,
            "footprintOffset": 0.004327523603165193,
            "ruralInfill": true
          },
          {
            "id": "hameau-rural36-berry-grange",
            "model": "ferme_02",
            "x": 0.0756531277917234,
            "z": -0.10305439011436779,
            "angle": 3.271592653589793,
            "width": 0.127,
            "depth": 0.09285724426216749,
            "height": 0.07337470866070177,
            "footprintOffset": 0.004095287883524576,
            "ruralInfill": true
          }
        ]
      }
    ],
    "streets": [
      {
        "id": "hameau-rural36-berry-chemin",
        "width": 0.01,
        "points": [
          [
            -0.2362475931130744,
            0.04238012208900833
          ],
          [
            -0.07742718543952262,
            0.02100073700882367
          ],
          [
            0.07723832654454613,
            -0.02198274124394094
          ],
          [
            0.22548325628701918,
            -0.04540155431482967
          ]
        ]
      }
    ],
    "trees": []
  }
];
