// Generated by scripts/mandats-model-revisions.ts from the actual asset content.
export const MODEL_URLS = {
  "architecture": "/mandats/models/architecture.glb?v=1f29c04ee18f9217",
  "vegetation": "/mandats/models/vegetation.glb?v=a76e9ce21413da32",
  "paris": "/mandats/models/paris.glb?v=8eb1d54a49bdd46b",
  "cathedrale": "/mandats/models/cathedrale.glb?v=9fb528573a603aee",
  "daylight": "/mandats/models/daylight.env?v=a27b2155c892bc0b"
} as const;
