// Generated by scripts/mandats-model-revisions.ts from the actual asset content.
export const MODEL_URLS = {
  "architecture": "/mandats/models/architecture.glb?v=5f91bf92a18e1ecc",
  "vegetation": "/mandats/models/vegetation.glb?v=44ba0d18ea0aa4e8",
  "paris": "/mandats/models/paris.glb?v=8eb1d54a49bdd46b",
  "cathedrale": "/mandats/models/cathedrale.glb?v=9fb528573a603aee",
  "daylight": "/mandats/models/daylight.env?v=a27b2155c892bc0b"
} as const;
