import type { Effect } from './types.ts';
import type { NarrativeChoice, NarrativeContext, NarrativeEvent, NarrativeFamily, NarrativeRelationship } from './narrative-types.ts';

/** Personnages, lieux et titres de presse sont fictifs; les rendements sont des hypothèses de jeu. */
export const NARRATIVE_CAST: readonly NarrativeRelationship[] = [
  { id: 'samira', name: 'Samira Benali', role: 'urgentiste et représentante des équipes hospitalières', loyalty: 50, stance: 'veut des équipes financées et des engagements tenus' },
  { id: 'luc', name: 'Luc Morel', role: 'maire de Val-des-Forges et négociateur territorial', loyalty: 50, stance: 'défend les services et les emplois du bassin' },
  { id: 'ines', name: 'Inès Vidal', role: 'directrice d’usine et porte-parole des sous-traitants', loyalty: 50, stance: 'soutient les investissements assortis d’un calendrier clair' },
  { id: 'claire', name: 'Claire Dumas', role: 'rapporteure parlementaire chargée de l’éthique publique', loyalty: 50, stance: 'demande des contrôles publics et la protection des alertes' },
];

export const NARRATIVE_PLACES = [
  { id: 'val-des-forges', name: 'Val-des-Forges', description: 'bassin industriel fictif en reconversion' },
  { id: 'hopital-des-rives', name: 'Hôpital des Rives', description: 'centre hospitalier fictif sous tension' },
  { id: 'gare-des-tilleuls', name: 'Quartier de la Gare-des-Tilleuls', description: 'quartier fictif mêlant logements anciens et nouveaux emplois' },
] as const;
export const NARRATIVE_FICTION_NOTE = 'Personnages, lieux et presse sont fictifs. Les coûts et rendements sont des hypothèses de jeu pour des enveloppes nationales; les scènes localisent leurs effets.';

export type NarrativeOpening = {
  id: NarrativeContext;
  title: string;
  body: string;
  promises: [];
  promiseCandidates: [{ id: string; label: string }, { id: string; label: string }];
  characters: string[];
  place: string;
};

/** Chaque contexte ouvre deux engagements incompatibles : le joueur en choisira le coût. */
export const NARRATIVE_OPENINGS: Record<NarrativeContext, NarrativeOpening> = {
  coalition: {
    id: 'coalition', title: 'La majorité réclame deux signatures',
    body: 'La majorité doit choisir comment financer deux promesses à Val-des-Forges : des renforts à l’hôpital et un bus pour les salariés. Les deux projets passent au même vote budgétaire.',
    promises: [], promiseCandidates: [
      { id: 'renforts-nuit', label: 'Aucune unité de soins ne fermera faute de renfort.' },
      { id: 'desservir-usine', label: 'Le premier bus pour l’usine circulera avant l’hiver.' },
    ], characters: ['luc', 'samira'], place: 'val-des-forges',
  },
  hospital: {
    id: 'hospital', title: 'La nuit où les urgences débordent',
    body: 'À l’hôpital des Rives, les gardes manquent de personnel et les locaux doivent être rénovés. Le budget ne permet pas de financer les deux projets en même temps.',
    promises: [], promiseCandidates: [
      { id: 'renforts-nuit', label: 'Des renforts seront présents aux gardes les plus fragiles.' },
      { id: 'service-rives', label: 'Le service de soins sera rénové avant la fin du mandat.' },
    ], characters: ['samira', 'ines'], place: 'hopital-des-rives',
  },
  redress: {
    id: 'redress', title: 'Le redressement a déjà ses perdants',
    body: 'Réduire les dépenses pourrait supprimer l’aide aux familles menacées d’expulsion. Dans le même temps, des marchés publics et une aide à l’usine attendent une décision.',
    promises: [], promiseCandidates: [
      { id: 'prevenir-expulsions', label: 'Les habitants garderont un guichet pour prévenir les expulsions.' },
      { id: 'audit-marche', label: 'Les contrats publics à risque seront contrôlés et publiés.' },
    ], characters: ['claire', 'ines'], place: 'gare-des-tilleuls',
  },
};

const effect = (value: Effect): Effect => value;
const choice = (value: NarrativeChoice): NarrativeChoice => value;
const event = (value: NarrativeEvent): NarrativeEvent => value;

/**
 * Rendements explicitement hypothétiques du jeu, en Md€ pour les flux nationaux.
 * Les choix narratifs financent des lots distincts; ils ne rejouent pas les économies,
 * recettes ou pertes des réformes r01-r15. Les références signalent le cadre déjà
 * couvert et ne déclenchent aucun effet par elles-mêmes.
 */
export const NARRATIVE_FAMILIES: readonly NarrativeFamily[] = [
  { id: 'soins-hospitaliers', title: 'Soins hospitaliers', category: 'Santé', summary: 'Des équipes, des lits et des trajets de soins à arbitrer.', art: 'hospital', urgency: 'à traiter vite', reformRefs: ['r05', 'r10'] },
  { id: 'industrie-conditionnalite', title: 'Industrie sous condition', category: 'Industrie', summary: 'Des aides publiques contre des emplois, des preuves et un calendrier.', art: 'energy', urgency: 'à traiter vite', reformRefs: ['r04', 'r16'] },
  { id: 'transition-energetique-mobilite', title: 'Énergie et mobilité', category: 'Transition', summary: 'Financer la conversion sans abandonner les ménages captifs.', art: 'energy', urgency: 'à suivre', reformRefs: ['r13'] },
  { id: 'recrutement-integration', title: 'Recruter et intégrer', category: 'Travail', summary: 'Pourvoir les postes vacants sans opposer nouveaux arrivants et équipes en place.', art: 'office', urgency: 'à suivre', reformRefs: ['r02', 'r07', 'r11', 'r12'] },
  { id: 'integrite-ministerielle', title: 'Intégrité ministérielle', category: 'Institutions', summary: 'Éclaircir les intérêts, protéger les alertes et décider sous contrôle.', art: 'nation', urgency: 'à suivre', reformRefs: [] },
  { id: 'logement', title: 'Logement et stabilité', category: 'Logement', summary: 'Éviter les expulsions et remettre des logements en usage avec les partenaires.', art: 'school', urgency: 'à traiter vite', reformRefs: ['r14'] },
];

const A = (id: string, label: string, delta: Effect, support: number) => ({ id, label, effect: effect(delta), support });
const P = (id: string, kind: string, label: string, place: string, dueAfter: number, pressByStatus: Record<string, string>, repair = false) => ({ id, kind, label, place, dueAfter, action: repair ? 'repair' as const : 'fund' as const, ...(repair ? { repair: true } : {}), pressByStatus, deliveryEffect: kind === 'hospital' ? { services: 3, assets: 1 } : kind === 'industry' ? { growth: 0.005, services: 1 } : kind === 'energy' ? { resilience: 2, services: 1 } : kind === 'housing' ? { cohesion: 2, services: 1, assets: 1 } : { trust: 2 } });

export const NARRATIVE_EVENTS: readonly NarrativeEvent[] = [
  event({
    id: 'soins-garde-nuit', familyId: 'soins-hospitaliers', title: 'Une garde sans équipe complète',
    body: 'À l’hôpital des Rives, les équipes de nuit manquent de personnel et les locaux vieillissent. Les renforts aideraient tout de suite; les travaux réduiraient temporairement l’accueil.',
    turns: [0, 1, 2, 3], contexts: ['hospital', 'coalition'],
    choices: [
      choice({ id: 'financer-renforts', title: 'Financer six mois de renfort', description: 'Ouvrir une enveloppe temporaire pour les gardes de nuit et publier les postes à pourvoir.', cost: '0,4 Md€ pour six mois', benefit: 'Davantage de gardes couvertes pendant six mois.', sacrifice: 'La mesure s’arrête si les recrutements durables n’aboutissent pas.', effect: effect({ operating: 0.4, services: 3, cohesion: 1 }), delayed: { after: 1, label: 'Le renfort de six mois prend fin; toute prolongation doit être revotée.', effect: effect({ operating: -0.4 }) }, promise: { id: 'renforts-nuit', label: 'Des renforts seront présents aux gardes les plus fragiles.', dueAfter: 2, keepWhen: 'services_improved' }, relationships: { social: 2, regional: 1 }, press: 'La Gazette des Rives : « Six mois de renfort votés, le recrutement durable reste à faire. »' }),
      choice({ id: 'renover-service', title: 'Engager la rénovation du service', description: 'Lancer les travaux par phases, avec maintien d’un accueil réduit.', cost: '1,6 Md€ d’investissement', benefit: 'Des locaux plus sûrs à la livraison.', sacrifice: 'La capacité d’accueil sera réduite pendant le chantier.', effect: effect({ investment: 1.6, services: -1 }), promise: { id: 'service-rives', label: 'Le service de soins rénové sera livré.', dueAfter: 2, targetProject: 'service-rives', keepWhen: 'project_delivered' }, project: P('service-rives', 'hospital', 'Rénovation du service de soins', 'hopital-des-rives', 2, { funded: 'La Gazette des Rives : « Les travaux des Rives sont financés, deux décisions de chantier annoncées. »', blocked: 'La Gazette des Rives : « Le chantier des Rives est bloqué, les équipes demandent un nouveau calendrier. »', delivered: 'La Gazette des Rives : « Le service rénové des Rives ouvre ses portes. »', withdrawn: 'La Gazette des Rives : « Faute de crédits, le projet de rénovation est retiré. »' }), relationships: { social: 1, regional: 1 } }),
      choice({ id: 'organiser-garde', title: 'Réorganiser les gardes existantes', description: 'Mutualiser les plannings entre services voisins et garantir les transferts.', cost: '0,2 Md€ de fonctionnement', benefit: 'Un relais identifié chaque nuit.', sacrifice: 'Des équipes se déplacent davantage et certains services ferment plus tôt.', effect: effect({ operating: 0.2, services: 1, cohesion: -1 }), amendment: A('amend-garde-trajets', 'Ajouter une navette pour les équipes de nuit', { operating: 0.15, services: 1 }, 2), relationships: { regional: 1, social: -1 } }),
    ],
  }),
  event({
    id: 'soins-lits-aval', familyId: 'soins-hospitaliers', title: 'Des lits occupés faute de relais',
    body: 'Des patients restent à l’hôpital faute de soins de suite ou d’aide à domicile. Faut-il financer une équipe mobile ou ouvrir des places temporaires dans le bassin ?',
    turns: [7, 8, 9, 10],
    choices: [
      choice({ id: 'equipe-domicile', title: 'Financer une équipe de sortie', description: 'Créer une équipe mobile qui coordonne retour à domicile et soins de suite.', cost: '0,5 Md€ par an', benefit: 'Des sorties mieux accompagnées dans le bassin.', sacrifice: 'Une dépense durable et des recrutements difficiles.', effect: effect({ operating: 0.5, services: 2, cohesion: 1 }), promise: { id: 'retour-accompagne', label: 'Les patients sortants auront un relais de soins identifié.', dueAfter: 3, keepWhen: 'services_improved' }, relationships: { social: 2 } }),
      choice({ id: 'places-temporaire', title: 'Ouvrir des places temporaires', description: 'Cofinancer des places de soins de suite avec les partenaires locaux.', cost: '1,1 Md€ d’investissement', benefit: 'Une capacité supplémentaire après livraison.', sacrifice: 'Les places ne seront pas disponibles pour la première année.', effect: effect({ investment: 1.1 }), project: P('places-suite', 'hospital', 'Places temporaires de soins de suite', 'hopital-des-rives', 2, { funded: 'La Gazette des Rives : « Les places de soins de suite sont financées, ouverture prévue après travaux. »', blocked: 'La Gazette des Rives : « Le chantier des places de suite attend un accord des partenaires. »', delivered: 'La Gazette des Rives : « Les nouvelles places de soins de suite accueillent leurs premiers patients. »', withdrawn: 'La Gazette des Rives : « Le projet de places temporaires est abandonné. »' }), relationships: { regional: 2 } }),
      choice({ id: 'lits-court-sejour', title: 'Réserver les lits aux cas aigus', description: 'Réduire les séjours prolongés et accélérer les transferts disponibles.', cost: '0,1 Md€ d’organisation', benefit: 'Les lits aigus se libèrent plus vite.', sacrifice: 'Les proches assument davantage de coordination.', effect: effect({ operating: 0.1, services: 1, cohesion: -2 }), amendment: A('amend-proches', 'Financer l’accompagnement des aidants', { operating: 0.2, cohesion: 2 }, 2), relationships: { social: -1, regional: 1 } }),
    ],
  }),
  event({
    id: 'soins-desert-medical', familyId: 'soins-hospitaliers', title: 'La consultation est à cinquante kilomètres',
    body: 'À Val-des-Forges, certains patients doivent parcourir cinquante kilomètres pour consulter un spécialiste. Faut-il rapprocher les consultations avec une antenne, une équipe mobile ou la téléconsultation ?',
    turns: [13, 14, 15, 16],
    choices: [
      choice({ id: 'antenne-soins', title: 'Cofinancer une antenne de consultation', description: 'Préparer des locaux partagés et une convention de présence médicale.', cost: '1,3 Md€ d’investissement', benefit: 'Un point d’accès régulier après livraison.', sacrifice: 'La présence dépendra encore des professionnels disponibles.', effect: effect({ investment: 1.3 }), project: P('antenne-forges', 'hospital', 'Antenne de consultation hospitalière', 'val-des-forges', 2, { funded: 'Le Courrier des Forges : « L’antenne de soins est financée, les praticiens restent à recruter. »', blocked: 'Le Courrier des Forges : « L’antenne attend sa convention hospitalière. »', delivered: 'Le Courrier des Forges : « L’antenne ouvre deux jours par semaine. »', withdrawn: 'Le Courrier des Forges : « Le projet d’antenne est retiré du budget. »' }), relationships: { regional: 2 } }),
      choice({ id: 'equipe-mobile-soins', title: 'Déployer une équipe mobile', description: 'Financer des consultations itinérantes sur les communes éloignées.', cost: '0,4 Md€ par an', benefit: 'Des consultations arrivent dans plusieurs communes.', sacrifice: 'Le temps de trajet réduit le nombre de rendez-vous.', effect: effect({ operating: 0.4, services: 2, cohesion: 1 }), promise: { id: 'consultations-itinerantes', label: 'Les communes éloignées garderont un accès périodique aux consultations.', dueAfter: 2, keepWhen: 'services_improved' }, relationships: { social: 1, regional: 2 } }),
      choice({ id: 'teleconsultation-soins', title: 'Équiper des points de téléconsultation', description: 'Financer du matériel et un accompagnement humain dans les maisons de services.', cost: '0,6 Md€ d’investissement', benefit: 'Les patients consultent sans prendre la route à chaque rendez-vous.', sacrifice: 'Les examens et les urgences exigent toujours un professionnel sur place.', effect: effect({ investment: 0.6 }), project: P('teleconsultation', 'hospital', 'Points accompagnés de téléconsultation', 'val-des-forges', 1, { funded: 'Le Courrier des Forges : « Le matériel de téléconsultation est financé, l’accompagnement reste à organiser. »', blocked: 'Le Courrier des Forges : « Les points de téléconsultation sont livrés mais sans permanence. »', delivered: 'Le Courrier des Forges : « Les points de téléconsultation accompagnés ouvrent au public. »', withdrawn: 'Le Courrier des Forges : « Le programme de téléconsultation est abandonné. »' }), relationships: { regional: 1, social: 1 } }),
    ],
  }),

  event({
    id: 'industrie-aide-contre-emplois', familyId: 'industrie-conditionnalite', title: 'L’aide arrive avant les embauches',
    body: 'L’usine de Val-des-Forges demande une aide alors que les embauches promises n’ont pas commencé. Faut-il verser l’argent par étapes vérifiées ou payer tout de suite et négocier les engagements plus tard ?',
    turns: [1, 2, 3, 4], contexts: ['coalition', 'redress'],
    choices: [
      choice({ id: 'tranche-contre-emplois', title: 'Verser par tranches vérifiées', description: 'Débloquer la première tranche après publication des postes et des achats locaux.', cost: '0,9 Md€ d’aide', benefit: 'Le projet démarre avec des conditions vérifiables.', sacrifice: 'L’administration contrôle les preuves à chaque étape.', effect: effect({ investment: 0.9, services: 1 }), project: P('filiere-forges', 'industry', 'Filière industrielle à engagements vérifiés', 'val-des-forges', 2, { funded: 'Le Courrier des Forges : « La première tranche est conditionnée aux emplois publiés. »', blocked: 'Le Courrier des Forges : « Faute de preuve d’embauche, le versement reste suspendu. »', delivered: 'Le Courrier des Forges : « Les engagements de la filière sont vérifiés, les postes sont ouverts. »', withdrawn: 'Le Courrier des Forges : « L’aide conditionnelle est retirée après l’échec du contrat. »' }), relationships: { reformist: 2, regional: 1 }, press: 'Le Courrier des Forges : « L’aide industrielle ne partira qu’avec ses preuves d’emploi. »' }),
      choice({ id: 'aide-sans-condition', title: 'Payer pour tenir le calendrier', description: 'Verser immédiatement l’aide prévue et négocier les engagements plus tard.', cost: '0,9 Md€ d’aide', benefit: 'L’usine poursuit son investissement sans délai administratif.', sacrifice: 'Les créations d’emplois ne sont pas garanties par ce vote.', effect: effect({ investment: 0.9, trust: -2 }), project: P('filiere-forges-libre', 'industry', 'Investissement industriel sans jalons opposables', 'val-des-forges', 2, { funded: 'Le Courrier des Forges : « L’aide est versée avant la vérification des emplois. »', blocked: 'Le Courrier des Forges : « Le chantier industriel ralentit, sans jalon de contrôle. »', delivered: 'Le Courrier des Forges : « Le site est modernisé; les emplois promis restent à vérifier. »', withdrawn: 'Le Courrier des Forges : « Le projet industriel financé est retiré. »' }), relationships: { reformist: -1, regional: 1, conservative: 1 } }),
      choice({ id: 'aide-suspendue', title: 'Suspendre le versement', description: 'Geler les crédits et ouvrir une vérification indépendante du contrat.', cost: '0,1 Md€ de contrôle', benefit: 'Le risque de payer sans contrepartie diminue.', sacrifice: 'Les fournisseurs attendent et le calendrier industriel glisse.', effect: effect({ operating: 0.1, trust: 2, growth: -0.01 }), amendment: A('amend-fonds-sous-traitants', 'Réserver un fonds de trésorerie aux petits fournisseurs', { investment: 0.2, trust: 1 }, 2), relationships: { reformist: 2, regional: -1 } }),
    ],
  }),
  event({
    id: 'industrie-commandes-locales', familyId: 'industrie-conditionnalite', title: 'Les sous-traitants ne voient pas les commandes',
    body: 'Les PME de Val-des-Forges peinent à accéder aux marchés publics de modernisation. Faut-il les aider à préparer leurs offres ou découper les marchés en lots plus petits ?',
    turns: [8, 9, 10, 11],
    choices: [
      choice({ id: 'lots-pme', title: 'Découper les marchés en lots accessibles', description: 'Financer une cellule d’appui aux candidatures et publier le calendrier des marchés.', cost: '0,2 Md€ de fonctionnement', benefit: 'Des PME peuvent se positionner avant la clôture des appels.', sacrifice: 'Le suivi de plusieurs lots coûte du temps aux acheteurs.', effect: effect({ operating: 0.2, cohesion: 1, trust: 1 }), promise: { id: 'acces-commandes-pme', label: 'Les petits fournisseurs auront accès aux marchés annoncés.', dueAfter: 2, keepWhen: 'programme_executed' }, relationships: { regional: 2, reformist: 1 } }),
      choice({ id: 'avance-fournisseurs', title: 'Garantir une avance remboursable', description: 'Créer une avance aux fournisseurs retenus, conditionnée aux livraisons.', cost: '0,6 Md€ de trésorerie engagée', benefit: 'Les petites entreprises peuvent acheter les intrants.', sacrifice: 'Le budget porte un risque si la livraison échoue.', effect: effect({ investment: 0.6 }), project: P('avance-fournisseurs', 'industry', 'Avances remboursables aux fournisseurs', 'val-des-forges', 1, { funded: 'Le Courrier des Forges : « Les avances sont engagées contre preuve de livraison. »', blocked: 'Le Courrier des Forges : « Les avances restent bloquées faute de bons de commande. »', delivered: 'Le Courrier des Forges : « Les fournisseurs remboursent les avances après livraison. »', withdrawn: 'Le Courrier des Forges : « Le fonds d’avances est fermé. »' }), relationships: { regional: 2 } }),
      choice({ id: 'garder-marches-regroupes', title: 'Garder les lots regroupés', description: 'Maintenir un grand marché pour tenir le calendrier industriel.', cost: 'Aucune dépense nouvelle', benefit: 'Un seul titulaire coordonne les travaux.', sacrifice: 'Les entreprises locales sans capacité de groupement restent à l’écart.', effect: effect({ cohesion: -1, trust: -1 }), relationships: { regional: -2 } }),
    ],
  }),
  event({
    id: 'industrie-site-pollue', familyId: 'industrie-conditionnalite', title: 'Réouvrir le site ou dépolluer d’abord ?',
    body: 'Un ancien site industriel pourrait accueillir de nouvelles activités, mais son sol doit être vérifié. Faut-il lancer la dépollution sous contrôle indépendant ou attendre les résultats avant d’annoncer le chantier ?',
    turns: [14, 15, 16, 17],
    choices: [
      choice({ id: 'diagnostic-depollution', title: 'Financer le diagnostic et la dépollution', description: 'Payer l’étude indépendante, puis traiter les zones confirmées avant d’ouvrir le site.', cost: '1,2 Md€ d’investissement', benefit: 'Une réouverture conditionnée à des contrôles publics.', sacrifice: 'Les emplois attendent les résultats et le chantier.', effect: effect({ investment: 1.2, trust: 1 }), project: P('site-depollue', 'industry', 'Diagnostic et dépollution de l’emprise', 'val-des-forges', 2, { funded: 'Le Courrier des Forges : « Le diagnostic du site est financé, les travaux attendent les prélèvements. »', blocked: 'Le Courrier des Forges : « La dépollution est bloquée, les garanties manquent. »', delivered: 'Le Courrier des Forges : « Le site dépollué ouvre après contrôle indépendant. »', withdrawn: 'Le Courrier des Forges : « Le projet de réouverture est abandonné. »' }), relationships: { reformist: 2, regional: 1 } }),
      choice({ id: 'reouvrir-avec-caution', title: 'Réouvrir avec une caution privée', description: 'Autoriser les travaux par zones et exiger une garantie de remise en état.', cost: '0,3 Md€ de contrôle public, hypothèse de simulation', benefit: 'Les premières activités peuvent redémarrer plus tôt.', sacrifice: 'Le suivi environnemental devient une obligation continue.', effect: effect({ operating: 0.3, growth: 0.01, trust: -1 }), amendment: A('amend-controle-public', 'Publier les prélèvements à chaque étape', { operating: 0.05, trust: 2 }, 2), relationships: { reformist: 1, conservative: 1 } }),
      choice({ id: 'geler-site-pollue', title: 'Geler le site', description: 'Interdire les travaux jusqu’à l’expertise complète et conserver le terrain fermé.', cost: '0,1 Md€ de sécurisation', benefit: 'Aucune activité ne démarre avant le diagnostic.', sacrifice: 'Le terrain ne crée ni emploi ni recette pendant l’attente.', effect: effect({ investment: 0.1, growth: -0.01, trust: 1 }), relationships: { reformist: 1, regional: -2 } }),
    ],
  }),

  event({
    id: 'energie-bus-usine', familyId: 'transition-energetique-mobilite', title: 'Le bus promis n’a pas de conducteur',
    body: 'À Val-des-Forges, les salariés qui finissent tard n’ont pas de bus pour rentrer. Lancer la ligne exige des véhicules, des chauffeurs et des bornes de recharge.',
    turns: [0, 1, 2, 3], contexts: ['coalition'],
    choices: [
      choice({ id: 'bus-soir', title: 'Financer les bus du soir', description: 'Signer une année de service avec les horaires d’équipe et un suivi des fréquentations.', cost: '0,35 Md€ par an', benefit: 'Les salariés disposent d’un trajet après leur poste.', sacrifice: 'La dépense revient chaque année même si l’usage fluctue.', effect: effect({ operating: 0.35, cohesion: 2, services: 1 }), promise: { id: 'desservir-usine', label: 'Le premier bus pour l’usine circulera avant l’hiver.', dueAfter: 1, keepWhen: 'services_improved' }, relationships: { regional: 2, conservative: -1 }, press: 'Le Courrier des Forges : « Le bus du soir est financé; les premiers départs sont annoncés avant l’hiver. »' }),
      choice({ id: 'bornes-ligne', title: 'Financer les bornes de recharge', description: 'Équiper les terminus et préparer le renouvellement de la flotte.', cost: '1,0 Md€ d’investissement', benefit: 'La conversion de la ligne peut commencer après travaux.', sacrifice: 'Aucun service supplémentaire ne circule pour la première année.', effect: effect({ investment: 1.0 }), project: P('recharge-bus', 'energy', 'Recharge électrique de la ligne de bus', 'gare-des-tilleuls', 2, { funded: 'L’Écho des Tilleuls : « Les bornes sont financées, les bus attendent encore. »', blocked: 'L’Écho des Tilleuls : « Le raccordement électrique bloque la ligne. »', delivered: 'L’Écho des Tilleuls : « Les bornes entrent en service pour la ligne du bassin. »', withdrawn: 'L’Écho des Tilleuls : « Le chantier de recharge est retiré du programme. »' }), relationships: { regional: 1, reformist: 1 } }),
      choice({ id: 'horaires-pilote', title: 'Lancer un pilote de six mois', description: 'Redéployer un service existant sur deux départs tardifs.', cost: '0,04 Md€ d’organisation', benefit: 'Le besoin est testé avant un engagement durable.', sacrifice: 'Les communes voisines perdent une partie de leurs passages.', effect: effect({ operating: 0.04, cohesion: -1, services: 1 }), delayed: { after: 1, label: 'Le pilote de six mois prend fin avant tout nouveau vote.', effect: effect({ operating: -0.04 }) }, amendment: A('amend-covoiturage', 'Ajouter un relais de covoiturage pour les communes écartées', { operating: 0.06, cohesion: 2 }, 2), relationships: { regional: 1, conservative: 1 } }),
    ],
  }),
  event({
    id: 'energie-menages-captifs', familyId: 'transition-energetique-mobilite', title: 'Changer de chauffage sans autre solution ?',
    body: 'À la Gare-des-Tilleuls, des familles doivent remplacer leur chauffage polluant mais n’en ont pas les moyens. Sans aide ni artisan disponible, l’obligation reste impossible à tenir.',
    turns: [7, 8, 9, 10],
    choices: [
      choice({ id: 'aide-ciblee-renovation', title: 'Cibler les ménages sans alternative', description: 'Aider les foyers modestes à remplacer leur équipement avec avance de frais.', cost: '0,7 Md€ d’aide', benefit: 'La transition ne dépend pas uniquement de l’épargne disponible.', sacrifice: 'Les dossiers et contrôles ralentissent les premiers chantiers.', effect: effect({ investment: 0.7, cohesion: 2, resilience: 1 }), promise: { id: 'aide-menages-captifs', label: 'Les ménages sans solution immédiate pourront demander une aide de remplacement.', dueAfter: 2, keepWhen: 'programme_executed' }, amendment: A('amend-accompagnement-renovation', 'Ajouter un accompagnateur énergie dans chaque secteur', { operating: 0.12, services: 1, cohesion: 1 }, 2), relationships: { social: 2, regional: 1 } }),
      choice({ id: 'guichet-renovation', title: 'Ouvrir un guichet avec les artisans', description: 'Financer le diagnostic, l’orientation et la réservation des chantiers.', cost: '0,18 Md€ par an', benefit: 'Les ménages savent quels travaux sont possibles.', sacrifice: 'Le guichet ne finance pas lui-même les équipements.', effect: effect({ operating: 0.18, services: 1, trust: 1 }), promise: { id: 'guichet-energie', label: 'Un guichet orientera les ménages vers les travaux finançables.', dueAfter: 1, keepWhen: 'services_improved' }, relationships: { social: 1, regional: 2 } }),
      choice({ id: 'reporter-remplacement', title: 'Reporter l’obligation', description: 'Décaler la contrainte et réserver l’enveloppe à l’entretien du réseau.', cost: 'Aucune dépense nouvelle', benefit: 'Les ménages gardent du temps pour s’organiser.', sacrifice: 'Les émissions locales baissent moins vite.', effect: effect({ resilience: -1, trust: 1 }), relationships: { social: 1, reformist: -1 } }),
    ],
  }),
  event({
    id: 'energie-reseau-partage', familyId: 'transition-energetique-mobilite', title: 'Qui paie le raccordement ?',
    body: 'Le réseau électrique de Val-des-Forges doit être renforcé pour accueillir de nouveaux producteurs. Qui doit payer les travaux, et quelles communes auront accès au réseau ?',
    turns: [14, 15, 16, 17],
    choices: [
      choice({ id: 'raccordement-partage', title: 'Partager le coût avec le producteur', description: 'Financer le renforcement public contre une contribution et un accès ouvert.', cost: '1,4 Md€ de financement public', benefit: 'Le réseau sert plusieurs projets du bassin.', sacrifice: 'Les travaux prennent deux décisions et le partage doit être contrôlé.', effect: effect({ investment: 1.4, resilience: 1 }), project: P('reseau-ouvert', 'energy', 'Raccordement ouvert du bassin', 'val-des-forges', 2, { funded: 'Le Courrier des Forges : « Le raccordement partagé est financé, accès ouvert inscrit au contrat. »', blocked: 'Le Courrier des Forges : « Le réseau attend sa convention d’accès ouvert. »', delivered: 'Le Courrier des Forges : « Le raccordement ouvert dessert les premiers projets. »', withdrawn: 'Le Courrier des Forges : « Le raccordement partagé est retiré du plan. »' }), relationships: { regional: 2, reformist: 1 } }),
      choice({ id: 'reseau-public-seul', title: 'Payer le réseau public seul', description: 'Faire porter les travaux au budget public pour démarrer plus vite.', cost: '2,0 Md€ d’investissement', benefit: 'Le chantier démarre sans négociation de contribution.', sacrifice: 'Le risque de dépassement revient au budget public.', effect: effect({ investment: 2.0, resilience: 1 }), project: P('reseau-public', 'energy', 'Renforcement public du réseau', 'val-des-forges', 2, { funded: 'Le Courrier des Forges : « Le réseau public est financé, sans contribution privée. »', blocked: 'Le Courrier des Forges : « Le raccordement public dépasse son calendrier. »', delivered: 'Le Courrier des Forges : « Le réseau public est livré. »', withdrawn: 'Le Courrier des Forges : « Le chantier public est arrêté. »' }), relationships: { regional: 1, conservative: 1 } }),
      choice({ id: 'renoncer-raccordement', title: 'Prioriser les économies d’énergie', description: 'Reporter le grand raccordement et financer des travaux de sobriété des bâtiments publics.', cost: '0,6 Md€ d’investissement', benefit: 'Des économies d’énergie sont possibles après livraison.', sacrifice: 'La nouvelle production ne sera pas raccordée dans le calendrier.', effect: effect({ investment: 0.6 }), project: P('sobriete-batiments', 'energy', 'Sobriété énergétique des bâtiments publics', 'gare-des-tilleuls', 1, { funded: 'L’Écho des Tilleuls : « Le programme de sobriété est financé, les économies restent à mesurer. »', blocked: 'L’Écho des Tilleuls : « Les travaux de sobriété attendent les marchés. »', delivered: 'L’Écho des Tilleuls : « Les premiers bâtiments rénovés rouvrent. »', withdrawn: 'L’Écho des Tilleuls : « Le programme de sobriété est retiré. »' }), relationships: { reformist: 1, regional: -1 } }),
    ],
  }),

  event({
    id: 'recrutement-postes-vacants', familyId: 'recrutement-integration', title: 'Des postes vacants, des horaires réduits',
    body: 'L’hôpital et les guichets publics manquent d’agents, et les postes restent vacants. Faut-il améliorer les conditions de travail ou simplifier les recrutements tout en gardant les qualifications requises ?',
    turns: [2, 3, 4, 5], contexts: ['hospital', 'coalition'],
    choices: [
      choice({ id: 'prime-installation', title: 'Financer une prime d’installation', description: 'Verser une prime annuelle aux personnels qui prennent les postes vacants.', cost: '0,3 Md€ par an', benefit: 'Les postes prioritaires deviennent plus attractifs.', sacrifice: 'Les équipes déjà en place demandent le même traitement.', effect: effect({ operating: 0.3, services: 2 }), promise: { id: 'pourvoir-postes', label: 'Les postes prioritaires seront publiés avec une aide d’installation.', dueAfter: 2, keepWhen: 'services_improved' }, amendment: A('amend-equipe-en-place', 'Inclure les équipes déjà en poste dans la prime', { operating: 0.18, cohesion: 2 }, 2), relationships: { social: 2, reformist: 1 } }),
      choice({ id: 'simplifier-concours', title: 'Simplifier les procédures de recrutement', description: 'Mutualiser les concours et accélérer les vérifications administratives.', cost: '0,1 Md€ d’organisation', benefit: 'Les délais de prise de poste diminuent dans le scénario.', sacrifice: 'Les équipes RH absorbent une charge de transition.', effect: effect({ operating: 0.1, services: 1 }), promise: { id: 'delais-recrutement', label: 'Les délais d’embauche des postes prioritaires seront raccourcis.', dueAfter: 2, keepWhen: 'services_improved' }, relationships: { reformist: 2 } }),
      choice({ id: 'reduire-horaires-vacants', title: 'Réduire les horaires aux capacités disponibles', description: 'Adapter les ouvertures aux équipes réellement présentes.', cost: 'Aucune dépense nouvelle', benefit: 'Les équipes cessent d’enchaîner les remplacements d’urgence.', sacrifice: 'Les usagers trouvent moins de créneaux.', effect: effect({ services: -2, cohesion: -1 }), relationships: { conservative: 1, social: -2 } }),
    ],
  }),
  event({
    id: 'integration-diplomes', familyId: 'recrutement-integration', title: 'Un diplôme reconnu, un poste toujours fermé',
    body: 'Des professionnels formés à l’étranger attendent la reconnaissance de leurs diplômes avant de pouvoir exercer. Faut-il accélérer l’évaluation ou financer un parcours de mise à niveau et d’accompagnement ?',
    turns: [9, 10, 11, 12], contexts: ['redress'],
    choices: [
      choice({ id: 'parcours-reconnaissance', title: 'Financer un parcours de reconnaissance', description: 'Créer des sessions d’évaluation et des stages rémunérés encadrés.', cost: '0,25 Md€ par an', benefit: 'Des candidats qualifiés peuvent accéder aux postes plus vite.', sacrifice: 'Le tutorat retire du temps aux équipes en place.', effect: effect({ operating: 0.25, services: 2, cohesion: 2 }), promise: { id: 'parcours-diplomes', label: 'Les candidats disposeront d’un parcours lisible de reconnaissance des qualifications.', dueAfter: 2, keepWhen: 'services_improved' }, amendment: A('amend-tuteurs', 'Financer du temps protégé pour les tuteurs', { operating: 0.1, services: 1, cohesion: 1 }, 2), relationships: { social: 2, reformist: 1 } }),
      choice({ id: 'cours-langue-metier', title: 'Associer langue et pratique professionnelle', description: 'Financer des cours de langue liés aux situations de travail.', cost: '0,16 Md€ par an', benefit: 'Les nouveaux collègues travaillent avec davantage d’autonomie.', sacrifice: 'La formation prend du temps avant la pleine activité.', effect: effect({ operating: 0.16, services: 1, cohesion: 2 }), promise: { id: 'langue-travail', label: 'La formation en langue sera accessible aux nouveaux collègues.', dueAfter: 1, keepWhen: 'services_improved' }, relationships: { social: 2, regional: 1 } }),
      choice({ id: 'recrutement-local-seul', title: 'Concentrer les moyens sur la formation locale', description: 'Réserver l’effort de formation aux personnes déjà inscrites dans les bassins d’emploi.', cost: '0,2 Md€ par an', benefit: 'Des candidats locaux reçoivent une formation plus longue.', sacrifice: 'Les candidats arrivés récemment attendent davantage.', effect: effect({ operating: 0.2, cohesion: -2 }), relationships: { conservative: 1, social: -2 } }),
    ],
  }),
  event({
    id: 'integration-logement-travail', familyId: 'recrutement-integration', title: 'Un contrat signé, aucun logement disponible',
    body: 'Des salariés recrutés à Val-des-Forges renoncent parfois au poste faute de logement proche. Faut-il financer une résidence temporaire, avec des règles publiques d’accès et une durée limitée ?',
    turns: [18, 19, 20, 21],
    choices: [
      choice({ id: 'residence-mobilite', title: 'Ouvrir une résidence temporaire', description: 'Cofinancer des logements temporaires attribués selon des règles publiées.', cost: '1,0 Md€ d’investissement', benefit: 'Les nouvelles recrues peuvent s’installer le temps de trouver un logement.', sacrifice: 'Les logements ne répondent pas aux besoins des familles sur la durée.', effect: effect({ investment: 1.0 }), project: P('residence-travail', 'housing', 'Résidence temporaire pour salariés recrutés', 'val-des-forges', 2, { funded: 'Le Courrier des Forges : « La résidence temporaire est financée, critères d’accès publiés. »', blocked: 'Le Courrier des Forges : « Le permis de la résidence temporaire manque. »', delivered: 'Le Courrier des Forges : « La résidence accueille les premières recrues. »', withdrawn: 'Le Courrier des Forges : « Le projet de résidence temporaire est abandonné. »' }), relationships: { regional: 2, social: 1 } }),
      choice({ id: 'aide-mobilite-recrues', title: 'Aider aux trajets pendant six mois', description: 'Financer le transport des nouveaux salariés pendant leur recherche de logement.', cost: '0,06 Md€ pour six mois', benefit: 'Les recrutements peuvent commencer sans attendre un logement.', sacrifice: 'La dépense ne résout pas la distance quotidienne.', effect: effect({ operating: 0.06, cohesion: 1 }), delayed: { after: 1, label: 'L’aide de trajet de six mois prend fin; sa prolongation doit être revotée.', effect: effect({ operating: -0.06 }) }, promise: { id: 'trajets-recrues', label: 'Les nouvelles recrues auront une aide de trajet pendant leur installation.', dueAfter: 1, keepWhen: 'programme_executed' }, relationships: { regional: 1 } }),
      choice({ id: 'logements-non-reserves', title: 'Laisser les locations au marché local', description: 'Ne pas réserver de logements; financer plutôt les annonces et la mise en relation.', cost: '0,04 Md€ de fonctionnement', benefit: 'Les logements restent disponibles à tous les habitants.', sacrifice: 'Les recrues peuvent refuser le poste faute de solution.', effect: effect({ operating: 0.04, services: 1, cohesion: -1 }), relationships: { social: 1, regional: -1 } }),
    ],
  }),

  event({
    id: 'integrite-interets', familyId: 'integrite-ministerielle', title: 'Un marché attribué à un proche',
    body: 'Un membre du cabinet a rencontré une entreprise candidate à un marché, et sa déclaration d’intérêts est incomplète. Aucun favoritisme n’est établi : faut-il publier les échanges et confier le contrôle à une instance indépendante ?',
    turns: [4, 5, 6, 7], contexts: ['redress', 'coalition'],
    choices: [
      choice({ id: 'audit-independant', title: 'Confier le dossier à un audit indépendant', description: 'Publier les pièces autorisées et suspendre l’attribution jusqu’au rapport.', cost: '0,08 Md€ de contrôle', benefit: 'La décision repose sur un examen vérifiable.', sacrifice: 'Le marché et les fournisseurs attendent le rapport.', effect: effect({ operating: 0.08, trust: 3 }), promise: { id: 'audit-marche', label: 'Le contrôle indépendant du marché sera publié.', dueAfter: 1, targetProject: 'audit-marche', keepWhen: 'project_delivered' }, project: P('audit-marche', 'integrity', 'Audit indépendant du marché public', 'gare-des-tilleuls', 1, { funded: 'L’Écho des Tilleuls : « L’audit indépendant est financé; l’attribution attend ses conclusions. »', blocked: 'L’Écho des Tilleuls : « L’audit est bloqué faute d’accès aux pièces. »', delivered: 'L’Écho des Tilleuls : « L’audit publié ne conclut à aucun favoritisme établi; les règles sont corrigées. »', withdrawn: 'L’Écho des Tilleuls : « L’audit est retiré, le doute demeure. »' }), relationships: { reformist: 2, presidential: -1 }, press: 'L’Écho des Tilleuls : « L’attribution est suspendue le temps d’un audit indépendant. »' }),
      choice({ id: 'deport-public', title: 'Publier le déport et reprendre la procédure', description: 'Écarter le membre du cabinet et relancer la comparaison des offres.', cost: '0,03 Md€ de procédure', benefit: 'Les candidats sont évalués sans sa participation.', sacrifice: 'Une relance réduit le temps pour lancer les travaux.', effect: effect({ operating: 0.03, trust: 2 }), amendment: A('amend-declaration-interets', 'Publier les déclarations d’intérêts actualisées', { operating: 0.01, trust: 2 }, 2), relationships: { reformist: 1, presidential: -1 } }),
      choice({ id: 'maintenir-procedure-marche', title: 'Maintenir l’attribution avec une note juridique', description: 'Faire examiner le dossier par le service juridique sans suspendre le marché.', cost: '0,01 Md€ de conseil', benefit: 'Les travaux démarrent au calendrier annoncé.', sacrifice: 'Le public ne voit pas encore les pièces ni l’examen complet.', effect: effect({ operating: 0.01, trust: -2, growth: 0.01 }), relationships: { presidential: 2, reformist: -2 } }),
    ],
  }),
  event({
    id: 'integrite-alerte', familyId: 'integrite-ministerielle', title: 'Une alerte interne reste sans réponse',
    body: 'Une agente affirme que les critères d’un marché public ont peut-être été modifiés au dernier moment. Comment protéger son identité et vérifier les faits sans bloquer inutilement les travaux ?',
    turns: [11, 12, 13, 14],
    choices: [
      choice({ id: 'canal-alerte', title: 'Ouvrir un canal indépendant protégé', description: 'Financer un tiers de réception et des règles de confidentialité contrôlées.', cost: '0,06 Md€ par an', benefit: 'Les alertes peuvent être examinées sans exposer leur auteur.', sacrifice: 'Les enquêtes et protections ralentissent certains achats.', effect: effect({ operating: 0.06, trust: 3 }), promise: { id: 'proteger-alertes', label: 'Les alertes sur les marchés auront un canal indépendant et protégé.', dueAfter: 2, keepWhen: 'programme_executed' }, relationships: { reformist: 2, presidential: -1 } }),
      choice({ id: 'commission-parlementaire', title: 'Mandater une commission parlementaire', description: 'Donner accès aux contrats et demander une audition publique des responsables.', cost: '0,04 Md€ de contrôle', benefit: 'Le contrôle relève du Parlement et produit un calendrier public.', sacrifice: 'Les auditions exposent les équipes aux controverses politiques.', effect: effect({ operating: 0.04, trust: 2 }), amendment: A('amend-acces-pieces', 'Étendre l’accès aux pièces aux représentants de l’opposition', { operating: 0.02, trust: 1 }, 2), relationships: { reformist: 2, presidential: -2 } }),
      choice({ id: 'traitement-interne', title: 'Exiger une réponse du ministère au prochain arbitrage', description: 'Conserver l’instruction en interne et imposer une date de réponse.', cost: '0,01 Md€ de fonctionnement', benefit: 'Le dossier avance sans nouvelle structure.', sacrifice: 'La personne qui reçoit l’alerte dépend du ministère concerné.', effect: effect({ operating: 0.01, trust: -1 }), promise: { id: 'reponse-alerte', label: 'Le ministère publiera sa réponse à l’alerte au prochain arbitrage.', dueAfter: 1, keepWhen: 'programme_executed' }, relationships: { presidential: 1, reformist: -1 } }),
    ],
  }),
  event({
    id: 'integrite-pieces', familyId: 'integrite-ministerielle', title: 'Publier le contrat ou protéger les secrets légitimes ?',
    body: 'Le public veut comprendre le prix d’un marché de rénovation, mais certaines annexes contiennent des secrets industriels. Faut-il publier le contrat avec des passages masqués ou laisser la commission décider pièce par pièce ?',
    turns: [20, 21, 22, 23],
    choices: [
      choice({ id: 'publication-annexes', title: 'Publier le contrat avec occultations justifiées', description: 'Faire relire les annexes et publier les motifs de chaque passage masqué.', cost: '0,05 Md€ d’examen', benefit: 'Les citoyens peuvent comparer prix, critères et engagements.', sacrifice: 'L’examen prend du temps aux équipes d’achat.', effect: effect({ operating: 0.05, trust: 3 }), promise: { id: 'publier-contrats', label: 'Les contrats majeurs seront publiés avec les occultations expliquées.', dueAfter: 2, keepWhen: 'programme_executed' }, relationships: { reformist: 2, presidential: -1 } }),
      choice({ id: 'commission-secret', title: 'Réserver les pièces à la commission', description: 'Transmettre les annexes aux parlementaires habilités et publier un résumé.', cost: '0,02 Md€ de contrôle', benefit: 'Le contrôle parlementaire commence rapidement.', sacrifice: 'Le public ne peut pas vérifier lui-même les prix.', effect: effect({ operating: 0.02, trust: 1 }), amendment: A('amend-synthese-prix', 'Publier aussi les prix unitaires non confidentiels', { operating: 0.01, trust: 1 }, 1), relationships: { presidential: 1, reformist: 1 } }),
      choice({ id: 'garder-annexes-confidentielles', title: 'Garder les annexes confidentielles', description: 'Protéger les clauses et attendre la fin du marché pour toute publication.', cost: 'Aucune dépense nouvelle', benefit: 'Les fournisseurs préservent leurs informations commerciales.', sacrifice: 'Le prix et les engagements restent difficiles à contrôler.', effect: effect({ trust: -2 }), relationships: { presidential: 1, reformist: -2 } }),
    ],
  }),

  event({
    id: 'logement-expulsions', familyId: 'logement', title: 'Le bail se termine dans dix jours',
    body: 'À la Gare-des-Tilleuls, des familles risquent l’expulsion dans les prochains jours. Faut-il financer des hébergements temporaires ou une médiation pour trouver un accord avec les propriétaires ?',
    turns: [3, 4, 5, 6], contexts: ['redress', 'hospital'],
    choices: [
      choice({ id: 'mediation-impayes', title: 'Financer une médiation avant expulsion', description: 'Payer une équipe qui négocie un échéancier avec locataires et bailleurs.', cost: '0,14 Md€ par an', benefit: 'Les ménages ont un interlocuteur avant l’échéance.', sacrifice: 'Une médiation ne peut annuler toutes les dettes.', effect: effect({ operating: 0.14, cohesion: 2, services: 1 }), amendment: A('amend-logement-mediations', 'Ajouter un accompagnement juridique aux médiations', { operating: 0.04, cohesion: 1 }, 2), promise: { id: 'prevenir-expulsions', label: 'Un guichet proposera une médiation avant les expulsions du scénario.', dueAfter: 1, keepWhen: 'services_improved' }, relationships: { social: 2, regional: 1 } }),
      choice({ id: 'hebergement-temporaire', title: 'Réserver des places temporaires', description: 'Louer des logements relais pour les situations urgentes.', cost: '0,5 Md€ par an', benefit: 'Des familles évitent une nuit sans solution.', sacrifice: 'Les places restent temporaires et sont rares.', effect: effect({ operating: 0.5, cohesion: 2 }), promise: { id: 'places-relais', label: 'Des places relais seront disponibles pour les urgences.', dueAfter: 2, keepWhen: 'programme_executed' }, relationships: { regional: 2, social: 1 } }),
      choice({ id: 'prioriser-criteres', title: 'Appliquer les critères habituels', description: 'Ne pas créer de dispositif spécifique et suivre les règles d’attribution actuelles.', cost: 'Aucune dépense nouvelle', benefit: 'Les règles restent identiques pour toutes les demandes.', sacrifice: 'Les situations urgentes peuvent attendre leur tour.', effect: effect({ cohesion: -2, trust: 1 }), relationships: { conservative: 1, social: -2 } }),
    ],
  }),
  event({
    id: 'logement-vacants', familyId: 'logement', title: 'Des logements vides, des listes d’attente',
    body: 'Des logements restent vides après des travaux interrompus alors que des familles attendent. Faut-il aider les bailleurs à les remettre en état, à condition de publier les loyers et les règles d’attribution ?',
    turns: [10, 11, 12, 13],
    choices: [
      choice({ id: 'remise-en-location', title: 'Cofinancer la remise en location', description: 'Verser par étapes après travaux constatés et publication des loyers.', cost: '1,2 Md€ d’investissement', benefit: 'Des logements supplémentaires peuvent être attribués après chantier.', sacrifice: 'Le budget est engagé avant de connaître le nombre final de logements.', effect: effect({ investment: 1.2 }), project: P('logements-remis', 'housing', 'Remise en état de logements vacants', 'gare-des-tilleuls', 2, { funded: 'L’Écho des Tilleuls : « La remise en état est financée, loyers publiés avant les attributions. »', blocked: 'L’Écho des Tilleuls : « Les travaux de remise en location n’ont pas commencé. »', delivered: 'L’Écho des Tilleuls : « Les premiers logements remis en état sont attribués. »', withdrawn: 'L’Écho des Tilleuls : « Le programme de remise en location est retiré. »' }), relationships: { regional: 2, social: 1 } }),
      choice({ id: 'garantie-bailleurs', title: 'Garantir une avance aux bailleurs', description: 'Avancer une partie du financement contre une date de remise en location.', cost: '0,8 Md€ de trésorerie', benefit: 'Les travaux peuvent démarrer plus tôt.', sacrifice: 'Une pénalité devra être récupérée si le délai n’est pas tenu.', effect: effect({ investment: 0.8 }), project: P('garantie-logements', 'housing', 'Avance garantie aux bailleurs', 'gare-des-tilleuls', 1, { funded: 'L’Écho des Tilleuls : « Les avances sont versées contre une échéance de remise en location. »', blocked: 'L’Écho des Tilleuls : « Les avances attendent les garanties des bailleurs. »', delivered: 'L’Écho des Tilleuls : « Les logements garantis sont remis en location dans les délais. »', withdrawn: 'L’Écho des Tilleuls : « Les garanties sont retirées après le retard des travaux. »' }), relationships: { regional: 1, conservative: 1 } }),
      choice({ id: 'mediations-bailleurs', title: 'Financer une équipe de médiation', description: 'Négocier les travaux et attributions sans avance directe au bailleur.', cost: '0,1 Md€ par an', benefit: 'Les obligations sont clarifiées avant financement public.', sacrifice: 'Les logements restent vides pendant les négociations.', effect: effect({ operating: 0.1, trust: 1 }), promise: { id: 'calendrier-logements', label: 'Chaque bailleur participant publiera un calendrier de travaux et d’attribution.', dueAfter: 2, keepWhen: 'programme_executed' }, relationships: { reformist: 1, regional: 1 } }),
    ],
  }),
  event({
    id: 'logement-construction', familyId: 'logement', title: 'Construire près de la gare ou préserver les abords ?',
    body: 'Un terrain près de la gare peut accueillir des logements abordables ou un espace ombragé. Quel projet répond le mieux aux besoins du quartier, et peut obtenir l’accord des habitants et partenaires ?',
    turns: [17, 18, 19, 20],
    choices: [
      choice({ id: 'logements-gare', title: 'Cofinancer le programme près de la gare', description: 'Engager les études et réserver des logements à loyers maîtrisés.', cost: '1,8 Md€ d’investissement', benefit: 'Une offre de logement peut arriver près des transports.', sacrifice: 'Les travaux commencent après les études et l’accord des partenaires.', effect: effect({ investment: 1.8 }), project: P('programme-gare', 'housing', 'Logements à loyers maîtrisés près de la gare', 'gare-des-tilleuls', 3, { funded: 'L’Écho des Tilleuls : « Le programme de la gare est financé, les études commencent. »', blocked: 'L’Écho des Tilleuls : « Le programme de la gare reste bloqué sans accord local. »', delivered: 'L’Écho des Tilleuls : « Les logements de la gare sont livrés avec leurs loyers publiés. »', withdrawn: 'L’Écho des Tilleuls : « Le projet de logements près de la gare est retiré. »' }), relationships: { regional: 2, social: 1 } }),
      choice({ id: 'renover-avant-construire', title: 'Rénover le parc existant', description: 'Réserver les crédits à l’isolation et à l’adaptation des logements actuels.', cost: '0,9 Md€ d’investissement', benefit: 'Les locataires actuels profitent d’un meilleur confort après travaux.', sacrifice: 'Aucun logement supplémentaire n’est créé.', effect: effect({ investment: 0.9 }), project: P('renovation-logements', 'housing', 'Rénovation du parc de logements existants', 'gare-des-tilleuls', 2, { funded: 'L’Écho des Tilleuls : « La rénovation du parc existant est financée. »', blocked: 'L’Écho des Tilleuls : « Les rénovations attendent les relogements temporaires. »', delivered: 'L’Écho des Tilleuls : « Les logements rénovés sont rendus à leurs locataires. »', withdrawn: 'L’Écho des Tilleuls : « La rénovation du parc est abandonnée. »' }), relationships: { social: 2, regional: 1 } }),
      choice({ id: 'terrain-espace-vert', title: 'Préserver le terrain en espace public', description: 'Aménager un espace ombragé et reporter la construction au prochain mandat.', cost: '0,45 Md€ d’investissement', benefit: 'Le quartier gagne un lieu frais et accessible.', sacrifice: 'La liste d’attente pour un logement ne diminue pas.', effect: effect({ investment: 0.45, resilience: 2, cohesion: 1 }), project: P('parc-gare', 'housing', 'Espace public ombragé de la gare', 'gare-des-tilleuls', 1, { funded: 'L’Écho des Tilleuls : « L’espace public ombragé est financé. »', blocked: 'L’Écho des Tilleuls : « Le parc de la gare attend les travaux de sol. »', delivered: 'L’Écho des Tilleuls : « Le nouvel espace ombragé ouvre au quartier. »', withdrawn: 'L’Écho des Tilleuls : « L’aménagement de la gare est retiré. »' }), relationships: { social: 1, conservative: 1 } }),
    ],
  }),

  event({
    id: 'suite-soins-service-bloque', familyId: 'soins-hospitaliers', title: 'Le service des Rives attend toujours ses travaux',
    body: 'Les travaux de l’hôpital des Rives sont bloqués : les patients et les équipes attendent toujours. Faut-il ajouter des crédits, revoir le chantier ou y renoncer ?',
    requiresProject: 'service-rives', requiresProjectStatus: 'blocked',
    choices: [
      choice({ id: 'abandonner-service-rives', title: 'Renoncer à la rénovation des Rives', description: 'Clore le programme et informer les personnes qui attendaient sa livraison.', cost: 'Aucun crédit nouveau', benefit: 'Aucune tranche supplémentaire ne sera engagée.', sacrifice: 'La réalisation ne sera pas livrée ; les sommes déjà engagées ne sont pas récupérées.', effect: effect({ trust: -2, cohesion: -1 }), project: { id: 'service-rives', kind: 'hospital', label: 'Rénovation du service de soins', place: 'hopital-des-rives', dueAfter: 1, action: 'withdraw' } }),
      choice({ id: 'reprendre-service-rives', title: 'Financer la remise en chantier', description: 'Ajouter une tranche ciblée et publier les travaux restant à faire.', cost: '0,25 Md€ d’investissement supplémentaire', benefit: 'Les salles de garde peuvent être terminées après le nouveau vote.', sacrifice: 'Le budget absorbe le retard avant le retour des capacités.', effect: effect({ investment: 0.25, services: 1 }), project: P('service-rives', 'hospital', 'Rénovation du service de soins', 'hopital-des-rives', 2, { delivered: 'La Gazette des Rives : « Après un nouveau vote, les salles de garde rénovées ouvrent. »' }, true), relationships: { social: 1 } }),
      choice({ id: 'reprioriser-service-rives', title: 'Revoir le calendrier avec les équipes', description: 'Réduire le chantier au minimum de sécurité et renégocier les étapes.', cost: '0,05 Md€ d’études', benefit: 'Les services arrêtent les travaux mal séquencés.', sacrifice: 'La rénovation reste bloquée tant qu’aucun nouveau financement n’est voté.', effect: effect({ operating: 0.05, trust: 1 }), relationships: { social: 1, regional: 1 } }),
    ],
  }),
  event({
    id: 'suite-industrie-site-bloque', familyId: 'industrie-conditionnalite', title: 'Le site reste fermé, les emplois attendent',
    body: 'La dépollution de Val-des-Forges est en retard et les salariés attendent la réouverture du site. Faut-il financer une nouvelle tranche, réduire le chantier ou l’abandonner ?',
    requiresProject: 'site-depollue', requiresProjectStatus: 'blocked',
    choices: [
      choice({ id: 'abandonner-site-depollue', title: 'Abandonner la réouverture du site', description: 'Clore le programme et informer les personnes qui attendaient sa livraison.', cost: 'Aucun crédit nouveau', benefit: 'Aucune tranche supplémentaire ne sera engagée.', sacrifice: 'La réalisation ne sera pas livrée ; les sommes déjà engagées ne sont pas récupérées.', effect: effect({ trust: -2, cohesion: -1 }), project: { id: 'site-depollue', kind: 'industry', label: 'Diagnostic et dépollution de l’emprise', place: 'val-des-forges', dueAfter: 1, action: 'withdraw' } }),
      choice({ id: 'reprendre-depollution', title: 'Compléter la dépollution sous contrôle indépendant', description: 'Financer les zones supplémentaires et publier les prélèvements de contrôle.', cost: '0,3 Md€ d’investissement supplémentaire', benefit: 'Le site pourra rouvrir après un nouvel avis indépendant.', sacrifice: 'Les emplois attendent la fin des vérifications.', effect: effect({ investment: 0.3, trust: 1 }), project: P('site-depollue', 'industry', 'Diagnostic et dépollution de l’emprise', 'val-des-forges', 2, { delivered: 'Le Courrier des Forges : « Le site dépollué rouvre après une nouvelle vérification indépendante. »' }, true), relationships: { reformist: 1, regional: 1 } }),
      choice({ id: 'revoir-perimetre-depollution', title: 'Réduire le périmètre industriel', description: 'Limiter le projet aux zones déjà contrôlées et garder le reste fermé.', cost: '0,06 Md€ de contrôle', benefit: 'Les zones sans réserve peuvent avancer.', sacrifice: 'Une partie du terrain reste inutilisable.', effect: effect({ operating: 0.06, trust: 1 }), relationships: { reformist: 1, regional: -1 } }),
    ],
  }),
  event({
    id: 'suite-energie-recharge-bloquee', familyId: 'transition-energetique-mobilite', title: 'Les bus électriques ne sont toujours pas en service',
    body: 'La borne de recharge prévue n’est pas prête et les salariés n’ont toujours pas le bus du soir. Faut-il financer les travaux, louer des bus provisoires ou abandonner l’équipement ?',
    requiresProject: 'recharge-bus', requiresProjectStatus: 'blocked',
    choices: [
      choice({ id: 'abandonner-recharge-bus', title: 'Renoncer aux équipements de recharge', description: 'Clore le programme et informer les personnes qui attendaient sa livraison.', cost: 'Aucun crédit nouveau', benefit: 'Aucune tranche supplémentaire ne sera engagée.', sacrifice: 'La réalisation ne sera pas livrée ; les sommes déjà engagées ne sont pas récupérées.', effect: effect({ trust: -2, cohesion: -1 }), project: { id: 'recharge-bus', kind: 'energy', label: 'Recharge électrique de la ligne de bus', place: 'gare-des-tilleuls', dueAfter: 1, action: 'withdraw' } }),
      choice({ id: 'financer-raccordement-bus', title: 'Financer le raccordement manquant', description: 'Ajouter la tranche de réseau et maintenir les horaires promis après livraison.', cost: '0,22 Md€ d’investissement supplémentaire', benefit: 'La ligne pourra charger ses bus au terminus.', sacrifice: 'Le service attend la fin des travaux et du contrôle électrique.', effect: effect({ investment: 0.22, resilience: 1 }), project: P('recharge-bus', 'energy', 'Recharge électrique de la ligne de bus', 'gare-des-tilleuls', 2, { delivered: 'L’Écho des Tilleuls : « Le raccordement livré permet aux bus électriques de reprendre la ligne. »' }, true), relationships: { regional: 1 } }),
      choice({ id: 'louer-bus-transition', title: 'Louer des bus provisoires', description: 'Maintenir deux départs tardifs avec une flotte louée pendant les travaux.', cost: '0,09 Md€ par an', benefit: 'Les salariés conservent un trajet du soir.', sacrifice: 'La location s’ajoute au coût du futur raccordement.', effect: effect({ operating: 0.09, services: 1, cohesion: 1 }), promise: { id: 'desservir-usine', label: 'Le trajet du soir reste assuré pendant les travaux.', dueAfter: 2, keepWhen: 'services_improved' }, relationships: { regional: 1, social: 1 } }),
    ],
  }),
  event({
    id: 'suite-recrutement-residence-bloquee', familyId: 'recrutement-integration', title: 'Les nouvelles recrues attendent leur logement',
    body: 'La résidence prévue pour les nouvelles recrues n’a pas ouvert, et leur prise de poste approche. Faut-il reprendre les travaux ou financer des trajets temporaires depuis les communes voisines ?',
    requiresProject: 'residence-travail', requiresProjectStatus: 'blocked',
    choices: [
      choice({ id: 'abandon-residence', title: 'Abandonner la résidence des recrues', description: 'Clore le programme et informer les personnes qui attendaient sa livraison.', cost: 'Aucun crédit nouveau', benefit: 'Aucune tranche supplémentaire ne sera engagée.', sacrifice: 'La réalisation ne sera pas livrée ; les sommes déjà engagées ne sont pas récupérées.', effect: effect({ trust: -2, cohesion: -1 }), project: { id: 'residence-travail', kind: 'housing', label: 'Résidence temporaire pour salariés recrutés', place: 'val-des-forges', dueAfter: 1, action: 'withdraw' } }),
      choice({ id: 'reprendre-residence', title: 'Financer l’adaptation au nouveau site', description: 'Reprendre les études et préserver la durée maximale de séjour annoncée.', cost: '0,18 Md€ d’investissement supplémentaire', benefit: 'Les recrues peuvent disposer d’un logement temporaire après livraison.', sacrifice: 'Le déménagement des plans repousse l’ouverture.', effect: effect({ investment: 0.18, cohesion: 1 }), project: P('residence-travail', 'housing', 'Résidence temporaire pour salariés recrutés', 'val-des-forges', 2, { delivered: 'Le Courrier des Forges : « La résidence temporaire ouvre après son transfert sur un site autorisé. »' }, true), relationships: { regional: 1, social: 1 } }),
      choice({ id: 'aide-trajet-residence', title: 'Financer des trajets de substitution', description: 'Aider les nouvelles recrues à rejoindre le bassin depuis les communes voisines.', cost: '0,07 Md€ par an', benefit: 'Les prises de poste peuvent avoir lieu pendant le retard.', sacrifice: 'Le temps de transport remplace provisoirement un logement proche.', effect: effect({ operating: 0.07, cohesion: 1 }), promise: { id: 'trajets-recrues', label: 'Une aide aux trajets couvrira la période de retard.', dueAfter: 2, keepWhen: 'programme_executed' }, relationships: { regional: 1 } }),
    ],
  }),
  event({
    id: 'suite-integrite-audit-bloque', familyId: 'integrite-ministerielle', title: 'L’audit du marché n’est toujours pas rendu',
    body: 'L’audit indépendant du marché public est en retard : le contrat reste sans vérification. Faut-il donner à l’auditeur les pièces manquantes, demander au Parlement de trancher ou arrêter l’audit ?',
    requiresProject: 'audit-marche', requiresProjectStatus: 'blocked',
    choices: [
      choice({ id: 'abandonner-audit-marche', title: 'Mettre fin à l’audit indépendant', description: 'Clore le programme et informer les personnes qui attendaient sa livraison.', cost: 'Aucun crédit nouveau', benefit: 'Aucune tranche supplémentaire ne sera engagée.', sacrifice: 'La réalisation ne sera pas livrée ; les sommes déjà engagées ne sont pas récupérées.', effect: effect({ trust: -2, cohesion: -1 }), project: { id: 'audit-marche', kind: 'integrity', label: 'Audit indépendant du marché public', place: 'gare-des-tilleuls', dueAfter: 1, action: 'withdraw' } }),
      choice({ id: 'ouvrir-pieces-audit', title: 'Ouvrir les pièces à l’auditeur indépendant', description: 'Financer la protection des données et transmettre les annexes utiles.', cost: '0,02 Md€ de contrôle supplémentaire', benefit: 'L’audit peut rendre une conclusion vérifiable.', sacrifice: 'Le marché reste suspendu pendant la vérification.', effect: effect({ operating: 0.02, trust: 2 }), project: P('audit-marche', 'integrity', 'Audit indépendant du marché public', 'gare-des-tilleuls', 1, { delivered: 'L’Écho des Tilleuls : « L’audit a été publié après accès aux pièces; le contrôle relève les règles à corriger. »' }, true), relationships: { reformist: 2 } }),
      choice({ id: 'commission-acces-audit', title: 'Faire trancher l’accès par la commission', description: 'Demander au Parlement de fixer les pièces communicables et les occultations.', cost: '0,015 Md€ de contrôle', benefit: 'Le désaccord d’accès reçoit une règle publique.', sacrifice: 'L’audit ne conclut pas avant la décision parlementaire.', effect: effect({ operating: 0.015, trust: 1 }), amendment: A('amend-acces-pieces-suite', 'Inclure les représentants de l’opposition à l’examen', { operating: 0.005, trust: 1 }, 1), relationships: { reformist: 1, presidential: -1 } }),
    ],
  }),
  event({
    id: 'suite-logement-programme-bloque', familyId: 'logement', title: 'Les familles attendent toujours les logements',
    body: 'Les logements abordables prévus près de la gare ne sont pas livrés, et les familles inscrites attendent. Faut-il financer une première tranche réduite, négocier un nouvel accord ou abandonner le programme ?',
    requiresProject: 'programme-gare', requiresProjectStatus: 'blocked',
    choices: [
      choice({ id: 'abandonner-programme-gare', title: 'Abandonner le programme de la gare', description: 'Clore le programme et informer les personnes qui attendaient sa livraison.', cost: 'Aucun crédit nouveau', benefit: 'Aucune tranche supplémentaire ne sera engagée.', sacrifice: 'La réalisation ne sera pas livrée ; les sommes déjà engagées ne sont pas récupérées.', effect: effect({ trust: -2, cohesion: -1 }), project: { id: 'programme-gare', kind: 'housing', label: 'Logements à loyers maîtrisés près de la gare', place: 'gare-des-tilleuls', dueAfter: 1, action: 'withdraw' } }),
      choice({ id: 'reprendre-programme-gare', title: 'Financer une tranche réduite', description: 'Lancer les logements du premier îlot et garder l’espace public dans la convention.', cost: '0,35 Md€ d’investissement supplémentaire', benefit: 'Une première tranche peut démarrer avec un accord local.', sacrifice: 'Le nombre de logements du programme diminue.', effect: effect({ investment: 0.35, cohesion: 1 }), project: P('programme-gare', 'housing', 'Logements à loyers maîtrisés près de la gare', 'gare-des-tilleuls', 2, { delivered: 'L’Écho des Tilleuls : « Le premier îlot de logements est livré avec sa cour végétalisée. »' }, true), relationships: { regional: 1, social: 1 } }),
      choice({ id: 'convention-logements-gare', title: 'Financer la médiation avant travaux', description: 'Payer une médiation pour résoudre l’accord d’usage du terrain.', cost: '0,03 Md€ de fonctionnement', benefit: 'Les partenaires disposent d’un texte commun à signer.', sacrifice: 'Le chantier reste reporté pendant la discussion.', effect: effect({ operating: 0.03, trust: 1 }), promise: { id: 'accord-programme-gare', label: 'Les partenaires publieront un accord de calendrier pour le programme.', dueAfter: 2, keepWhen: 'programme_executed' }, relationships: { regional: 1 } }),
    ],
  }),
];
