import type { Society } from './types.ts';
export type Reform = { id: string; category: string; group: keyof Society; question: string; cut: string; saving: number; sacrifice: string; tax: string; taxSociety: Partial<Society>; yield: number; taxSacrifice: string; afterCut: string; afterOther: string };
/** Fixed v7 game hypotheses; amounts are not official policy yields. Disjoint envelopes. */
export const REFORMS: readonly Reform[] = [
  {
    "category": "Retraites",
    "group": "pensioners",
    "question": "Faut-il réduire les pensions pour diminuer le déficit ?",
    "cut": "Réduire les pensions hors petites retraites",
    "saving": 15,
    "sacrifice": "Les pensions concernées perdent du pouvoir d’achat.",
    "tax": "Supprimer l’abattement fiscal des pensions",
    "taxSociety": {"pensioners": -3},
    "yield": 4.5,
    "taxSacrifice": "Les retraités imposables paient davantage.",
    "afterCut": "Faut-il compenser les retraités touchés par la baisse ?",
    "afterOther": "Comment financer l’aide à l’autonomie ?",
    "id": "r01"
  },
  {
    "category": "Fonction publique",
    "group": "publicStaff",
    "question": "Faut-il réduire les effectifs administratifs ?",
    "cut": "Ne pas remplacer certains départs administratifs",
    "saving": 10,
    "sacrifice": "Les équipes sont moins nombreuses et les délais augmentent.",
    "tax": "Financer les postes par une contribution sur les hauts revenus",
    "taxSociety": {"affluent": -3},
    "yield": 8,
    "taxSacrifice": "Les contribuables ciblés financent le maintien des emplois.",
    "afterCut": "Que faire face aux guichets débordés ?",
    "afterOther": "Comment réorganiser les services maintenus ?",
    "id": "r02"
  },
  {
    "category": "Consommation",
    "group": "workers",
    "question": "Faire payer la consommation ou réduire les aides ?",
    "cut": "Réduire une enveloppe de soutiens généraux à la consommation",
    "saving": 8,
    "sacrifice": "Les ménages perdent une partie des soutiens du scénario.",
    "tax": "Relever de deux points la TVA normale",
    "taxSociety": {"workers": -2, "vulnerable": -3, "pensioners": -1},
    "yield": 16,
    "taxSacrifice": "Les achats deviennent plus chers pour les consommateurs.",
    "afterCut": "Les ménages privés d’aides doivent-ils être compensés ?",
    "afterOther": "Comment protéger les achats essentiels ?",
    "id": "r03"
  },
  {
    "category": "Entreprises",
    "group": "businesses",
    "question": "Faut-il couper les aides aux grandes entreprises ?",
    "cut": "Supprimer les subventions générales sans contrepartie",
    "saving": 10,
    "sacrifice": "Des entreprises renoncent à des projets et recrutements.",
    "tax": "Réduire les exonérations de cotisations au-dessus des bas salaires",
    "taxSociety": {"businesses": -3},
    "yield": 12,
    "taxSacrifice": "Le travail coûte davantage aux employeurs concernés.",
    "afterCut": "Les entreprises menacent de réduire leurs projets : que faire ?",
    "afterOther": "Faut-il réorienter le soutien vers les petites entreprises ?",
    "id": "r04"
  },
  {
    "category": "Santé",
    "group": "vulnerable",
    "question": "Jusqu’où réduire les remboursements de santé ?",
    "cut": "Restreindre certains remboursements et prises en charge",
    "saving": 10,
    "sacrifice": "Les patients concernés et leurs complémentaires paient davantage.",
    "tax": "Augmenter la contribution maladie sur les revenus élevés",
    "taxSociety": {"affluent": -3},
    "yield": 12,
    "taxSacrifice": "Les assurés aisés contribuent davantage.",
    "afterCut": "Que faire face au renoncement aux soins ?",
    "afterOther": "Comment financer les soins de proximité ?",
    "id": "r05"
  },
  {
    "category": "Protection sociale",
    "group": "vulnerable",
    "question": "Faut-il resserrer l’accès aux prestations ?",
    "cut": "Réserver davantage les prestations aux revenus les plus faibles",
    "saving": 10,
    "sacrifice": "Des ménages proches des plafonds perdent leurs aides.",
    "tax": "Augmenter la contribution sur les revenus du capital",
    "taxSociety": {"affluent": -3},
    "yield": 10,
    "taxSacrifice": "Les revenus de placements des épargnants concernés diminuent.",
    "afterCut": "Que faire pour les ménages exclus des prestations ?",
    "afterOther": "Comment limiter les impayés des ménages fragiles ?",
    "id": "r06"
  },
  {
    "category": "Résidence et aides",
    "group": "newcomers",
    "question": "Faut-il exiger cinq ans de résidence pour certaines aides ?",
    "cut": "Engager une réforme des conditions de résidence",
    "saving": 0,
    "sacrifice": "Le changement juridique doit aboutir avant toute économie. Certains nouveaux résidents perdraient des aides.",
    "tax": "Financer l’intégration par une contribution employeur ciblée",
    "taxSociety": {"businesses": -3},
    "yield": 1,
    "taxSacrifice": "Les employeurs recrutant à l’étranger contribuent davantage.",
    "afterCut": "Comment poursuivre la réforme des cinq ans de résidence ?",
    "afterOther": "Comment améliorer l’accès à l’emploi des nouveaux résidents ?",
    "id": "r07"
  },
  {
    "category": "Associations",
    "group": "vulnerable",
    "question": "Faut-il supprimer les subventions associatives non prioritaires ?",
    "cut": "Supprimer l’enveloppe discrétionnaire hors soins et aide sociale",
    "saving": 6,
    "sacrifice": "Des associations cessent leurs activités et suppriment des emplois.",
    "tax": "Réduire les avantages fiscaux des dons des foyers aisés",
    "taxSociety": {"affluent": -3},
    "yield": 3,
    "taxSacrifice": "Les dons des contribuables concernés coûtent plus cher.",
    "afterCut": "Qui reprend les activités des associations fermées ?",
    "afterOther": "Comment répartir les subventions associatives maintenues ?",
    "id": "r08"
  },
  {
    "category": "Âge de départ",
    "group": "workers",
    "question": "Faut-il travailler un an de plus avant la retraite ?",
    "cut": "Reporter progressivement le départ avec exceptions de pénibilité",
    "saving": 8,
    "sacrifice": "Les actifs concernés travaillent plus longtemps.",
    "tax": "Augmenter les cotisations vieillesse",
    "taxSociety": {"workers": -2, "businesses": -2},
    "yield": 10,
    "taxSacrifice": "Le salaire net ou les marges des employeurs diminuent.",
    "afterCut": "Comment accompagner les seniors qui ne trouvent pas d’emploi ?",
    "afterOther": "Comment améliorer l’emploi en fin de carrière ?",
    "id": "r09"
  },
  {
    "category": "Hôpital",
    "group": "publicStaff",
    "question": "Faut-il regrouper les services hospitaliers ?",
    "cut": "Regrouper les sites et fonctions de soutien du scénario",
    "saving": 6,
    "sacrifice": "Certains patients se déplacent plus loin et les équipes changent de site.",
    "tax": "Augmenter la contribution sur les contrats de complémentaire",
    "taxSociety": {"workers": -2, "pensioners": -2},
    "yield": 5,
    "taxSacrifice": "Les cotisations des assurés peuvent augmenter.",
    "afterCut": "Comment rétablir un accès aux soins dans les zones éloignées ?",
    "afterOther": "Comment réduire l’attente dans les services conservés ?",
    "id": "r10"
  },
  {
    "category": "Rémunérations publiques",
    "group": "publicStaff",
    "question": "Faut-il geler les rémunérations publiques ?",
    "cut": "Geler le point d’indice sur le reste du mandat",
    "saving": 6,
    "sacrifice": "Le pouvoir d’achat des agents diminue.",
    "tax": "Financer les salaires par une contribution sur les bénéfices",
    "taxSociety": {"businesses": -3},
    "yield": 8,
    "taxSacrifice": "Les entreprises concernées conservent moins de bénéfices.",
    "afterCut": "Comment répondre aux tensions de recrutement public ?",
    "afterOther": "Comment rendre les carrières publiques plus attractives ?",
    "id": "r11"
  },
  {
    "category": "Chômage",
    "group": "workers",
    "question": "Faut-il raccourcir l’indemnisation du chômage ?",
    "cut": "Réduire la durée maximale et renforcer la dégressivité",
    "saving": 5,
    "sacrifice": "Les demandeurs d’emploi épuisent leurs droits plus tôt.",
    "tax": "Relever la contribution des entreprises aux contrats courts",
    "taxSociety": {"businesses": -3},
    "yield": 5,
    "taxSacrifice": "Les employeurs utilisant ces contrats paient davantage.",
    "afterCut": "Comment accompagner les chômeurs en fin de droits ?",
    "afterOther": "Comment réduire la précarité des contrats courts ?",
    "id": "r12"
  },
  {
    "category": "Énergie",
    "group": "businesses",
    "question": "Faut-il supprimer les aides aux usages fossiles ?",
    "cut": "Retirer les subventions aux usages fossiles du scénario",
    "saving": 5,
    "sacrifice": "Les usagers sans alternative paient leur énergie plus cher.",
    "tax": "Supprimer des taux fiscaux réduits sur les carburants professionnels",
    "taxSociety": {"businesses": -3},
    "yield": 6,
    "taxSacrifice": "Les secteurs concernés supportent davantage de taxes.",
    "afterCut": "Faut-il aider les secteurs frappés par la fin des aides ?",
    "afterOther": "Comment financer la conversion des usages énergétiques ?",
    "id": "r13"
  },
  {
    "category": "Logement",
    "group": "vulnerable",
    "question": "Faut-il réduire les aides au logement ?",
    "cut": "Resserrer les plafonds hors ménages les plus modestes",
    "saving": 4,
    "sacrifice": "Certains locataires paient une plus grande part du loyer.",
    "tax": "Relever les prélèvements sur les résidences secondaires",
    "taxSociety": {"affluent": -3},
    "yield": 5,
    "taxSacrifice": "Les propriétaires concernés contribuent davantage.",
    "afterCut": "Que faire face aux impayés de loyer ?",
    "afterOther": "Comment financer la remise en location des logements vacants ?",
    "id": "r14"
  },
  {
    "category": "Collectivités",
    "group": "publicStaff",
    "question": "Faut-il mutualiser les services locaux ?",
    "cut": "Regrouper les fonctions de soutien et réduire les postes dédiés",
    "saving": 6,
    "sacrifice": "Des agents changent de poste et certains services s’éloignent.",
    "tax": "Financer les services par une contribution foncière supplémentaire",
    "taxSociety": {"affluent": -3},
    "yield": 6,
    "taxSacrifice": "Les propriétaires concernés paient davantage.",
    "afterCut": "Comment maintenir l’accueil dans les communes éloignées ?",
    "afterOther": "Comment partager les moyens entre communes ?",
    "id": "r15"
  },
  {
    "category": "Recherche",
    "group": "businesses",
    "question": "Faut-il réduire le soutien à la recherche privée ?",
    "cut": "Supprimer certains programmes de subvention à la recherche",
    "saving": 4,
    "sacrifice": "Des projets exploratoires s’arrêtent.",
    "tax": "Plafonner le crédit d’impôt recherche des grands groupes",
    "taxSociety": {"businesses": -3},
    "yield": 4,
    "taxSacrifice": "Les grandes entreprises reçoivent moins de soutien fiscal.",
    "afterCut": "Faut-il sauver les projets de recherche interrompus ?",
    "afterOther": "Comment soutenir les jeunes entreprises innovantes ?",
    "id": "r16"
  },
  {
    "category": "Prestations familiales",
    "group": "affluent",
    "question": "Faut-il réserver davantage les allocations familiales ?",
    "cut": "Réduire les prestations des foyers les plus aisés",
    "saving": 4,
    "sacrifice": "Les familles concernées perdent une partie de leurs allocations.",
    "tax": "Réduire les avantages fiscaux familiaux des hauts revenus",
    "taxSociety": {"affluent": -3},
    "yield": 5,
    "taxSacrifice": "Les ménages concernés paient plus d’impôt.",
    "afterCut": "Comment aider les familles privées d’allocations ?",
    "afterOther": "Comment financer les places d’accueil des enfants ?",
    "id": "r17"
  },
  {
    "category": "Audiovisuel et culture",
    "group": "workers",
    "question": "Faut-il réduire l’offre culturelle financée par l’impôt ?",
    "cut": "Réduire l’audiovisuel public et les subventions aux grands opérateurs",
    "saving": 3,
    "sacrifice": "Des programmes et activités disparaissent.",
    "tax": "Relever les prélèvements sur les plateformes et revenus publicitaires",
    "taxSociety": {"businesses": -3},
    "yield": 3,
    "taxSacrifice": "Les entreprises concernées peuvent répercuter le coût.",
    "afterCut": "Comment préserver une offre d’information de proximité ?",
    "afterOther": "Comment répartir les moyens culturels conservés ?",
    "id": "r18"
  },
  {
    "category": "Action internationale",
    "group": "businesses",
    "question": "Faut-il réduire les dépenses internationales ?",
    "cut": "Réduire les programmes d’aide et de coopération du scénario",
    "saving": 3,
    "sacrifice": "Des programmes cessent et l’influence extérieure diminue.",
    "tax": "Réduire des avantages fiscaux sur les revenus internationaux",
    "taxSociety": {"affluent": -3},
    "yield": 4,
    "taxSacrifice": "Les contribuables concernés paient davantage.",
    "afterCut": "Faut-il rétablir les programmes de coopération supprimés ?",
    "afterOther": "Comment orienter la coopération vers des projets évalués ?",
    "id": "r19"
  },
  {
    "category": "Investissements",
    "group": "workers",
    "question": "Faut-il abandonner de nouveaux grands projets ?",
    "cut": "Réduire durablement l’enveloppe de préparation et de soutien aux projets",
    "saving": 6,
    "sacrifice": "Des infrastructures futures ne seront pas réalisées.",
    "tax": "Relever les droits sur les très grandes successions",
    "taxSociety": {"affluent": -3},
    "yield": 5,
    "taxSacrifice": "Les héritiers concernés reçoivent moins.",
    "afterCut": "Que faire des territoires privés de nouveaux projets ?",
    "afterOther": "Comment sélectionner les projets à lancer ?",
    "id": "r20"
  }
];
