/** Plain-language copy, in the same order as the national campaign dossiers. */
export const NATIONAL_COPY: readonly [string, string, readonly [string, string, string], readonly [string, string, string]][] = [
  [
    'Faut-il changer les impôts ?',
    'Les recettes ne couvrent pas les dépenses publiques prévues. Une hausse ou une baisse des impôts change aussi les budgets des années suivantes.',
    ['Limiter certaines dispenses d’impôt', 'Réduire les impôts', 'Garder les règles actuelles'],
    ['Les contribuables concernés paient davantage et vous font moins confiance.', 'Les contribuables paient moins et vous font plus confiance. Vous avez davantage besoin d’emprunter.', 'Les impôts restent les mêmes. Vous devez financer le manque d’argent autrement.'],
  ],
  [
    'Faut-il réduire ou renforcer les services ?',
    'Vous reprenez des dépenses déjà prévues pour plusieurs années. Certaines financent des aides et des services que les habitants utilisent.',
    ['Réduire des dépenses moins prioritaires', 'Renforcer les services prioritaires', 'Garder les dépenses prévues'],
    ['Certains habitants perdent une aide ou un service.', 'Les habitants reçoivent davantage de services. Le déficit augmente chaque année.', 'Les habitants gardent leurs services. Les recettes ne suffisent toujours pas à les financer.'],
  ],
  [
    'Comment rapprocher les services des villages ?',
    'Dans ce scénario, les habitants des campagnes ont moins de guichets à proximité pour leurs démarches publiques.',
    ['Ajouter des permanences locales', 'Rénover des lieux d’accueil partagés', 'Coordonner les horaires actuels'],
    ['Les habitants trouvent davantage de permanences près de chez eux pour faire leurs démarches.', 'Dans un an, les habitants font leurs démarches dans les locaux rénovés.', 'Les agents coordonnent les horaires et orientent les habitants. Ils ne peuvent pas accueillir plus de monde.'],
  ],
  [
    'Faut-il renforcer les équipes ou le matériel de santé ?',
    'Les équipes de soins ont besoin de collègues et de matériel. Rénover les équipements prend deux ans.',
    ['Renforcer les équipes de soins', 'Moderniser les équipements de santé', 'Donner la priorité à certains soins'],
    ['Les équipes renforcées peuvent prendre en charge davantage de patients.', 'Dans deux ans, les soignants disposent des équipements rénovés pour prendre en charge les patients.', 'Les patients prioritaires accèdent plus facilement aux soins. Les autres ont plus de difficultés.'],
  ],
  [
    'Comment aider les élèves ?',
    'Les élèves ont besoin d’aide dans leur scolarité. Vous pouvez aussi financer du matériel et des bâtiments avec les collectivités.',
    ['Renforcer l’aide aux élèves', 'Participer aux équipements éducatifs', 'Garder le programme actuel'],
    ['Les élèves reçoivent davantage d’aide pour poursuivre leur scolarité.', 'Dans deux ans, les élèves utilisent les équipements modernisés avec les collectivités.', 'Les élèves gardent l’aide actuelle. Ceux qui en demandent davantage doivent attendre.'],
  ],
  [
    'Comment réduire la consommation d’énergie ?',
    'Les entreprises industrielles dépendent de l’énergie et des réseaux. Des travaux ou des conseils peuvent les aider à consommer moins.',
    ['Investir pour consommer moins', 'Financer des conseils techniques', 'Garder les programmes actuels'],
    ['Dans deux ans, les installations consomment moins d’énergie et certaines dépenses de fonctionnement baissent.', 'Les entreprises reçoivent des conseils pour moins dépendre de l’énergie. Leurs installations changent peu.', 'Les entreprises restent aussi dépendantes de l’énergie.'],
  ],
  [
    'Faut-il moderniser ou réparer les infrastructures ?',
    'Des infrastructures publiques ont besoin de travaux. Moderniser un réseau prend deux ans ; réparer ses points fragiles agit dès maintenant.',
    ['Moderniser un réseau prioritaire', 'Réparer les parties fragiles', 'Reporter les nouveaux travaux'],
    ['Vous empruntez avant la livraison. Dans deux ans, les habitants utilisent le réseau modernisé.', 'Les équipes réparent les parties fragiles. Les habitants disposent de peu de services supplémentaires.', 'Les travaux déjà engagés continuent. Vous ne lancez aucun nouvel équipement.'],
  ],
  [
    'Comment réduire le besoin d’emprunter ?',
    'Payer les intérêts de la dette laisse moins d’argent pour les services. Augmenter les impôts ou réduire les dépenses limite les nouveaux emprunts.',
    ['Augmenter les recettes fiscales', 'Réduire des dépenses moins prioritaires', 'Garder le budget prévu'],
    ['Les contribuables paient davantage et vous font moins confiance. Vous avez moins besoin d’emprunter.', 'Les habitants disposent de moins de services. Vous avez moins besoin d’emprunter.', 'Vous devez toujours trouver de quoi financer les dépenses que les recettes ne couvrent pas.'],
  ],
  [
    'Que financer avant de boucler le premier budget ?',
    'Vous avez pris vos premières décisions. Avant de boucler le budget, vous pouvez encore aider les habitants ou réparer des équipements.',
    ['Renforcer les services essentiels', 'Réparer des équipements publics', 'Ne rien ajouter au budget'],
    ['Les habitants reçoivent davantage d’aide et de services pendant le mandat.', 'Les équipes remettent en état une partie des équipements publics.', 'Les programmes décidés continuent. Les habitants qui demandent autre chose doivent attendre.'],
  ],
  [
    'Comment faciliter les démarches fiscales ?',
    'Les contribuables consacrent du temps à leurs démarches. Les agents peuvent les aider directement ou s’équiper pour traiter leurs dossiers.',
    ['Moderniser les outils de traitement', 'Renforcer l’aide aux contribuables', 'Garder les procédures actuelles'],
    ['Dans un an, les agents traitent plus facilement les dossiers et certaines dépenses de fonctionnement baissent.', 'Les contribuables reçoivent davantage d’aide pour leurs démarches et vous font plus confiance.', 'Les contribuables continuent leurs démarches avec les mêmes difficultés.'],
  ],
  [
    'Comment aider les agents à traiter les dossiers ?',
    'Les agents appliquent vos décisions en plus de leurs tâches habituelles. Recruter des collègues ou changer leurs outils peut les aider.',
    ['Renforcer les équipes administratives', 'Équiper les agents de nouveaux outils', 'Réduire les tâches moins prioritaires'],
    ['Les agents disposent de renforts pour traiter les dossiers des habitants.', 'Dans un an, les agents utilisent les nouveaux outils pour traiter plus facilement les dossiers.', 'Les agents traitent mieux les priorités. Les autres demandes sont moins bien servies et la confiance baisse.'],
  ],
  [
    'Que faire des bâtiments publics qui consomment trop ?',
    'Certains bâtiments publics consomment beaucoup d’énergie. Vous pouvez les rénover, les entretenir ou regrouper les activités dans moins de locaux.',
    ['Rénover les bâtiments les plus gourmands', 'Renforcer l’entretien régulier', 'Regrouper les activités dans moins de locaux'],
    ['Dans deux ans, les bâtiments rénovés consomment moins d’énergie et certaines dépenses de fonctionnement baissent.', 'Les équipes entretiennent mieux les bâtiments. Elles ne les rénovent pas entièrement pour réduire les pertes de chaleur.', 'Certains habitants doivent aller plus loin pour trouver un service.'],
  ],
  [
    'Faut-il financer de nouveaux réseaux d’énergie ?',
    'Les entreprises ont besoin de raccorder leurs installations aux réseaux d’énergie. Vous pouvez participer aux travaux avec les opérateurs.',
    ['Participer aux travaux sur le réseau', 'Aider les équipes à préparer les projets', 'Garder le calendrier prévu'],
    ['Dans deux ans, les entreprises industrielles peuvent utiliser les nouveaux raccordements.', 'Les équipes préparent les projets de réseau. Il faudra encore financer les travaux.', 'Les opérateurs gardent leur calendrier : vous ne financez pas de travaux supplémentaires.'],
  ],
  [
    'Comment aider les entreprises industrielles à s’adapter ?',
    'Les entreprises industrielles doivent adapter leurs installations. Leurs salariés peuvent aussi avoir besoin d’aide pour changer de métier.',
    ['Participer à la modernisation industrielle', 'Aider les salariés à changer de métier', 'Utiliser les aides déjà disponibles'],
    ['Dans deux ans, les entreprises utilisent les installations modernisées pour adapter leur production aux crises.', 'Les salariés de l’industrie reçoivent de l’aide pour changer de métier.', 'Les entreprises et les salariés sont orientés vers les aides existantes. Vous n’en financez pas de nouvelles.'],
  ],
  [
    'Comment aider les personnes à changer de métier ?',
    'Les personnes qui changent de métier ont besoin de conseils et de formations. Les régions et les employeurs participent à leur organisation.',
    ['Renforcer l’aide à la reconversion', 'Moderniser les lieux de formation', 'Donner la priorité à certaines formations'],
    ['Les personnes qui changent de métier reçoivent davantage d’aide, au-delà de leur première formation.', 'Dans un an, les personnes en formation utilisent le nouveau matériel et les locaux modernisés.', 'Les personnes qui suivent les formations prioritaires gagnent des créneaux. Les autres en perdent.'],
  ],
  [
    'Comment faciliter l’accès au logement ?',
    'Dans certaines grandes villes du scénario, des ménages peinent à se loger. Remettre des bâtiments en service demande deux ans.',
    ['Participer à la réouverture de bâtiments', 'Renforcer l’aide aux ménages en difficulté', 'Garder les programmes actuels'],
    ['Dans deux ans, les ménages accèdent plus facilement au logement grâce aux bâtiments remis en service.', 'Les ménages reçoivent davantage d’aide dans leurs démarches pour se loger. Aucun logement n’est ajouté.', 'Les ménages continuent de rencontrer les mêmes difficultés pour se loger.'],
  ],
  [
    'Comment réduire les écarts entre villes et campagnes ?',
    'Les habitants des campagnes ont moins de services à proximité. Vous pouvez financer des lieux, ajouter des permanences ou déplacer les moyens.',
    ['Financer des équipements partagés ruraux', 'Ajouter des permanences rurales', 'Réorienter les moyens vers les zones rurales'],
    ['Dans un an, les habitants des campagnes accèdent aux services dans les nouveaux équipements partagés.', 'Les habitants des campagnes trouvent davantage de permanences pour se faire aider.', 'Les habitants des zones moins servies reçoivent davantage d’aide. Ceux des zones mieux dotées en perdent.'],
  ],
  [
    'Faut-il ajuster le budget avant la fin de l’année ?',
    'Les programmes lancés entraînent des dépenses chaque année. Avant de boucler le budget, vous pouvez revoir les dépenses ou les impôts.',
    ['Réduire des dépenses moins prioritaires', 'Augmenter les recettes fiscales', 'Garder les moyens du programme'],
    ['Les habitants disposent de moins de services et vous font moins confiance.', 'Les contribuables paient davantage et vous font moins confiance.', 'Les habitants gardent les services prévus. Vous ne réduisez pas le déficit avec ce choix.'],
  ],
  [
    'Comment réagir au ralentissement économique ?',
    'Dans ce scénario, les revenus souffrent du ralentissement économique. Davantage de personnes demandent de l’aide aux services publics.',
    ['Financer une aide pendant un an', 'Financer des réparations d’infrastructures', 'Répartir autrement les aides existantes'],
    ['Les personnes touchées reçoivent une aide cette année. Elle prend fin l’année suivante.', 'Les équipes réparent les infrastructures. Les personnes qui perdent des revenus en tirent peu d’aide immédiate.', 'Les aides vont d’abord aux demandes prioritaires. Certains bénéficiaires en reçoivent moins.'],
  ],
  [
    'Faut-il aider les ménages un an ou plus longtemps ?',
    'Des ménages ont besoin d’aide pendant la crise. Vous pouvez leur accorder une aide pour cette année ou une aide plus petite qui continue ensuite.',
    ['Créer une aide exceptionnelle d’un an', 'Créer une aide durable plus petite', 'Utiliser les aides actuelles'],
    ['Les ménages reçoivent une aide et vous font plus confiance. Cette aide prend fin l’année suivante.', 'Les ménages reçoivent une aide plus petite, qui continue après la crise.', 'Les ménages peuvent demander les aides existantes. Vous n’en ajoutez pas pour la crise.'],
  ],
  [
    'Comment répondre à la hausse des dépenses d’énergie ?',
    'La crise énergétique touche les entreprises industrielles. Une aide paie une partie de leurs dépenses ; moderniser les installations prend un an.',
    ['Aider les entreprises touchées pendant un an', 'Moderniser pour consommer moins d’énergie', 'Aider à changer la consommation d’énergie'],
    ['Les entreprises reçoivent une aide pendant un an. Elles restent aussi dépendantes de l’énergie.', 'Dans un an, les entreprises consomment moins d’énergie et certaines dépenses de fonctionnement baissent.', 'Les entreprises adaptent leur consommation. Elles doivent supporter davantage les difficultés de la crise.'],
  ],
  [
    'Comment faire face aux files d’attente ?',
    'La crise augmente les demandes de services publics. Vous pouvez renforcer les équipes, aménager l’accueil ou traiter certains dossiers en premier.',
    ['Renforcer durablement les services', 'Aménager les lieux d’accueil', 'Traiter d’abord les demandes urgentes'],
    ['Les agents peuvent prendre en charge davantage de demandes. Il faudra financer ce renfort après la crise.', 'Les agents accueillent les habitants dans des locaux réaménagés. Ils restent aussi nombreux.', 'Les agents traitent mieux les urgences. Les autres habitants attendent davantage.'],
  ],
  [
    'Que faire quand le budget reçoit moins d’argent ?',
    'Avec le ralentissement, les recettes suffisent encore moins à payer les dépenses. Changer les impôts ou les aides aura un effet après la crise.',
    ['Augmenter les recettes fiscales', 'Réduire certaines aides moins prioritaires', 'Garder les recettes et les services actuels'],
    ['Les contribuables paient davantage, même après la crise, et vous font moins confiance.', 'Certains habitants reçoivent moins d’aide et disposent de moins de services.', 'Les habitants gardent leurs services. Les recettes ne suffisent toujours pas à payer les dépenses.'],
  ],
  [
    'Comment se préparer aux difficultés de livraison ?',
    'Dans ce scénario, certains biens essentiels sont plus difficiles à obtenir. Les équipes publiques peuvent préparer les livraisons avec leurs partenaires.',
    ['Moderniser les installations de livraison', 'Surveiller les difficultés de livraison', 'Donner la priorité à certaines livraisons'],
    ['Dans un an, les équipes disposent d’installations modernisées pour faire face aux difficultés de livraison.', 'Les équipes repèrent les difficultés de livraison et se coordonnent avec leurs partenaires. Le matériel change peu.', 'Les équipes partagent les informations et donnent la priorité à certaines livraisons. D’autres sont moins bien servies.'],
  ],
  [
    'Comment mieux protéger les territoires côtiers ?',
    'Les territoires côtiers du scénario sont exposés aux risques climatiques. Les collectivités peuvent protéger les équipements ou préparer leurs équipes.',
    ['Participer aux travaux de protection', 'Aider les équipes locales à se préparer', 'Garder les plans de prévention actuels'],
    ['Dans deux ans, les infrastructures côtières rénovées résistent mieux aux risques climatiques.', 'Les équipes locales organisent la prévention et l’entraide. Les infrastructures restent exposées.', 'Les équipes réorganisent la prévention avec les plans actuels. Elles ne reçoivent aucun nouvel équipement.'],
  ],
  [
    'Comment financer les dépenses de crise ?',
    'Les aides de crise ajoutent des dépenses. Augmenter les impôts ou réduire certains services limite ce que vous devrez emprunter.',
    ['Réduire des dépenses moins prioritaires', 'Augmenter les recettes fiscales', 'Garder les moyens engagés'],
    ['Les habitants perdent une partie des services en pleine crise.', 'Les contribuables paient davantage pour financer la crise et vous font moins confiance.', 'Les habitants gardent leurs services. Vous devez toujours financer le manque d’argent par l’emprunt.'],
  ],
  [
    'Que financer à la sortie de la crise ?',
    'La période la plus difficile passe. Les aides temporaires approchent de leur fin ; des habitants ont encore besoin d’aide et des équipements de réparations.',
    ['Réparer les équipements fragilisés', 'Créer une aide de proximité durable', 'Reprendre le programme déjà prévu'],
    ['Les équipes remettent en état une partie des équipements fragilisés.', 'Les habitants reçoivent une aide qui continuera après la fin des aides exceptionnelles.', 'Les aides temporaires prennent fin aux dates prévues. Vous n’ajoutez pas d’aide pour la suite.'],
  ],
  [
    'Comment faire fonctionner les équipements ouverts ?',
    'Les agents doivent apprendre à utiliser les équipements en service. Vous pouvez compléter les aménagements ou financer leur travail quotidien.',
    ['Compléter les aménagements', 'Renforcer le fonctionnement quotidien', 'Garder les moyens prévus'],
    ['Les habitants utilisent plus facilement les équipements grâce aux nouveaux aménagements.', 'Les agents reçoivent davantage de moyens pour faire fonctionner les équipements et accueillir les habitants.', 'Les agents mettent plus de temps à résoudre les difficultés d’utilisation des équipements.'],
  ],
  [
    'Comment améliorer le travail des services publics ?',
    'Les agents doivent apprendre à travailler avec les nouveaux outils. Vous pouvez les aider à changer leurs méthodes ou supprimer certaines tâches.',
    ['Aider les équipes à changer leurs pratiques', 'Supprimer des tâches moins prioritaires', 'Garder les méthodes actuelles'],
    ['Vous financez l’aide dès maintenant. Dans un an, les agents utilisent mieux leurs outils pour rendre les services.', 'Les agents abandonnent certaines tâches. Les habitants disposent de moins de services.', 'Les agents continuent à travailler avec leurs méthodes actuelles.'],
  ],
  [
    'Que faire quand les intérêts pèsent sur le budget ?',
    'Payer les intérêts de la dette laisse moins d’argent pour les services et les travaux. Vous pouvez augmenter les impôts ou réduire les dépenses.',
    ['Augmenter les recettes fiscales', 'Réduire des dépenses moins prioritaires', 'Garder les engagements prévus'],
    ['Les contribuables paient davantage et vous font moins confiance. Vous avez moins besoin d’emprunter.', 'Les habitants disposent de moins de services. Vous avez moins besoin d’emprunter.', 'Le programme continue. Vous devez encore réserver une partie du budget au paiement des intérêts.'],
  ],
  [
    'Faut-il réduire un peu le déficit ?',
    'Vous pouvez réduire certaines dépenses ou augmenter un peu les impôts. Les travaux déjà engagés restent à payer.',
    ['Réduire un peu les dépenses courantes', 'Augmenter un peu les recettes fiscales', 'Garder le budget actuel'],
    ['Les agents ont moins de moyens pour rendre certains services aux habitants.', 'Les contribuables paient un peu plus et vous font moins confiance.', 'Les recettes et les dépenses restent les mêmes. Vous ne réduisez pas le déficit avec ce choix.'],
  ],
  [
    'Comment rendre les services plus proches à la campagne ?',
    'Des habitants des campagnes restent loin de certains services. Des lieux partagés ou des équipes mobiles peuvent les aider près de chez eux.',
    ['Participer à des lieux d’accueil partagés', 'Renforcer les équipes mobiles', 'Partager autrement les horaires existants'],
    ['Dans un an, les habitants font leurs démarches dans les nouveaux lieux d’accueil près de chez eux.', 'Les équipes mobiles aident davantage les habitants des campagnes près de chez eux.', 'Les habitants des lieux moins servis gagnent des créneaux d’accueil. D’autres en perdent.'],
  ],
  [
    'Comment entretenir les infrastructures qui vieillissent ?',
    'Les infrastructures s’usent pendant que les nouveaux projets avancent. Les équipes doivent aussi entretenir les équipements déjà utilisés.',
    ['Remplacer les éléments les plus abîmés', 'Renforcer l’entretien préventif', 'Garder le programme d’entretien actuel'],
    ['Les équipes remplacent les éléments abîmés. Il reste moins d’argent pour lancer d’autres projets.', 'Les équipes entretiennent les infrastructures et préviennent les incidents.', 'Les réparations prévues ne rattrapent pas toute l’usure. Les infrastructures se dégradent.'],
  ],
  [
    'Faut-il renforcer la recherche pour les années à venir ?',
    'Les chercheurs ont besoin d’équipements et de financements réguliers. Leurs travaux peuvent se poursuivre au-delà de votre mandat.',
    ['Moderniser les équipements de recherche', 'Financer davantage les travaux de recherche', 'Garder les programmes déjà engagés'],
    ['Les chercheurs recevront les nouveaux équipements dans deux ans, après la fin du mandat.', 'Les chercheurs peuvent poursuivre davantage de travaux. Le financement ne garantit aucune découverte.', 'Les chercheurs poursuivent les programmes engagés avec les financements actuels.'],
  ],
  [
    'Comment financer la protection sociale après la crise ?',
    'Des habitants ont encore besoin d’aide après la crise. Vous pouvez renforcer leur accompagnement ou augmenter les recettes de la protection sociale.',
    ['Renforcer une aide ciblée', 'Augmenter les recettes de protection sociale', 'Garder les aides actuelles'],
    ['Les habitants concernés reçoivent davantage d’aide. Le déficit augmente durablement.', 'Les personnes concernées contribuent davantage à la protection sociale et vous font moins confiance.', 'Les habitants gardent les aides actuelles. Ceux qui en demandent davantage doivent attendre.'],
  ],
  [
    'Faut-il lancer des travaux livrés après votre mandat ?',
    'Des travaux peuvent protéger les infrastructures contre les crises futures. Ils prennent deux ans et se termineraient après votre départ.',
    ['Lancer le programme de travaux de deux ans', 'Réparer quelques équipements maintenant', 'Laisser le prochain mandat décider'],
    ['Dans deux ans, après votre départ, les infrastructures rénovées résistent mieux aux crises.', 'Les équipes réparent une partie des équipements dès maintenant.', 'Le prochain mandat devra décider s’il lance les travaux et comment les financer.'],
  ],
  [
    'Faut-il ajouter une dernière aide ?',
    'Les aides exceptionnelles ont chacune leur date de fin. Vous pouvez en créer une pour votre dernière année ou une plus petite qui continue ensuite.',
    ['Créer une dernière aide d’un an', 'Créer une aide durable plus petite', 'Ne pas ajouter de nouvelle aide'],
    ['Les habitants concernés reçoivent une aide cette année. Elle prend fin après le mandat.', 'Les habitants concernés reçoivent une aide plus petite. Le prochain mandat devra continuer à la financer.', 'Les aides décidées suivent leur calendrier. Certains habitants auront encore besoin d’aide après leur fin.'],
  ],
  [
    'Comment suivre les programmes avant votre départ ?',
    'Le prochain mandat doit savoir quels programmes sont terminés, en travaux ou refusés, et quels engagements il doit respecter.',
    ['Renforcer l’équipe de suivi', 'Moderniser les outils de suivi', 'Transmettre le suivi actuel'],
    ['Davantage d’agents suivent les programmes et évaluent l’état des équipements publics.', 'Les agents disposent de nouveaux outils pour suivre les équipements publics.', 'Les agents transmettent les dossiers avec leurs outils et leurs moyens actuels.'],
  ],
  [
    'Quels moyens laisser aux services du quotidien ?',
    'Les habitants auront toujours besoin des services publics après votre départ. Vous pouvez renforcer les équipes d’accueil ou améliorer leurs locaux.',
    ['Renforcer les équipes d’accueil', 'Adapter les installations existantes', 'Garder les moyens actuels'],
    ['Les agents peuvent accueillir davantage d’habitants. Le prochain mandat devra financer ces renforts.', 'Les habitants sont mieux accueillis dans les locaux aménagés. Les agents restent aussi nombreux.', 'Les agents gardent leurs moyens actuels. Certaines demandes des habitants restent sans réponse.'],
  ],
  [
    'Faut-il réparer encore les infrastructures ?',
    'L’état des infrastructures dépend des travaux financés pendant le mandat. Vous pouvez encore réparer les éléments abîmés ou renforcer leur entretien.',
    ['Réparer les éléments les plus abîmés', 'Renforcer l’entretien régulier', 'Garder le programme existant'],
    ['Les équipes réparent les éléments abîmés pour limiter les incidents. Ces travaux ajoutent de la dette.', 'Les équipes entretiennent mieux les infrastructures. Le prochain mandat devra continuer à le financer.', 'Les équipes font les travaux prévus. Le retard d’entretien restant n’est pas réduit.'],
  ],
  [
    'Comment préparer les services à une prochaine crise ?',
    'Les équipes peuvent préparer les équipements et organiser l’aide en cas de crise, même si vous ne savez pas quand elle arrivera.',
    ['Moderniser les équipements de prévention', 'Aider les équipes locales à se préparer', 'Garder les moyens de préparation actuels'],
    ['Les équipes disposent d’équipements modernisés pour faire face aux crises.', 'Les équipes organisent la prévention et l’entraide. Vous financez ce travail même si aucune crise ne survient.', 'Les équipes gardent les programmes actuels. Vous n’ajoutez aucune protection.'],
  ],
  [
    'Quels impôts laisser pour le prochain mandat ?',
    'Votre dernier choix fiscal change les recettes des prochaines années. Réduire les impôts laisse moins d’argent au prochain budget.',
    ['Augmenter les recettes fiscales', 'Réduire les impôts', 'Garder les règles fiscales actuelles'],
    ['Les contribuables concernés paient davantage et vous font moins confiance.', 'Les contribuables paient moins et vous font plus confiance. Le prochain budget reçoit moins d’argent.', 'Le prochain mandat reçoit les recettes prévues par les règles fiscales actuelles.'],
  ],
  [
    'Faut-il encore réduire le besoin d’emprunter ?',
    'Augmenter les impôts ou réduire les dépenses limite les nouveaux emprunts. Vous devrez toujours rembourser la dette déjà accumulée.',
    ['Réduire des dépenses moins prioritaires', 'Augmenter les recettes fiscales', 'Garder les engagements actuels'],
    ['Les habitants disposent de moins de services. Vous avez moins besoin d’emprunter.', 'Les contribuables paient davantage et vous font moins confiance. Vous avez moins besoin d’emprunter.', 'Les habitants gardent leurs services. Vous ne réduisez pas le besoin d’emprunter avec ce choix.'],
  ],
  [
    'Faut-il laisser un nouveau chantier au prochain mandat ?',
    'Un nouveau programme ouvrirait des équipements pour les services publics dans deux ans. Le prochain mandat devrait aussi payer leur fonctionnement.',
    ['Lancer un programme pour les services futurs', 'Réparer les équipements existants', 'Laisser le prochain mandat choisir'],
    ['Dans deux ans, les habitants utilisent les nouveaux équipements. Le prochain mandat paie alors leur fonctionnement.', 'Les équipes réparent une partie des équipements dès maintenant.', 'Le prochain mandat devra choisir le projet et son financement. Vous ne lancez aucun nouvel équipement.'],
  ],
  [
    'Quel dernier choix laisser au prochain mandat ?',
    'Vous arrivez au bilan des 45 décisions et des cinq budgets. Vous pouvez encore renforcer l’aide aux habitants ou augmenter les impôts pour la suite.',
    ['Renforcer durablement l’accompagnement', 'Augmenter les recettes fiscales', 'Terminer sans nouvel engagement'],
    ['Les habitants reçoivent davantage d’aide et de services. Le prochain mandat devra continuer à les financer.', 'Les contribuables paient davantage et vous font moins confiance. Le prochain budget reçoit plus d’argent.', 'Vous présentez les travaux réalisés, les engagements à tenir et les demandes encore sans réponse.'],
  ],
];
