/** Plain-language copy, in the same order as the national campaign dossiers. */
export const NATIONAL_COPY: readonly [string, string, readonly [string, string, string], readonly [string, string, string]][] = [
  [
    'Faut-il changer les impôts ?',
    'L’argent reçu ne couvre pas les dépenses publiques prévues. Vous pouvez modifier les impôts, avec un effet sur les budgets suivants.',
    ['Limiter certaines dispenses d’impôt', 'Réduire les impôts', 'Garder les règles actuelles'],
    ['Certains contribuables paient davantage et la confiance baisse.', 'Les contribuables paient moins, mais le budget reçoit moins chaque année.', 'Le budget ne reçoit aucun revenu supplémentaire.'],
  ],
  [
    'Faut-il réduire ou renforcer les services ?',
    'Des dépenses reviennent déjà chaque année. Les réduire libère de l’argent, mais peut supprimer des services utiles.',
    ['Réduire des dépenses moins prioritaires', 'Renforcer les services prioritaires', 'Garder les dépenses prévues'],
    ['Le budget dépense moins chaque année, mais des bénéficiaires perdent un service.', 'Les services progressent, avec une dépense supplémentaire chaque année.', 'Les services sont maintenus et le manque d’argent reste à financer.'],
  ],
  [
    'Comment rapprocher les services des villages ?',
    'Dans ce scénario, les habitants des zones rurales ont moins de lieux d’accueil pour leurs démarches publiques.',
    ['Ajouter des permanences locales', 'Rénover des lieux d’accueil partagés', 'Mieux coordonner les horaires actuels'],
    ['L’accueil de proximité progresse, avec des dépenses chaque année.', 'Les locaux et l’accueil s’améliorent dans un an.', 'L’organisation change, mais le nombre de personnes accueillies reste limité.'],
  ],
  [
    'Faut-il renforcer les équipes ou le matériel de santé ?',
    'Les soins ont besoin de personnel et d’équipements adaptés. Les deux choix ne produisent pas leurs effets au même moment.',
    ['Renforcer les équipes de soins', 'Moderniser les équipements de santé', 'Donner la priorité à certains soins'],
    ['La prise en charge progresse, avec des dépenses chaque année.', 'Les équipements et les soins s’améliorent dans deux ans.', 'Les soins prioritaires progressent, mais d’autres deviennent moins accessibles.'],
  ],
  [
    'Comment améliorer l’aide aux élèves ?',
    'Il faut soutenir les élèves et améliorer les équipements éducatifs. Les travaux se préparent avec les collectivités.',
    ['Renforcer le soutien aux élèves', 'Participer aux équipements éducatifs', 'Garder le programme actuel'],
    ['Le soutien progresse dès maintenant et doit être financé chaque année.', 'Les équipements et l’accès à l’éducation progressent dans deux ans.', 'Les besoins supplémentaires restent sans réponse.'],
  ],
  [
    'Comment moins dépendre de l’énergie ?',
    'Les zones industrielles dépendent de l’énergie et de ses réseaux. Réduire leur consommation demande des travaux ou un appui technique.',
    ['Investir pour consommer moins', 'Financer des conseils techniques', 'Garder les programmes actuels'],
    ['Dans deux ans, les installations sont mieux préparées aux chocs et certaines dépenses diminuent.', 'La préparation s’améliore, mais les installations changent peu.', 'La dépendance actuelle à l’énergie demeure.'],
  ],
  [
    'Faut-il moderniser ou réparer les infrastructures ?',
    'Des infrastructures publiques ont besoin de travaux. Une grande modernisation prend plus de temps que des réparations ciblées.',
    ['Moderniser un réseau prioritaire', 'Réparer les parties fragiles', 'Reporter les nouveaux travaux'],
    ['Les infrastructures et les services progressent dans deux ans ; il faut financer les travaux maintenant.', 'L’état des infrastructures s’améliore, avec peu de nouveaux services.', 'Les travaux déjà engagés continuent, sans ajout de nouveaux équipements.'],
  ],
  [
    'Comment réduire le besoin d’emprunter ?',
    'Les intérêts de la dette prennent de l’argent au budget. Recevoir plus ou dépenser moins peut limiter les nouveaux emprunts.',
    ['Augmenter les recettes fiscales', 'Réduire des dépenses moins prioritaires', 'Garder le budget prévu'],
    ['Le budget reçoit plus chaque année, mais les contribuables paient davantage.', 'Le budget dépense moins chaque année, mais certains services reculent.', 'Le besoin d’emprunter n’est pas réduit par ce choix.'],
  ],
  [
    'Que financer avant de fermer le premier budget ?',
    'Vos premiers choix sont pris. Vous pouvez encore renforcer les services ou entretenir les équipements publics.',
    ['Renforcer les services essentiels', 'Réparer des équipements publics', 'Ne rien ajouter au budget'],
    ['Les services et le soutien progressent, avec une dépense chaque année.', 'L’état des équipements s’améliore grâce aux travaux financés cette année.', 'Les demandes nouvelles attendent ; les programmes décidés continuent.'],
  ],
  [
    'Comment faciliter les démarches fiscales ?',
    'Les démarches liées aux impôts prennent du temps. De meilleurs outils ou davantage d’aide peuvent les faciliter.',
    ['Moderniser les outils de traitement', 'Renforcer l’aide aux contribuables', 'Garder les procédures actuelles'],
    ['Dans un an, les démarches s’améliorent et certaines dépenses diminuent.', 'L’aide et la confiance progressent, avec des dépenses chaque année.', 'Les difficultés dans les démarches restent les mêmes.'],
  ],
  [
    'Comment aider les agents à traiter les dossiers ?',
    'Les agents doivent appliquer vos décisions en plus de leurs tâches habituelles. Renforcer les équipes ou leurs outils demande des moyens.',
    ['Renforcer les équipes administratives', 'Équiper les agents de nouveaux outils', 'Réduire les tâches moins prioritaires'],
    ['Le traitement des dossiers s’améliore, avec une dépense chaque année.', 'Les nouveaux outils améliorent les services dans un an.', 'Les demandes prioritaires sont mieux servies, mais d’autres le sont moins.'],
  ],
  [
    'Que faire des bâtiments publics qui consomment trop ?',
    'Certains bâtiments publics consomment beaucoup d’énergie. Les rénover, les entretenir ou regrouper les activités a des effets différents.',
    ['Rénover les bâtiments les plus gourmands', 'Renforcer l’entretien régulier', 'Regrouper les activités dans moins de locaux'],
    ['Dans deux ans, les bâtiments sont en meilleur état et certaines dépenses diminuent.', 'Les bâtiments sont mieux entretenus, sans rénovation complète contre les pertes de chaleur.', 'Les dépenses baissent, mais certains services deviennent moins proches.'],
  ],
  [
    'Faut-il financer de nouveaux réseaux d’énergie ?',
    'De nouveaux usages ont besoin de réseaux adaptés. Les pouvoirs publics peuvent participer aux travaux avec les opérateurs.',
    ['Participer aux travaux sur le réseau', 'Financer la préparation des projets', 'Garder le calendrier prévu'],
    ['Le réseau est amélioré dans deux ans, notamment dans les zones industrielles.', 'Les projets sont mieux préparés, mais les travaux restent à financer.', 'Aucun financement supplémentaire ne vient accélérer le programme.'],
  ],
  [
    'Comment aider les zones industrielles à s’adapter ?',
    'Les zones industrielles demandent une aide pour moderniser leurs installations et accompagner les changements de métier.',
    ['Participer à la modernisation industrielle', 'Accompagner les changements de métier', 'Utiliser les aides déjà disponibles'],
    ['Les installations et la préparation aux chocs progressent dans deux ans.', 'L’accompagnement des personnes progresse et doit être financé chaque année.', 'Les demandes sont orientées vers les aides existantes, sans moyens supplémentaires.'],
  ],
  [
    'Comment aider les personnes à changer de métier ?',
    'Changer de métier demande un accompagnement et des lieux de formation adaptés. Les régions et les employeurs participent aussi.',
    ['Renforcer l’aide à la reconversion', 'Moderniser les lieux de formation', 'Donner la priorité à certaines formations'],
    ['Les personnes sont mieux accompagnées, avec des dépenses chaque année.', 'Le matériel et les services de formation s’améliorent dans un an.', 'Certaines formations gagnent des places, mais d’autres en perdent.'],
  ],
  [
    'Comment améliorer l’accès au logement ?',
    'Dans certaines grandes villes du scénario, se loger est difficile. Remettre des bâtiments en usage prend du temps.',
    ['Participer à la remise en usage de bâtiments', 'Renforcer l’aide aux ménages en difficulté', 'Garder les programmes actuels'],
    ['L’accès au logement s’améliore dans deux ans, avec les partenaires locaux.', 'L’accompagnement progresse, mais aucun logement supplémentaire n’est créé par ce choix.', 'Les difficultés d’accès au logement persistent.'],
  ],
  [
    'Comment réduire les écarts entre villes et campagnes ?',
    'Les habitants des zones rurales ont moins accès à certains services. Vous pouvez financer des lieux, des permanences ou changer les priorités.',
    ['Financer des équipements partagés ruraux', 'Ajouter des permanences rurales', 'Réorienter les moyens vers les zones rurales'],
    ['Les nouveaux équipements améliorent l’accès aux services dans un an.', 'Les services de proximité progressent, avec une dépense chaque année.', 'Les zones moins servies sont prioritaires, mais d’autres perdent un avantage.'],
  ],
  [
    'Faut-il ajuster le budget avant la fin de l’année ?',
    'Les programmes lancés ont un coût qui dure. Vous pouvez réduire certaines dépenses, recevoir plus d’impôts ou garder le programme.',
    ['Réduire des dépenses moins prioritaires', 'Augmenter les recettes fiscales', 'Garder les moyens du programme'],
    ['Les dépenses baissent, mais certains services et la confiance reculent.', 'Les contribuables paient davantage chaque année et la confiance baisse.', 'Les services gardent leurs moyens ; ce choix ne réduit pas le déficit.'],
  ],
  [
    'Comment réagir au ralentissement économique ?',
    'Dans ce scénario, l’activité ralentit et les besoins d’aide augmentent. Un soutien d’un an et des travaux répondent à des besoins différents.',
    ['Financer une aide pendant un an', 'Financer des réparations d’infrastructures', 'Répartir autrement les aides existantes'],
    ['Le soutien progresse cette année ; la dépense s’arrête l’année suivante.', 'Les infrastructures sont en meilleur état, mais ce choix aide peu les revenus immédiatement.', 'Les besoins prioritaires passent d’abord, mais certains bénéficiaires sont moins aidés.'],
  ],
  [
    'Faut-il aider les ménages un an ou plus longtemps ?',
    'La crise crée de nouveaux besoins. Vous pouvez ajouter une aide pour cette année ou une aide plus petite qui continue ensuite.',
    ['Créer une aide exceptionnelle d’un an', 'Créer une aide durable plus petite', 'Utiliser les aides actuelles'],
    ['Le soutien et la confiance progressent ; la dépense prend fin l’année suivante.', 'Le soutien progresse moins, mais sa dépense continue après la crise.', 'Les aides existantes continuent sans moyen supplémentaire.'],
  ],
  [
    'Comment répondre à la hausse des dépenses d’énergie ?',
    'La crise énergétique touche les zones industrielles. Une aide agit cette année ; moderniser les installations demande un an.',
    ['Aider les usages les plus touchés pendant un an', 'Moderniser pour consommer moins d’énergie', 'Adapter les usages avec les moyens actuels'],
    ['Le soutien progresse cette année, mais la dépendance à l’énergie reste la même.', 'Dans un an, la préparation aux chocs progresse et certaines dépenses diminuent.', 'La préparation progresse, mais les personnes touchées supportent davantage les difficultés.'],
  ],
  [
    'Comment faire face aux files d’attente ?',
    'La crise augmente les demandes de services publics. Vous pouvez renforcer les moyens, adapter l’accueil ou choisir les demandes prioritaires.',
    ['Renforcer durablement les services', 'Aménager les lieux d’accueil', 'Traiter d’abord les demandes urgentes'],
    ['La prise en charge progresse, avec des dépenses qui continuent après la crise.', 'L’accueil et les locaux s’améliorent, sans personnel supplémentaire.', 'Les urgences sont mieux traitées, mais d’autres demandes attendent davantage.'],
  ],
  [
    'Que faire quand le budget reçoit moins d’argent ?',
    'Le ralentissement rend le budget plus difficile à équilibrer. Augmenter les impôts ou réduire les aides aurait un effet durable.',
    ['Augmenter les recettes fiscales', 'Réduire certaines aides moins prioritaires', 'Garder les recettes et les services actuels'],
    ['Les contribuables paient davantage, même après la crise.', 'Les dépenses diminuent, mais certains besoins sont moins bien couverts.', 'Les services sont maintenus ; le manque d’argent reste à financer.'],
  ],
  [
    'Comment se préparer aux difficultés de livraison ?',
    'Dans ce scénario, certains biens essentiels deviennent plus difficiles à obtenir. Mieux s’organiser ou moderniser les installations a un coût.',
    ['Moderniser les installations de livraison', 'Mieux surveiller et coordonner les besoins', 'Donner la priorité aux usages essentiels'],
    ['Les installations et la préparation aux pénuries progressent dans un an.', 'La préparation progresse, avec peu d’équipements supplémentaires.', 'Les besoins prioritaires passent d’abord, mais certains usages reçoivent moins.'],
  ],
  [
    'Comment mieux protéger les territoires côtiers ?',
    'Les territoires côtiers du scénario sont exposés aux risques climatiques. Les travaux et la préparation des équipes n’agissent pas au même rythme.',
    ['Participer aux travaux de protection', 'Renforcer la préparation locale', 'Garder les plans de prévention actuels'],
    ['Les infrastructures et la protection progressent dans deux ans.', 'La préparation et l’entraide progressent, mais les infrastructures restent exposées.', 'La prévention utilise les moyens actuels, sans nouvel équipement.'],
  ],
  [
    'Comment financer les dépenses de crise ?',
    'Les mesures de crise demandent de l’argent. Réduire les dépenses ou augmenter les recettes limite le besoin de nouveaux emprunts.',
    ['Réduire des dépenses moins prioritaires', 'Augmenter les recettes fiscales', 'Garder les moyens engagés'],
    ['Les dépenses diminuent, mais des services reculent pendant la crise.', 'Les contribuables financent davantage le budget, avec une baisse de confiance.', 'Les services gardent leurs moyens et le besoin d’emprunter reste à financer.'],
  ],
  [
    'Que faut-il soutenir à la sortie de la crise ?',
    'La période la plus difficile passe. Les aides temporaires ont une date de fin, mais certains équipements et besoins restent fragiles.',
    ['Réparer les équipements fragilisés', 'Créer une aide de proximité durable', 'Reprendre le programme déjà prévu'],
    ['L’état des équipements s’améliore, avec des travaux à financer cette année.', 'Le soutien progresse, avec une dépense qui continue après les aides exceptionnelles.', 'Les aides temporaires suivent leur fin prévue, sans soutien supplémentaire.'],
  ],
  [
    'Comment mieux utiliser les équipements ouverts ?',
    'Les équipements en service demandent des moyens adaptés. Vous pouvez améliorer leurs aménagements ou leur fonctionnement quotidien.',
    ['Compléter les aménagements', 'Renforcer les moyens de fonctionnement', 'Garder les moyens prévus'],
    ['Les installations et les services progressent, avec des travaux supplémentaires.', 'Les services progressent, avec une dépense supplémentaire chaque année.', 'Les difficultés d’utilisation restent plus lentes à corriger.'],
  ],
  [
    'Comment améliorer le travail des services publics ?',
    'De nouveaux outils ne suffisent pas à changer les habitudes. Vous pouvez accompagner les équipes ou réduire certaines tâches.',
    ['Aider les équipes à changer leurs pratiques', 'Supprimer des tâches moins prioritaires', 'Garder les méthodes actuelles'],
    ['L’aide coûte chaque année ; l’amélioration des services arrive dans un an.', 'Les dépenses diminuent, mais certaines fonctions sont abandonnées.', 'Les équipes continuent avec leurs méthodes et leurs moyens actuels.'],
  ],
  [
    'Que faire quand les intérêts pèsent sur le budget ?',
    'Les intérêts de la dette utilisent une partie du budget. Cet argent est moins disponible pour les services et les travaux.',
    ['Augmenter les recettes fiscales', 'Réduire des dépenses moins prioritaires', 'Garder les engagements prévus'],
    ['Le besoin d’emprunter diminue, mais les contribuables paient davantage.', 'Le besoin d’emprunter diminue, mais certains services reculent.', 'Le programme continue et les intérêts restent à financer.'],
  ],
  [
    'Faut-il réduire un peu le déficit ?',
    'Vous pouvez ajuster les dépenses ou les recettes sans annuler les travaux déjà engagés. Même un petit changement a des conséquences.',
    ['Réduire un peu les dépenses courantes', 'Augmenter un peu les recettes fiscales', 'Garder le budget actuel'],
    ['Les dépenses diminuent chaque année, mais certains services ont moins de moyens.', 'Le budget reçoit plus chaque année, mais les contribuables paient davantage.', 'Ce choix ne réduit pas l’écart entre les recettes et les dépenses.'],
  ],
  [
    'Comment rendre les services plus proches à la campagne ?',
    'Des habitants des zones rurales restent loin de certains services. Des lieux partagés ou des équipes mobiles peuvent améliorer l’accès.',
    ['Participer à des lieux d’accueil partagés', 'Renforcer les équipes mobiles', 'Partager autrement les horaires existants'],
    ['L’accès aux services progresse dans un an, à l’ouverture des lieux.', 'L’aide de proximité progresse, avec une dépense supplémentaire chaque année.', 'Les lieux moins servis gagnent des horaires, mais d’autres en perdent.'],
  ],
  [
    'Comment entretenir les infrastructures qui vieillissent ?',
    'Les infrastructures existantes s’usent pendant que les nouveaux projets avancent. Il faut aussi financer leur entretien.',
    ['Remplacer les éléments les plus abîmés', 'Renforcer l’entretien préventif', 'Garder le programme d’entretien actuel'],
    ['L’état des infrastructures progresse, avec moins d’argent disponible pour d’autres projets.', 'L’état et la préparation aux incidents progressent, avec une dépense chaque année.', 'Une partie de l’usure n’est pas réparée et l’état des infrastructures recule.'],
  ],
  [
    'Faut-il renforcer la recherche pour les années à venir ?',
    'La recherche demande des équipements et des moyens réguliers. Les résultats peuvent dépasser la fin de votre mandat.',
    ['Moderniser les équipements de recherche', 'Renforcer les moyens réguliers de recherche', 'Garder les programmes déjà engagés'],
    ['Les équipements seront disponibles dans deux ans, après la fin du mandat.', 'La recherche reçoit des moyens chaque année, sans découverte garantie.', 'Les programmes continuent sans financement supplémentaire.'],
  ],
  [
    'Comment financer la protection sociale après la crise ?',
    'Des besoins d’aide restent importants après la crise. Vous pouvez renforcer le soutien ou augmenter les recettes qui le financent.',
    ['Renforcer une aide ciblée', 'Augmenter les recettes de protection sociale', 'Garder les aides actuelles'],
    ['Le soutien progresse, avec une dépense supplémentaire chaque année.', 'Les recettes progressent, mais les personnes concernées contribuent davantage.', 'Les aides continuent, sans réponse supplémentaire aux nouveaux besoins.'],
  ],
  [
    'Faut-il lancer des travaux livrés après votre mandat ?',
    'Un programme de travaux peut mieux préparer les infrastructures aux risques. Il prend deux ans et serait livré après votre départ.',
    ['Lancer le programme de travaux de deux ans', 'Réparer quelques équipements maintenant', 'Laisser le prochain mandat décider'],
    ['La protection et l’état des infrastructures progressent dans deux ans.', 'L’état des équipements progresse tout de suite, avec des travaux limités.', 'Le programme reste à décider et à financer.'],
  ],
  [
    'Faut-il ajouter une dernière aide ?',
    'Les aides exceptionnelles ont chacune leur date de fin. Vous pouvez créer une nouvelle aide d’un an ou un soutien plus petit et durable.',
    ['Créer une dernière aide d’un an', 'Créer une aide durable plus petite', 'Ne pas ajouter de nouvelle aide'],
    ['Le soutien progresse cette année ; la dépense s’arrête après le mandat.', 'Le soutien progresse et le prochain mandat devra continuer à le financer.', 'Les aides déjà décidées suivent leur calendrier ; certains besoins restent.'],
  ],
  [
    'Comment suivre les programmes avant votre départ ?',
    'Des programmes peuvent être terminés, en travaux ou refusés. Le prochain mandat doit savoir ce qui a été engagé.',
    ['Renforcer l’équipe de suivi', 'Moderniser les outils de suivi', 'Transmettre le suivi actuel'],
    ['Le suivi des équipements progresse, avec des dépenses chaque année.', 'Le suivi des équipements progresse, avec un achat à financer cette année.', 'Les outils et les moyens de suivi restent les mêmes.'],
  ],
  [
    'Quels moyens laisser aux services du quotidien ?',
    'Les services publics continueront après votre départ. Vous pouvez renforcer les équipes ou améliorer leurs locaux.',
    ['Renforcer les équipes d’accueil', 'Adapter les installations existantes', 'Garder les moyens actuels'],
    ['L’accueil progresse et le prochain mandat devra continuer à le financer.', 'Les locaux et les services progressent, sans personnel supplémentaire.', 'Les services continuent avec leurs moyens actuels et leurs manques restants.'],
  ],
  [
    'Faut-il réparer encore les infrastructures ?',
    'Les infrastructures portent la trace des choix passés. De derniers travaux peuvent améliorer leur état avant la fin du mandat.',
    ['Réparer les éléments les plus abîmés', 'Renforcer l’entretien régulier', 'Garder le programme existant'],
    ['L’état des infrastructures et leur préparation aux incidents progressent, avec de nouveaux travaux à financer.', 'L’état des infrastructures progresse et la dépense continue après le mandat.', 'Les travaux prévus continuent, sans réduire davantage le retard d’entretien.'],
  ],
  [
    'Comment préparer les services à une prochaine crise ?',
    'Une crise future peut demander des équipements et une organisation adaptés. Leur préparation doit être financée dès aujourd’hui.',
    ['Moderniser les équipements de prévention', 'Renforcer la préparation locale', 'Garder les moyens de préparation actuels'],
    ['Les équipements et la préparation aux crises progressent dès maintenant.', 'La préparation et l’entraide progressent, avec une dépense même sans crise.', 'Les programmes actuels continuent, sans protection supplémentaire.'],
  ],
  [
    'Quels impôts laisser pour le prochain mandat ?',
    'Votre dernier choix fiscal change aussi les recettes des prochaines années. Une baisse laisse moins d’argent au budget.',
    ['Augmenter les recettes fiscales', 'Réduire les impôts', 'Garder les règles fiscales actuelles'],
    ['Les contribuables concernés paient davantage et la confiance baisse.', 'Les contribuables paient moins, mais le prochain budget reçoit moins d’argent.', 'Le prochain mandat garde les recettes prévues, sans ajout.'],
  ],
  [
    'Faut-il encore réduire le besoin d’emprunter ?',
    'Réduire les dépenses ou augmenter les recettes limite les nouveaux besoins d’emprunt. Cela n’efface pas la dette déjà accumulée.',
    ['Réduire des dépenses moins prioritaires', 'Augmenter les recettes fiscales', 'Garder les engagements actuels'],
    ['Le budget dépense moins chaque année, mais certains services reculent.', 'Le budget reçoit plus chaque année, mais les contribuables paient davantage.', 'Les services continuent ; ce choix ne réduit pas les nouveaux besoins d’emprunt.'],
  ],
  [
    'Faut-il laisser un nouveau chantier au prochain mandat ?',
    'Un nouveau programme améliorerait les équipements et les services dans deux ans. Il coûterait aussi de l’argent à faire fonctionner.',
    ['Lancer un programme pour les services futurs', 'Réparer les équipements existants', 'Laisser le prochain mandat choisir'],
    ['Dans deux ans, les services progressent et de nouvelles dépenses de fonctionnement commencent.', 'L’état des équipements progresse dès maintenant, avec des travaux limités.', 'Le projet reste à choisir et à financer ; aucun nouvel équipement n’est engagé.'],
  ],
  [
    'Quel dernier choix laisser au prochain mandat ?',
    'Vous arrivez au bilan des 45 décisions et des cinq budgets. Un dernier choix peut ajouter du soutien ou des recettes pour la suite.',
    ['Renforcer durablement l’accompagnement', 'Augmenter les recettes fiscales', 'Terminer sans nouvel engagement'],
    ['Le soutien et les services progressent ; le prochain mandat devra continuer à les financer.', 'Le prochain budget reçoit plus, mais les contribuables paient davantage.', 'Le bilan conserve les réalisations, les engagements et les besoins restants.'],
  ],
];
