import { icon } from "./icons.ts";
import { planner } from "./planner.ts";
import { AMBITIONS, ambitionFor } from "./ambitions.ts";
import { deliveryFeed, projects, world, worldArt } from "./world.ts";
import type { WorldOptions } from "./world.ts";
import { choicesFor, DOMAINS, preview, score } from "./engine.ts";
import { escape as e } from "./sharing.ts";
import type { Game, Mode } from "./types.ts";
export type Screen = "select" | "mandate" | "play" | "result";
export type View = "decision" | "territory" | "finance" | "journal" | "plan";
export const n = (v: number, digits = 1) => new Intl.NumberFormat("fr-FR", { maximumFractionDigits: digits }).format(v);
const button = (action: string, label: string, cls = "button") => `<button class="${cls}" data-action="${action}">${label}</button>`;
const eyebrow = (text: string) => `<p class="eyebrow">${text}</p>`;

/** A schematic choropleth, not an illustration or a real district boundary. */
export function territoryMap(g: Game, small = false): string {
  const shapes = g.mode === "municipal" ? ["M40 200 260 175 235 390 50 380Z", "M70 40 340 40 325 190 260 175 40 200Z", "M360 55 550 100 545 355 270 390 310 220Z"] : ["M245 30 385 65 375 190 260 185 195 100Z", "M390 80 520 145 480 285 380 235 375 190Z", "M95 125 195 100 260 185 225 310 105 280Z", "M225 310 260 185 380 235 480 285 390 390 285 370Z"];
  return `<svg class="territory-map ${small ? "map-small" : ""}" viewBox="0 0 600 420" role="img" aria-label="Carte schématique : ${g.areas.map(a => `${e(a.name)}, services ${Math.round(a.services)} sur 100`).join(" ; ")}"><path d="M0 60H600M0 120H600M0 180H600M0 240H600M0 300H600M0 360H600M60 0V420M120 0V420M180 0V420M240 0V420M300 0V420M360 0V420M420 0V420M480 0V420M540 0V420" fill="none" stroke="currentColor" stroke-opacity=".07"/>${shapes.map((s, i) => `<path d="${s}" fill="${g.mode === "municipal" ? "#3d8474" : "#496982"}" fill-opacity="${.25 + g.areas[i].services / 180}" stroke="#91b5b7" stroke-width="1.5"/>`).join("")}${g.mode === "municipal" ? '<path d="M370 -10C340 70 360 120 328 195S280 310 244 430" stroke="#426e86" stroke-width="16" fill="none"/><path d="M370 -10C340 70 360 120 328 195S280 310 244 430" stroke="#7aa6b8" stroke-width="1" fill="none"/>' : '<path d="M292 100 420 184 320 330 178 230Z" stroke="#94c4dd" stroke-dasharray="5 7" fill="none" opacity=".7"/>'}${g.areas.map((a, i) => { const x = g.mode === "municipal" ? [145, 207, 427][i] : [295, 427, 175, 325][i]; const y = g.mode === "municipal" ? [285, 110, 235][i] : [100, 178, 210, 320][i]; return `<g><circle cx="${x}" cy="${y}" r="${7 + a.services / 9}" fill="#d7f2dd" fill-opacity=".12"/><circle cx="${x}" cy="${y}" r="5" fill="${a.services >= 60 ? "#b9e7c5" : "#edc488"}"/>${small ? "" : `<text x="${x}" y="${y + 32}" text-anchor="middle" fill="#f2f7f4" font-size="14" font-family="Source Sans 3, sans-serif">${e(a.name)}</text><text x="${x}" y="${y + 51}" text-anchor="middle" fill="#b8cbd1" font-size="12" font-family="Source Sans 3, sans-serif">Services ${Math.round(a.services)}/100</text>`}</g>`; }).join("")}</svg>`;
}
export function selection(saved: Game | null, light = false): string {
  return `<section class="mandate-selection"><div class="selection-heading">${eyebrow("UNE RESPONSABILITÉ. MILLE ARBITRAGES.")}<h1 tabindex="-1">Choisissez votre <em>mandat.</em></h1><p class="lead">Une ville à transformer. Un pays à piloter. À vous de décider.</p></div>${saved ? `<div class="resume"><span><strong>Le mandat continue.</strong> ${e(DOMAINS[saved.mode].place)} · ${saved.turn}/${DOMAINS[saved.mode].turns} ans</span>${button("resume", "Reprendre", "button compact")}</div>` : ""}<div class="mode-grid">${(["municipal", "national"] as Mode[]).map(mode => {
    const d = DOMAINS[mode];
    return `<button class="mode-card ${mode}" data-action="mode" data-mode="${mode}"><div class="mode-art">${worldArt(mode, { light })}<span class="mode-number">${mode === "municipal" ? "01 / LE TERRITOIRE" : "02 / LE PAYS"}</span><span class="mode-art-caption">${mode === "municipal" ? "VAL-SUR-RIVE" : "FRANCE"}<small>Scénario fictif</small></span></div><div class="mode-copy"><span class="eyebrow">${e(d.role)}</span><h2>${e(d.label)}</h2><p>${mode === "municipal" ? "Des écoles à rénover. Des quartiers à protéger. Un avenir à financer." : "Des services à préserver. Une dette à contenir. Des crises à traverser."}</p><div class="mode-meta"><span>${d.duration}</span><span>${mode === "municipal" ? "Stratégie territoriale" : "Grands arbitrages"}</span></div><span class="mode-cta">${mode === "municipal" ? "Choisir ma ville" : "Prendre les commandes"}</span></div></button>`;
  }).join("")}</div><div class="selection-footer">${button("helper", "Quel mode me convient ?", "text-button")}<p>Sans compte · Sauvegarde automatique · Hypothèses ouvertes</p><a href="/mandats/methode/">Comprendre les règles</a><a href="/mandats/comprendre/">Les guides</a></div></section>`;
}
export function pulse(g: Game): string {
  const d = DOMAINS[g.mode];
  const financeValue = g.mode === "municipal" ? `${n(g.finance.cash)} M€` : `${n(g.finance.debt / g.finance.gdp * 100)} %`;
  return `<div class="pulse" aria-label="État du mandat"><div><span>${g.mode === "municipal" ? "Trésorerie" : "Dette / PIB"}</span><strong>${financeValue}</strong></div><div><span>Services</span><strong>${Math.round(g.metrics.services)}<small>/100</small></strong></div><div><span>Résilience</span><strong>${Math.round(g.metrics.resilience)}<small>/100</small></strong></div><div class="pulse-year"><span>${e(d.role.split(" et")[0])}</span><strong>${g.turn}/${d.turns}<small> tours</small></strong></div></div>`;
}
export function ambitionPicker(g: Game, action = "ambition"): string {
  if (g.version === 1 || (g.turn > 0 && action === "ambition")) return "";
  return `<div class="ambition-picker" role="group" aria-label="Priorité du mandat">${Object.entries(AMBITIONS).map(([key, a]) => `<button class="ambition-option" data-action="${action}" data-ambition="${key}" aria-pressed="${(g.ambition ?? "equilibre") === key}"><strong>${a.short}</strong><span>${a.description}</span></button>`).join("")}</div>`;
}
export function mandateSetup(g: Game, opts: WorldOptions = {}): string {
  const d = DOMAINS[g.mode];
  return `<section class="mandate-setup"><div class="mandate-portrait">${worldArt(g.mode,opts)}<div><p>${e(d.role)}</p><strong>${e(d.place)}</strong></div></div><article>${eyebrow("AVANT VOTRE PREMIÈRE DÉCISION")}<h1 tabindex="-1">Quel cap donnez-vous <br>à votre mandat ?</h1><p class="lead">Choisissez votre priorité. Elle guidera votre bilan de fin de mandat.</p><div class="initial-cap-options" role="group" aria-label="Cap du mandat">${Object.entries(AMBITIONS).map(([key,a])=>`<button class="initial-cap-card" data-action="choose-cap" data-ambition="${key}">${icon(({equilibre:"balance",services:"people",resilience:"leaf"} as const)[key as keyof typeof AMBITIONS])}<span><strong>${e(a.label)}</strong><span>${e(a.description)}</span></span></button>`).join("")}</div><p class="initial-cap-note">Un choix pour tout le mandat.</p><details class="decision-context"><summary>Votre situation de départ</summary><p>${e(d.intro)}</p><p>${e(d.scope)}</p><ul>${d.objectives.map(o=>`<li>${e(o)}</li>`).join("")}</ul></details>${button("new","Changer de mandat","text-button")}</article></section>`;
}
function decision(g: Game): string {
  const d = DOMAINS[g.mode]; const dossier = d.dossiers[g.turn];
  return `<article class="dossier">${eyebrow(`ANNÉE ${g.turn + 1} / ${d.turns} <span>· ${e(dossier.category)}</span>`)}<h1 tabindex="-1">${e(dossier.title)}</h1><p class="story">${e(dossier.story.split(/(?<=\.)\s/)[0])}</p><div class="choices">${choicesFor(g).map((c, i) => { const p = preview(g, c.id); return `<button class="choice" data-action="choose" data-choice="${c.id}" ${p.error ? "disabled" : ""}><span class="choice-top"><span class="choice-index">${String(i + 1).padStart(2, "0")}</span><strong>${e(c.title)}</strong></span><span class="choice-facts"><span class="cost">${e(c.cost)}</span></span><span class="tradeoff"><span>${e(c.delayed ? c.benefit.replace("à la livraison", `en année ${g.turn + c.delayed.after + 1}`) : c.benefit)}</span><span>${e(c.sacrifice)}</span></span>${p.error ? `<span class="choice-error">${e(p.error)}</span>` : ""}</button>`; }).join("")}</div><details class="decision-context"><summary>Le contexte en détail</summary><p>${e(dossier.story)}</p>${choicesFor(g).map(c => `<p><strong>${e(c.title)}</strong> : ${e(c.description)}</p>`).join("")}<p>${e(dossier.advisor)}</p></details></article>`;
}
export function finance(g: Game): string {
  const d = DOMAINS[g.mode]; const l = g.history.at(-1)?.ledger;
  const rows = l ? [["Recettes", l.revenue], ["Dépenses courantes hors intérêts", l.operating], ["Intérêts", l.interest], ["Épargne brute", l.savings], ["Investissement", l.investment], ["Subventions d'investissement", l.grants], ["Capital remboursé", l.repayment], ["Financement nouveau", l.borrowing], ["Dette en fin d'année", l.debt]] as const : [["Recettes héritées", g.finance.revenue], ["Dépenses courantes héritées", g.finance.operating], ["Dette héritée", g.finance.debt]] as const;
  return `<article class="finance-panel">${eyebrow(`COMPTES DU MANDAT · ${d.unit}`)}<h1 tabindex="-1">Chaque choix laisse une trace.</h1><p>${g.mode === "municipal" ? "L'épargne finance d'abord le remboursement. L'emprunt complète seulement le financement des investissements." : "Le déficit inclut les intérêts et l'investissement. Il accroît la dette ; le ratio dépend aussi du PIB nominal."}</p>${trajectory(g)}<dl class="ledger">${rows.map(([label, value]) => `<div><dt>${label}</dt><dd>${n(value)} <small>${d.unit}</small></dd></div>`).join("")}</dl>${g.mode === "national" ? `<p class="finance-note">${l ? `Déficit de l'année : <strong>${n(l.deficit)} Md€</strong>. ` : ""}PIB nominal du scénario : ${n(l?.gdp ?? g.finance.gdp)} Md€. Taux moyen de la dette : ${n(g.finance.rate * 100, 2)} %.</p>` : `<p class="finance-note">Trésorerie : <strong>${n(g.finance.cash)} M€</strong>. La capacité de désendettement est un indicateur analytique, pas un plafond légal unique.</p>`}<details><summary>Voir les comptes année par année</summary><div class="year-ledgers">${g.history.map(t => `<section><h3>Année ${t.year}</h3><p>${e(t.title)}</p><dl><div><dt>Recettes</dt><dd>${n(t.ledger.revenue)} ${d.unit}</dd></div><div><dt>Dette</dt><dd>${n(t.ledger.debt)} ${d.unit}</dd></div><div><dt>Services</dt><dd>${Math.round(t.metrics.services)}/100</dd></div></dl></section>`).join("") || "<p>Vos premiers comptes apparaîtront après une décision.</p>"}</div></details></article>`;
}
export function trajectory(g: Game): string {
  const base = DOMAINS[g.mode].initial().finance.debt; const values = [base, ...g.history.map(t => t.ledger.debt)];
  const min = Math.min(...values) * .9, max = Math.max(...values) * 1.05;
  const points = values.map((v, i) => `${20 + i * 360 / Math.max(1, values.length - 1)},${105 - (v - min) / Math.max(1, max - min) * 80}`).join(" ");
  return `<figure class="trajectory"><figcaption>Trajectoire de dette <span>${n(values.at(-1)!)} ${DOMAINS[g.mode].unit}</span></figcaption><svg viewBox="0 0 400 135" role="img" aria-label="Dette du scénario par année : ${values.map(v => n(v)).join(", ")} ${DOMAINS[g.mode].unit}"><path d="M20 112H380" stroke="#44616d"/><polyline points="${points}" stroke="#a7ddc3" stroke-width="3" fill="none"/><text x="20" y="132" fill="#b5c8cf" font-size="11">Héritage</text><text x="380" y="132" text-anchor="end" fill="#b5c8cf" font-size="11">Année ${g.turn}</text></svg><p>Échelle ajustée à la trajectoire, départ différent de zéro.</p></figure>`;
}
export function governanceIndicators(g: Game): string {
  const labels = { services: "Services", cohesion: "Cohésion", trust: "Confiance", resilience: "Résilience", assets: "Patrimoine" } as const;
  return `<section class="governance-indicators" aria-labelledby="indicators-title"><h2 id="indicators-title">Le pouls du mandat</h2><p>Indices de simulation sur 100. La confiance représente un état du jeu, pas une intention de vote.</p><dl>${Object.entries(labels).map(([key, label]) => `<div><dt>${label}</dt><dd>${Math.round(g.metrics[key as keyof typeof labels])}<small>/100</small></dd></div>`).join("")}</dl></section>`;
}
export function territory(g: Game, opts: WorldOptions = {}): string {
  return `<article class="territory-panel">${eyebrow("LE TERRITOIRE EN DÉTAIL")}<h1 tabindex="-1">Le territoire vous répond.</h1><p>${g.mode === "municipal" ? "Trois quartiers, des besoins différents. Les effets d'un projet ciblé apparaissent à sa livraison." : "Quatre profils territoriaux fictifs. Cette carte schématique ne décrit pas des régions administratives réelles."}</p><div class="mobile-territory-world">${world(g, opts)}</div>${governanceIndicators(g)}${territoryMap(g)}<div class="area-list">${g.areas.map(a => `<section><h2>${e(a.name)}</h2><p>${e(a.need)}</p><div class="area-meters"><label>Services <strong>${Math.round(a.services)}/100</strong><meter min="0" max="100" value="${a.services}">${Math.round(a.services)}</meter></label><label>Résilience <strong>${Math.round(a.resilience)}/100</strong><meter min="0" max="100" value="${a.resilience}">${Math.round(a.resilience)}</meter></label></div></section>`).join("")}</div></article>`;
}
function journal(g: Game): string {
  return `<article class="journal">${eyebrow("VOTRE CARNET DE MANDAT")}<h1 tabindex="-1">Les décisions restent.</h1>${g.history.length ? g.history.map(t => `<section><span class="year-label">ANNÉE ${t.year}</span><h2>${e(t.title)}</h2><p class="event-label">${e(t.event)}</p><ul>${t.messages.map(m => `<li>${e(m)}</li>`).join("")}</ul></section>`).join("") : "<p>Le premier dossier vous attend. Chaque année sera conservée ici.</p>"}<h2>Engagements à livrer</h2>${g.pending.length ? `<ul>${g.pending.map(p => `<li>Année ${p.due + 1} : ${e(p.label)}</li>`).join("")}</ul>` : "<p>Aucun chantier en attente de livraison.</p>"}</article>`;
}
function turnReport(g: Game): string {
  const t = g.history.at(-1)!; const before = g.history.at(-2)?.metrics ?? DOMAINS[g.mode].initial().metrics;
  const delivered = projects(g).filter(p => p.recent && p.state === "delivered");
  return `<article class="resolution">${eyebrow(`ANNÉE ${g.turn} · LE BILAN`)}<h2>${e(t.title)}</h2><p class="resolution-event">${e(t.event)}</p>${delivered.length ? `<div class="completion-stamp">${icon("check")}<div><small>LES DÉCISIONS DEVIENNENT VISIBLES</small><strong>${delivered.length} programme${delivered.length > 1 ? "s" : ""} en service</strong></div></div>` : ""}<div class="change-grid">${(["services", "cohesion", "resilience"] as const).map(key => {
    const delta = g.metrics[key] - before[key];
    return `<div class="${delta < 0 ? "delta-negative" : "delta-positive"}"><span>${({ services: "Services", cohesion: "Cohésion", resilience: "Résilience" })[key]}</span><strong>${delta > 0 ? "+" : ""}${n(delta)}</strong><small>${Math.round(before[key])} → ${Math.round(g.metrics[key])}/100</small></div>`;
  }).join("")}</div><div class="resolution-notes"><h2>La trace de votre décision</h2><ul>${t.messages.map(m => `<li>${e(m)}</li>`).join("")}</ul></div><div class="finance-strip"><span>Dette <strong>${n(t.ledger.debt)} ${DOMAINS[g.mode].unit}</strong></span><span>${g.mode === "municipal" ? "Épargne brute" : "Déficit"} <strong>${n(g.mode === "municipal" ? t.ledger.savings : t.ledger.deficit)} ${DOMAINS[g.mode].unit}</strong></span></div><button class="text-button" data-action="share-decision">Partager cette décision</button><p class="hint">Effets du choix, livraisons, usure et événement sont cumulés dans ce bilan.</p></article>`;
}
function turnFeedback(g: Game): string {
  if (!g.turn) return "";
  const before = g.history.at(-2)?.metrics ?? DOMAINS[g.mode].initial().metrics;
  const delta = g.metrics.services - before.services;
  return `<details class="turn-feedback"><summary><span class="turn-confirmation">${icon("check")} Année ${g.turn} terminée</span><span>Services ${delta > 0 ? "+" : ""}${n(delta)} <small>· Voir les effets</small></span></summary>${turnReport(g)}</details>`;
}
export function result(g: Game, shared = false): string {
  const s = score(g); const d = DOMAINS[g.mode];
  return `<article class="result">${eyebrow(`${shared ? "RÉSULTAT PARTAGÉ" : "VOTRE HÉRITAGE"} · ${e(d.place)}`)}<h1 tabindex="-1">${s.legacy}</h1><p class="score-number">${s.total}<span>/100</span></p><p class="lead">Votre force : <strong>${s.strength.toLocaleLowerCase("fr")}</strong>.<br>Le prochain chantier : <strong>${s.weakness.toLocaleLowerCase("fr")}</strong>.</p><div class="score-dimensions">${Object.entries(s.dimensions).map(([key, v]) => `<div><span>${({ finances: "Finances durables", services: "Services", cohesion: g.version === 1 ? "Cohésion" : "Cohésion & confiance", resilience: "Résilience & patrimoine" })[key]}</span><strong>${Math.round(v)}/100</strong><meter min="0" max="100" value="${v}">${Math.round(v)}</meter></div>`).join("")}</div><details class="score-explanation"><summary>Comprendre mon score</summary><p class="scope">${g.version === 1 ? "Chaque dimension pèse 25 %." : `Priorité : ${ambitionFor(g).label}. Finances ${ambitionFor(g).weights.finances * 100} %, services ${ambitionFor(g).weights.services * 100} %, cohésion/confiance ${ambitionFor(g).weights.cohesion * 100} %, résilience ${ambitionFor(g).weights.resilience * 100} %.`} ${s.terminalPenalty ? `Charges non livrées : −${s.terminalPenalty} point.` : ""} Le score exprime les règles du jeu, pas la qualité réelle d'un gouvernement ni une intention de vote.</p></details><div class="result-actions">${button("share", "Partager mon héritage", "button primary")}${button("replay", "Rejouer le même défi", "button")}${button("open-plan", "Comparer une autre stratégie", "button")}${button("new", "Changer de mandat", "text-button")}</div>${g.version === 2 ? `<details class="replay-priority"><summary>Rejouer avec une autre priorité</summary>${ambitionPicker(g, "replay-ambition")}</details>` : ""}<details><summary>Relire mon mandat et mes engagements</summary>${journal(g)}</details></article>`;
}
export function gameShell(g: Game, screen: Screen, view: View, shared = false, opts: WorldOptions = {}, planIds: string[] = g.choices): string {
  const content = screen === "result" ? result(g, shared) : ({ decision: () => g.turn === DOMAINS[g.mode].turns ? result(g, shared) : decision(g), territory: () => territory(g, opts), finance: () => finance(g), journal: () => journal(g), plan: () => planner(g, planIds) })[view]();
  const timeline = `<ol class="mandate-timeline" aria-label="Progression du mandat">${Array.from({ length: DOMAINS[g.mode].turns }, (_, i) => `<li class="${i < g.turn ? "completed" : i === g.turn ? "current" : ""}"><span>${i < g.turn ? icon("check") : i + 1}</span><small>AN ${i + 1}</small></li>`).join("")}</ol>`;
  const tabs = screen === "play" ? `<nav class="game-tabs" aria-label="Vues du mandat">${([ ["decision", "Décider"], ["territory", "Territoire"], ["finance", "Finances"], ["journal", "Journal"], ["plan", "Atelier"] ] as const).map(([id, label]) => `<button data-action="view" data-view="${id}" ${view === id ? 'aria-current="page"' : ""}>${icon(id)}${id === "decision" && g.turn === DOMAINS[g.mode].turns ? "Bilan" : label}</button>`).join("")}</nav>` : "";
  return `${pulse(g)}<div class="mobile-mandate-context"><span>${e(DOMAINS[g.mode].place)}</span><strong>Année ${Math.min(g.turn + 1, DOMAINS[g.mode].turns)}/${DOMAINS[g.mode].turns}</strong></div><div class="game-grid" data-screen="${screen}" data-view="${view}"><aside class="strategic-panel"><div class="world-heading"><div>${eyebrow(g.mode === "municipal" ? "VOTRE VILLE, VOTRE EMPREINTE" : "LA SALLE DES DÉCISIONS")}<h2>${g.mode === "municipal" ? "Val-sur-Rive" : "France"}</h2></div></div>${world(g, opts)}${timeline}<div class="strategic-underlay"><div class="strategic-metrics"><span>Confiance <strong>${Math.round(g.metrics.trust)}<small>/100</small></strong></span><span>Patrimoine <strong>${Math.round(g.metrics.assets)}<small>/100</small></strong></span><button class="text-button" data-action="light-mode" aria-pressed="${!!opts.light}">${opts.light ? "Vue illustrée" : "Vue légère"}</button></div>${deliveryFeed(g)}${trajectory(g)}</div></aside><div class="game-content">${tabs}${screen === "play" && view === "decision" && g.turn < DOMAINS[g.mode].turns ? turnFeedback(g) : ""}${content}</div></div>`;
}
