import type {
  NarrativeChoice,
  NarrativeEvent,
  NarrativeFamily,
} from "./narrative-types.ts";
import type { Effect } from "./types.ts";
import { NARRATIVE_EVENTS } from "./narrative-content.ts";

/** Fictional scenarios; amounts are simulation assumptions for national envelopes. */
export const REWORK_FAMILIES: NarrativeFamily[] = [
  {
    id: "automatisation-ia",
    title: "Transition industrielle",
    category: "Industrie et IA",
    summary: "Transformer la production et les métiers.",
    art: "industry",
    urgency: "Une transformation à préparer",
  },
  {
    id: "reseau-eau",
    title: "Réseau d’eau",
    category: "Eau",
    summary: "Protéger les usages avec des moyens limités.",
    art: "energy",
    urgency: "Les réserves baissent",
  },
  {
    id: "cyber-soins",
    title: "Continuité des soins",
    category: "Santé et cyberattaque",
    summary: "Rétablir les systèmes et maintenir les soins.",
    art: "hospital",
    urgency: "Service perturbé",
  },
  {
    id: "logistique-port",
    title: "Approvisionnements",
    category: "Port et logistique",
    summary: "Les flux de marchandises se réorganisent.",
    art: "industry",
    urgency: "Stocks limités",
  },
  {
    id: "occasion-science",
    title: "Recherche publique",
    category: "Recherche",
    summary: "Une occasion à transformer en résultat.",
    art: "nation",
    urgency: "Une occasion à saisir",
  },
  {
    id: "chaleur",
    title: "Chaleur et prévention",
    category: "Climat",
    summary: "Préparer les services et les lieux exposés.",
    art: "energy",
    urgency: "Préparer l’été",
  },
  {
    id: "logement-emploi",
    title: "Logement et emploi",
    category: "Logement",
    summary: "Rapprocher les logements et les activités.",
    art: "housing",
    urgency: "Un bassin se transforme",
  },
];
const response = (
  id: string,
  title: string,
  description: string,
  cost: string,
  benefit: string,
  sacrifice: string,
  effect: Effect,
  extra: Partial<NarrativeChoice> = {},
): NarrativeChoice => ({
  id,
  title,
  description,
  cost,
  benefit,
  sacrifice,
  effect,
  ...extra,
});
const project = (
  id: string,
  kind: string,
  label: string,
  place: string,
  dueAfter: number,
  deliveryEffect: Effect,
) => ({ project: { id, kind, label, place, dueAfter, deliveryEffect } });
const withdrawals: Record<
  string,
  Pick<NarrativeChoice, "description" | "benefit" | "sacrifice" | "effect">
> = {
  "service-rives": {
    description:
      "Renoncer aux locaux rénovés et conserver un service à capacité réduite.",
    benefit: "Aucune nouvelle tranche de rénovation n’est engagée.",
    sacrifice: "Les équipes gardent des locaux dégradés et moins de capacité.",
    effect: { services: -2, society: { publicStaff: -1 }, trust: -1 },
  },
  "site-depollue": {
    description:
      "Sécuriser la fermeture et accompagner les salariés sans rouvrir la production.",
    benefit: "La reprise industrielle ne mobilise plus de crédits.",
    sacrifice: "Les emplois attendus ne sont pas créés.",
    effect: { cohesion: -2, society: { workers: -2, businesses: -1 } },
  },
  "recharge-bus": {
    description:
      "Conserver la flotte existante et mettre fin au programme de conversion électrique.",
    benefit: "Les bus existants continuent leur service.",
    sacrifice: "La dépendance au carburant reste élevée.",
    effect: { resilience: -2, assets: -1 },
  },
  "residence-travail": {
    description:
      "Annuler la résidence et laisser les recrutements dépendre du marché locatif.",
    benefit: "Le budget n’engage aucune nouvelle construction.",
    sacrifice: "Les salariés recrutés peinent à se loger près du site.",
    effect: { society: { workers: -2 }, cohesion: -1 },
  },
  "audit-marche": {
    description:
      "Clore le contrôle indépendant et conserver les pièces sous la responsabilité du ministère.",
    benefit: "Les achats reprennent sans attendre les conclusions.",
    sacrifice: "Les soupçons restent sans vérification indépendante.",
    effect: { trust: -3 },
  },
  "programme-gare": {
    description:
      "Arrêter le programme près des transports et conserver le terrain dans son état actuel.",
    benefit: "Le terrain reste disponible pour un autre projet.",
    sacrifice: "La liste d’attente des logements abordables reste ouverte.",
    effect: { society: { vulnerable: -2 }, services: -1 },
  },
};
export const REWORK_BASE_EVENTS: NarrativeEvent[] = NARRATIVE_EVENTS.map(
  (event) => ({
    ...event,
    choices: event.choices.map((choice) => {
      const detail =
        choice.project?.action === "withdraw"
          ? withdrawals[choice.project.id]
          : undefined;
      return detail ? { ...choice, ...detail } : choice;
    }),
  }),
);
export const REWORK_EVENTS: NarrativeEvent[] = [
  {
    id: "ia-usine",
    familyId: "automatisation-ia",
    title: "L’usine prépare l’automatisation",
    body: "Une usine veut automatiser une partie de ses ateliers. Les salariés demandent une reconversion avant la suppression des postes. Une aide nationale peut soutenir un programme vérifiable.",
    turns: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    choices: [
      response(
        "former",
        "Conditionner l’aide aux reconversions",
        "Financer un programme dont la livraison est vérifiée avec les équipes et un gouvernement en fonction.",
        "1,2 Md€ d’investissement et 0,15 Md€/an de contrôle",
        "Les crédits sont engagés pour les reconversions.",
        "La formation demande du temps et des crédits.",
        { investment: 1.2, operating: 0.15 },
        project(
          "ia-reconversions",
          "industry",
          "Programme de reconversion industrielle",
          "val-des-forges",
          3,
          { cohesion: 3, society: { workers: 4, businesses: 2 } },
        ),
      ),
      response(
        "partager",
        "Négocier le partage des gains",
        "Obtenir une contribution à la formation et une part des gains pour les salariés.",
        "0,08 Md€/an de négociation",
        "Les salariés obtiennent une garantie matérielle.",
        "L’entreprise conserve moins de gains.",
        {
          operating: 0.08,
          society: { workers: 3, businesses: -2 },
          cohesion: 1,
        },
        { relationships: { social: 5, conservative: -3 } },
      ),
      response(
        "echelonner",
        "Échelonner l’automatisation",
        "Limiter la première vague et donner du temps aux équipes.",
        "0,25 Md€/an d’accompagnement",
        "Le changement de métiers arrive progressivement.",
        "Les gains de productivité sont retardés.",
        { operating: 0.25, society: { workers: 1, businesses: -1 } },
        project(
          "ia-pilote",
          "industry",
          "Atelier pilote avant automatisation",
          "val-des-forges",
          2,
          { assets: 2, society: { workers: 2 } },
        ),
      ),
    ],
  },
  {
    id: "eau-equipes",
    familyId: "reseau-eau",
    title: "Deux urgences sur le réseau d’eau",
    body: "Les réserves baissent et une fuite détourne une partie de l’eau disponible. Les équipes mobilisables ne peuvent pas sécuriser tous les usages en même temps.",
    turns: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    choices: [
      response(
        "potable",
        "Sécuriser l’eau potable",
        "Mobiliser les équipes sur la distribution aux habitants.",
        "0,35 Md€/an de distribution",
        "L’accès des ménages est protégé.",
        "Les usages agricoles restent contraints.",
        {
          operating: 0.35,
          society: { vulnerable: 3, businesses: -2 },
          area: "littoraux",
          services: 2,
          resilience: -1,
        },
      ),
      response(
        "fuite",
        "Réparer la fuite principale",
        "Engager les travaux qui réduiront durablement les pertes.",
        "0,8 Md€ d’investissement",
        "La réparation commence.",
        "La distribution reste tendue pendant les travaux.",
        { investment: 0.8, society: { vulnerable: -1 } },
        project(
          "eau-reparation",
          "energy",
          "Réparation du réseau d’eau",
          "montpellier",
          2,
          { resilience: 4, services: 2 },
        ),
      ),
      response(
        "prevention",
        "Prépositionner les équipes incendie",
        "Protéger les secteurs où les départs de feu menacent les infrastructures.",
        "0,2 Md€/an de prévention",
        "Les moyens d’intervention sont disponibles.",
        "La fuite attend et les restrictions continuent.",
        { operating: 0.2, resilience: 3, services: -1, area: "littoraux" },
      ),
    ],
  },
  {
    id: "cyber-hopital",
    familyId: "cyber-soins",
    title: "L’hôpital perd l’accès à ses systèmes",
    body: "Une cyberattaque bloque les dossiers de soins. Une sauvegarde existe, mais elle doit être vérifiée avant de reconnecter les services.",
    turns: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
    choices: [
      response(
        "isoler",
        "Isoler les systèmes touchés",
        "Fermer les connexions et assurer les soins avec les procédures de secours.",
        "0,3 Md€/an de continuité",
        "La contamination numérique est contenue.",
        "Les équipes travaillent plus lentement.",
        {
          operating: 0.3,
          resilience: 3,
          services: -1,
          society: { publicStaff: -1 },
        },
      ),
      response(
        "restaurer",
        "Restaurer une sauvegarde vérifiée",
        "Financer la vérification puis le rétablissement progressif des applications.",
        "0,65 Md€ d’investissement",
        "Le rétablissement est engagé.",
        "Les soins restent ralentis avant la remise en service.",
        { investment: 0.65, services: -1 },
        project(
          "cyber-restauration",
          "hospital",
          "Rétablissement des systèmes de soins",
          "hopital-des-rives",
          2,
          { services: 4, resilience: 2 },
        ),
      ),
      response(
        "transferer",
        "Réorienter les soins disponibles",
        "Organiser les transports vers les établissements ayant encore des capacités.",
        "0,45 Md€/an de transports",
        "Les patients sont accueillis ailleurs.",
        "Les établissements voisins absorbent la charge.",
        {
          operating: 0.45,
          services: 1,
          society: { publicStaff: -2 },
          area: "metropoles",
        },
      ),
    ],
  },
  {
    id: "port-bloque",
    familyId: "logistique-port",
    title: "Le port bloque les approvisionnements",
    body: "Une grève ralentit un port et les réserves diminuent. Les représentants demandent un accord sur les horaires et la sécurité des équipes.",
    turns: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    choices: [
      response(
        "accord",
        "Négocier les horaires et la sécurité",
        "Financer les aménagements convenus avec les partenaires.",
        "0,4 Md€/an",
        "Un accord matériel réduit le conflit.",
        "Les nouvelles conditions coûtent davantage aux exploitants.",
        {
          operating: 0.4,
          cohesion: 3,
          society: { workers: 3, businesses: -1 },
        },
        { relationships: { social: 5, regional: 3 } },
      ),
      response(
        "flux",
        "Réorganiser les flux",
        "Utiliser des capacités alternatives pour les marchandises prioritaires.",
        "0,55 Md€/an de logistique",
        "Les livraisons essentielles continuent.",
        "Les trajets s’allongent et les marges diminuent.",
        {
          operating: 0.55,
          services: 2,
          society: { businesses: -2 },
          resilience: 1,
        },
      ),
      response(
        "reserves",
        "Mobiliser les réserves essentielles",
        "Distribuer temporairement les stocks disponibles.",
        "0,18 Md€ de logistique et stocks consommés",
        "Les besoins urgents sont couverts.",
        "Les réserves de sécurité s’épuisent.",
        { investment: 0.18, services: 2, resilience: -3 },
      ),
    ],
  },
  {
    id: "science-stockage",
    familyId: "occasion-science",
    title: "Une équipe améliore le stockage d’énergie",
    body: "Une équipe de recherche présente un procédé prometteur. Il faut vérifier sa fiabilité avant de l’utiliser dans les services publics.",
    turns: [
      3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    ],
    choices: [
      response(
        "pilote",
        "Tester dans un service public",
        "Financer un essai limité avec des critères d’évaluation.",
        "0,4 Md€ d’investissement",
        "Un pilote permet une évaluation concrète.",
        "Les résultats arrivent après l’essai.",
        { investment: 0.4 },
        project(
          "science-pilote",
          "energy",
          "Essai de stockage d’énergie",
          "toulouse",
          3,
          { resilience: 3, assets: 2 },
        ),
      ),
      response(
        "partenariat",
        "Partager le développement industriel",
        "Associer des entreprises avec des obligations de diffusion publique.",
        "0,6 Md€ d’investissement et 0,05 Md€/an de suivi",
        "Des capacités industrielles se préparent.",
        "Le partenaire obtient une part des droits.",
        { investment: 0.6, operating: 0.05, society: { businesses: 2 } },
        project(
          "science-industrie",
          "industry",
          "Partenariat de stockage industriel",
          "val-des-forges",
          4,
          { assets: 4, resilience: 2 },
        ),
      ),
      response(
        "cooperation",
        "Ouvrir une coopération de recherche",
        "Partager les résultats et répartir les travaux entre laboratoires.",
        "0,2 Md€/an de recherche",
        "Les connaissances se diffusent.",
        "Le pays renonce à une exploitation exclusive.",
        {
          operating: 0.2,
          cohesion: 1,
          resilience: 1,
          society: { publicStaff: 1 },
        },
      ),
    ],
  },
  {
    id: "chaleur-ecoles",
    familyId: "chaleur",
    title: "Les écoles doivent préparer les fortes chaleurs",
    body: "Plusieurs établissements exposés à la chaleur manquent d’espaces frais. Les collectivités cherchent une réponse avant le prochain été.",
    turns: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    choices: [
      response(
        "ombrage",
        "Rénover les cours et les façades",
        "Financer l’ombre, la ventilation et les surfaces adaptées.",
        "1 Md€ d’investissement",
        "Les travaux sont engagés.",
        "La protection complète attend la livraison.",
        { investment: 1 },
        project(
          "ecoles-fraiches",
          "energy",
          "Protection des établissements contre la chaleur",
          "montpellier",
          3,
          { resilience: 4, services: 2 },
        ),
      ),
      response(
        "horaires",
        "Adapter les horaires et les lieux",
        "Organiser des plages de cours adaptées et des salles de repli.",
        "0,2 Md€/an d’organisation",
        "L’exposition des élèves baisse.",
        "Les familles réorganisent leurs journées.",
        {
          operating: 0.2,
          services: 2,
          society: { workers: -1, vulnerable: -1 },
          area: "littoraux",
        },
      ),
      response(
        "renforts",
        "Renforcer les services de prévention",
        "Mobiliser les équipes sanitaires et les espaces publics frais.",
        "0,45 Md€/an de personnels",
        "Les personnes exposées sont accompagnées.",
        "Les équipes sont moins disponibles ailleurs.",
        {
          operating: 0.45,
          resilience: 2,
          society: { publicStaff: -1, vulnerable: 2 },
        },
      ),
    ],
  },
  {
    id: "logements-vacants",
    familyId: "logement-emploi",
    title: "Des emplois arrivent, les logements manquent",
    body: "Un bassin recrute tandis que des logements restent vacants loin des lieux de travail. Les nouveaux salariés peinent à s’installer.",
    turns: [
      2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22,
    ],
    choices: [
      response(
        "location",
        "Garantir la remise en location",
        "Couvrir une part du risque locatif en échange de loyers encadrés.",
        "0,45 Md€/an de garanties",
        "Des logements existants deviennent accessibles.",
        "L’État assume une partie des impayés.",
        {
          operating: 0.45,
          cohesion: 2,
          society: { vulnerable: 3, affluent: -1 },
        },
      ),
      response(
        "conversion",
        "Convertir des bâtiments inutilisés",
        "Financer des autorisations et des travaux de transformation.",
        "1,3 Md€ d’investissement",
        "La construction de logements commence.",
        "Les logements ne seront disponibles qu’après les travaux.",
        { investment: 1.3 },
        project(
          "logements-conversion",
          "housing",
          "Conversion de bâtiments en logements",
          "gare-des-tilleuls",
          4,
          { services: 2, assets: 3, society: { workers: 3, vulnerable: 2 } },
        ),
      ),
      response(
        "trajets",
        "Organiser les trajets des salariés",
        "Desservir les logements disponibles et les lieux d’emploi.",
        "0,35 Md€/an de transports",
        "Les salariés accèdent aux postes proposés.",
        "Les trajets quotidiens restent plus longs.",
        {
          operating: 0.35,
          society: { workers: 2 },
          services: 1,
          resilience: -1,
          area: "metropoles",
        },
      ),
    ],
  },
  {
    id: "ia-services",
    familyId: "automatisation-ia",
    title: "Un assistant IA pour les démarches publiques",
    body: "Des agents proposent un assistant pour traiter les demandes simples. Les réponses sensibles exigent encore un contrôle humain.",
    turns: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
    choices: [
      response(
        "assister",
        "Garder la validation par un agent",
        "Tester l’assistance avec une décision humaine sur chaque dossier.",
        "0,5 Md€ d’investissement",
        "Les équipes disposent d’un outil à éprouver.",
        "Le gain dépend de personnels toujours présents.",
        { investment: 0.5 },
        project(
          "ia-demarches",
          "integrity",
          "Assistance contrôlée aux démarches",
          "paris",
          2,
          { services: 3, trust: 1 },
        ),
      ),
      response(
        "simples",
        "Automatiser les demandes sans enjeu sensible",
        "Réserver l’outil aux démarches simples et maintenir un recours humain.",
        "0,2 Md€/an et 0,3 Md€ d’investissement",
        "Les demandes simples sont traitées plus vite.",
        "Le traitement des situations complexes reste lent.",
        {
          operating: 0.2,
          investment: 0.3,
          services: 2,
          society: { publicStaff: -1 },
        },
      ),
      response(
        "guichets",
        "Renforcer les guichets existants",
        "Affecter des personnels aux démarches qui accumulent du retard.",
        "0,65 Md€/an de personnels",
        "Les usagers trouvent une réponse humaine.",
        "La dépense de personnel est durable.",
        {
          operating: 0.65,
          services: 2,
          society: { publicStaff: 2, vulnerable: 2 },
        },
      ),
    ],
  },
];
